### ISSUE TITLE
Vector is not sink-ing/processing files with one line of data

### ISSUE THREAD

**Issue by ruslankiskinov** [vectordotdev/vector#17600] opened 2023-06-05 08:04 UTC
### Problem

I have thousands of small JSON files containing only one line of JSON data that I need to import into Elasticsearch. 

Vector is processing only files that have more than one line of text.
I tried to change the fingerprint strategy because if it is not "device_and_inode" it does not even consider reading the small files.
If I add a second line of json data the file gets processed and imported in elaasticsearch.

Is there a problem with my configuration? 
Is this by design ?

### Configuration

```text
[sources.eid_hash]
type = "file"
include = ["SOME SOURCE PATH"]
read_from = "beginning"
fingerprint.strategy = "device_and_inode"


# Parsing the hash files. 
[transforms.json_parse_hash]
type = "remap"
inputs = [ "index-name" ]
source = ". = parse_json!(.message)"

# --- SINKS --- ------------------------------------------------------------------
[sinks.opensearch_hash]
type = "elasticsearch"
api_version = "v7"
inputs = [ "json_parse_hash" ]
endpoints = [ "https://localhost:9200" ]
compression = "none"
mode = "bulk"
bulk.index = "eid-hash"
auth.strategy = "basic"
auth.user = "...."
auth.password = "...."
tls.verify_certificate = false
acknowledgements.enabled = true
```

### Version

vector 0.29.1 (x86_64-pc-windows-msvc 74ae15e 2023-04-20 14:50:42.739094536)

### Example Data

{"checksum":"UWgX3AENI3R0kARtKTA1QeSKfltlbgitT8QYLHbdJM/au445ySUze2NvyPyCpnv5UO1QAdXz3G9g4GZD7uL8qQ==","source_file":"eid-mpozei-3892ec3c-f895-475d-bb9a-4fe6e3653f66_2023060509_010.log","source_path":"..","date_created":"2023-06-05T06:56:05.0066162Z","system_id":"eid-mpozei","events":["00f740cbde07476891b0e5392dc22df5","02cdc0f451944e24a3f00b6b48eb6c0a"]}

**Comment by neuronull** [comment] 2023-06-05 19:06
Hello @ruslankiskinov ,

Do your single line files have a newline or a carriage return by any chance? If the config does not specify, `\n` is used.

https://vector.dev/docs/reference/configuration/sources/file/#line_delimiter

**Comment by ruslankiskinov** [comment] 2023-06-06 06:50
Hi @neuronull,
The files don't contain any new line characters \n or \r\n. 
This means the record inside is not terminated with a new line. The new line was inserted only if there are more than one record in the file.
By the way, if multiple records are in the file separated with \r\n they are imported successfully. 
I didn't configure the newline parameter because it was not needed at the moment.
I don't know how this newline parameter can help as the file contains only one line and there is no new line in the file.

**Comment by jszwedko** [comment] 2023-06-06 13:29
This is expected behavior since the default checkpointer attempts to read one line to generate a "fingerprint" for the file. Without the newline, Vector can't be sure that it has read a full line of if it is reading a partial line. You can either update your writer to add a newline at the end of each line or you can use the `device_and_inode` checkpoint strategy.

I'll close this since it is expected behavior, but let us know if you have any other troubles!

**Closed by jszwedko** 2023-06-06 13:29 UTC
Labels: meta: awaiting author
