### ISSUE TITLE
DataDog Source -> Filter Transform -> DataDog Sink dropping kube_service tag

### ISSUE THREAD

**Issue by andrewegel** [vectordotdev/vector#14707] opened 2022-10-03 22:03 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Context & Brakground

At Confluent we're interested in utilizing Vector to filter out certain metrics from the DataDog agent before they're submitted to DataDog. Specifically we no longer want DataDog to ingest (and by extension bill us for) `container` and `datadog`-prefixed metrics. Since this functionality doesn't exist in the datadog agent (https://github.com/DataDog/datadog-agent/issues/2465), we're turning to Vector to do this filtering.

## Problem

Filtering of `container` and `datadog`-prefixed metrics works like a charm (See the attached vector conf we're using), but it was noticed that on the `kubernetes.pods.running` metrics, the `kube_service` tag with values that would match our services "disappeared". 

## An example

(Note that I'm tactically omitting sensitive company information, so apologies that its just a screen shot)

An example of this is in our DataDog metric query:

```
default_zero(sum:kubernetes.pods.running{cluster_name:NameOfOurCluster,kube_service:ServiceName} by {kube_service,host,cluster_name})
```

Bellow is a snapshot of when I enabled Vector filtering, and then disabled Vector filtering on the cluster `NameOfOurCluster` when filtering by the `kube_service:ServiceName` that "disappears":

![Screen Shot 2022-10-03 at 2 40 41 PM](https://user-images.githubusercontent.com/3142242/193692064-0f7e88f3-f5f6-4bb2-ae45-a34ef8efb633.png)

You can see that before the dip, DataDog was reporting that there were 4 "kube_service:ServiceName"-named Pods running (Not a real name, replaced with a sensitive service name) running in our `NameOfOurCluster` cluster, then it dropped to 0 (no data sent hence why I've wrapped DataDog query in `default_zero(...)` after I enabled Vector filtering, then came back after I disabled Vector filtering.

The Vector Conf I was using during this experiment was "pass through":

```
ources:
      datadog_agent:
        address: "[::]:8282"
        type: datadog_agent
        disable_logs: true
        disable_traces: true
        disable_metrics: false
    sinks:
      datadog:
        type: datadog_metrics
        inputs:
          - datadog_agent
        default_api_key: "${DD_API_KEY}"
```

### Configuration

```text
sources:
      datadog_agent:
        address: "[::]:8282"
        type: datadog_agent
        disable_logs: true
        disable_traces: true
        disable_metrics: false
    transforms:
      filter_tld_metrics:
        type: filter
        inputs:
          - datadog_agent
        condition: .namespace != "datadog" && .namespace != "container"
    sinks:
      datadog:
        type: datadog_metrics
        inputs:
          - filter_tld_metrics
        default_api_key: "${DD_API_KEY}"
```

### Version

0.23.3-distroless-libc

### Debug Output

```text
https://gist.github.com/andrewegel/a5bacaf541d27dc268078b9c0f22c2b5
```

### Additional Context

* Vector is running in kubernetes as a "side car" container next to the dd-agent DaemonSet (As in each node gets an instance of dd-agent & vector
* We have configured the dd-agent with `DD_VECTOR_METRICS_ENABLED=true` and `DD_VECTOR_METRICS_URL="http://127.0.0.1:8282"`

Further information (but not really relevant): We have a case open with datadog about this problem, we started there given the wording that Vector would be supported: https://docs.datadoghq.com/integrations/observability_pipelines/integrate_vector_with_datadog/?tab=yaml

But were told by DataDog that Vector support is mostly only availible through the community - So thats what this GitHub issue is for.

**Comment by spencergilbert** [comment] 2022-10-04 18:37
Hey @andrewegel, just to confirm you're only seeing that behavior with the configuration with the `filter` transform, not with the "passthrough" config?

**Comment by andrewegel** [comment] 2022-10-04 19:39
> Hey @andrewegel, just to confirm you're only seeing that behavior with the configuration with the filter transform, not with the "passthrough" config?

With both - The "passthrough" config the `kube_service` tag was missing.

**Comment by spencergilbert** [comment] 2022-10-04 19:45
Huh, OK... That's _definitely_ not expected. Let me see if I can reproduce this and track down the cause.

**Comment by andrewegel** [comment] 2022-10-04 20:56
FWIW I've connected with @spencergilbert over DataDog community Slack for quicker troubleshooting & comms. We'll report back any findings & resolutions here.

**Comment by spencergilbert** [comment] 2022-10-05 15:20
@andrewegel did some additional investigation that's pointed us toward the Datadog Agent as the root cause. It appears as though once we turn on the config that directs metrics to a Vector instance the agent stops sending the tag.

**Comment by jszwedko** [comment] 2022-10-05 16:03
> @andrewegel did some additional investigation that's pointed us toward the Datadog Agent as the root cause. It appears as though once we turn on the config that directs metrics to a Vector instance the agent stops sending the tag.

Are we sure that the Agent is sending the `kube_service` tag with each metric? Or is it something that is associated once Datadog ingests the metric by adding host tags?

**Comment by spencergilbert** [comment] 2022-10-05 16:37
Was definitely going to suggest testing against the `proxy` option. I'm looking to make some time this week (ideally today) to go through the Agent code and see if I can find the cause there.

**Comment by jszwedko** [comment] 2022-10-05 17:09
I'm still not convinced that the Agent does send that tag with each metric. Using a proxy or tcpdump to capture requests sent directly to Datadog, when not setting `DD_VECTOR_METRICS_ENABLED`, would help prove that. My hunch is that this is a host tag associated by Datadog during metrics ingestion. I'd start with validating that before poking around the Datadog Agent too much.

**Comment by andrewegel** [comment] 2022-10-05 17:38
Update here -

So I couldn't use the PROXY as noted here [1]:

```
Note: When setting up an HTTP proxy for https requests, the actual communication between the Agent and Datadog is encrypted end-to-end with TLS and cannot be decrypted by the proxy. The only unencrypted communication is the HTTP CONNECT request that’s made between the Agent and the proxy to establish the initial TCP connection between the Agent and Datadog. As such, when using a proxy for https requests, there is no need to use an HTTPS proxy in order to have encrypted communication between the Agent and Datadog.
```

As all I saw was CONNECT requests and from the agent's perspective the payload was encrypted:

```
2022/10/05 17:20:20 Request: &{CONNECT //api.datadoghq.com:443 HTTP/1.1 1 1 map[User-Agent:[Go-http-client/1.1]] <nil> <nil> 0 [] false api.datadoghq.com:443 map[] map[] <nil> map[] 127.0.0.1:43246 api.datadoghq.com:443 <nil> <nil> <nil> 0xc0000ae3c0}
```

So I couldn't inspect things that way. Instead I overrode `DD_URL` to point to my proxy that would then forward things onto DataDog's systems. Once I did that, my tiny proxy could inspect the metrics payloads that the DataDog agent was sending. What I found was the tag was being sent on the metric:

```
{
		"host": "<aws-instance-id>",
		"interval": 0,
		"metric": "kubernetes.containers.running",
		"points": [
			[
				1664991065,
				2
			]
		],
		"source_type_name": "System",
		"tags": [
			"docker_image:602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.8.4-eksbuild.1",
			"image_id:docker-pullable://602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns@sha256:fcb60ebdb0d8ec23abe46c65d0f650d9e2bf2f803fac004ceb1f0bf348db0fd0",
			"image_name:602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns",
			"image_tag:v1.8.4-eksbuild.1",
			"kube_container_name:coredns",
			"kube_deployment:coredns",
			"kube_namespace:kube-system",
			"kube_ownerref_kind:replicaset",
			"kube_priority_class:system-cluster-critical",
			"kube_qos:Burstable",
			"kube_replica_set:coredns-85d5b4454c",
			"kube_service:kube-dns",                                              // HERE IT IS
			"pod_phase:running",
			"short_image:coredns"
		],
		"type": "gauge"
	},
```

So to me this says there is a bug in the DataDog agent when `DD_VECTOR_METRICS_ENABLED` is set / configured.

[1] https://docs.datadoghq.com/agent/proxy/?tab=agentv6v7

**Comment by jszwedko** [comment] 2022-10-05 17:49
Thank you! That is very curious.

**Comment by andrewegel** [comment] 2022-10-05 17:50
Doing one more round of verification with `DD_VECTOR_METRICS_URL` setting (not overriding DD_URL) to confirm something.

**Comment by andrewegel** [comment] 2022-10-05 18:01
Which is part of this behavior difference I saw, that the `kube_service:` tag was missing only on "some" pods - Those "some pods" being some proprietary workloads that seemed to be Java based. I'll have to extend my experiment to another environment and I'll report back.

**Comment by andrewegel** [comment] 2022-10-05 19:35
OK, so this is interesting - With `DD_VECTOR_METRICS_ENABLED` using a Proxy / Relay (not vector) this is the payload that was intercepted:

```
        {
                "host": “<instance-id>”,
                "interval": 0,
                "metric": "kubernetes.containers.running",
                "points": [
                        [
                                1664997945,
                                1
                        ]
                ],
                "source_type_name": "System",
                "tags": [
                        "clusterid:<redacted>”,
                        "docker_image:<redact>.dkr.ecr.us-west-2.amazonaws.com/<redact>”,
                        "image_id:docker-pullable://<redact>.dkr.ecr.us-west-2.amazonaws.com/<redact>,
                        "image_name:<redact>.dkr.ecr.us-west-2.amazonaws.com/<redact>”,
                        "image_tag:<redacted>",
                        "kube_container_name:<redacted-service-name-that-disappears>”,
                        "kube_namespace:<redacted-just-the-k8-namespace>”,
                        "kube_ownerref_kind:statefulset",
                        "kube_qos:Burstable",
                        "kube_service:<redact>",
                        "kube_service:<redact>-0-internal",
                        "kube_service:<redact>-discovery",
                        "kube_stateful_set:<redact>",
                        "persistentvolumeclaim:data0-<redact>-0",
                        "pod-name:<redact>-0",
                        "pod_phase:running",
                        "short_image:<redact>"
                ],
                "type": "gauge"
        },
```

Specifically its interesting that datadog agent is senting multiple values for this `kube_service` tag:

```
                        "kube_service:<redact>",
                        "kube_service:<redact>-0-internal",
                        "kube_service:<redact>-discovery",
```

End Result: things are working as expected. I'm seeing this metric & tag coming in still - this is what DataDog shows:

`kube_service:<redact>,kube_service:<redact>-0-internal,kube_service:<redact>-discovery`

**Comment by jszwedko** [comment] 2022-10-05 19:48
Aha, interesting. Notably Vector's metric model doesn't allow for duplicate tags. I think, if you were to pass that metric through Vector, you'd only end up with one of those values for `kube_service`.

**Comment by spencergilbert** [comment] 2022-10-05 19:49
We're going to have to come up with a way to handle this because repeated tags are very common in DD metrics.

**Comment by spencergilbert** [comment] 2022-10-05 19:55
> I created #14742 to track that. Given this is the first time it has come up, I'm not sure how common it is, but it's definitely something we should improve.

I know it's come up internally before, and frankly I'm surprised that it hasn't come up as an issue in the past.

**Comment by jszwedko** [comment] 2022-10-05 19:57
Yeah, that's fair. I just hadn't seen it come up before which is a bit surprising given the potential impact.

**Comment by andrewegel** [comment] 2022-10-05 19:59
> ... frankly I'm surprised that it hasn't come up as an issue in the past.

I often come across this scenario (in general, not specific to DataDog->Vector & tags) myself in my day-to-days so you're not alone here.

Thanks for the assistance @jszwedko & @spencergilbert - I'll defer to how you folks like to track your work (eg: Close this as dupe to #14742 or keep it open till a PR is merged) - I'll watch these issues either way.

**Comment by andrewegel** [comment] 2022-10-05 20:08
Final tidbit - I checked back on my graphs, indeed there is a `kube_service:<redact>-discovery` tag, but not any `kube_service:<redact>-0-internal` or `kube_service:<redact>` tags, so it looks like the "last" value is used, which aligns with the code here:

https://github.com/vectordotdev/vector/blob/bd0cab24cfc25aa19d499b7b703f9d2d7514f3f5/src/sources/datadog_agent/metrics.rs#L401-L409

**Comment by jszwedko** [comment] 2022-10-07 18:35
Closing in-lieu of https://github.com/vectordotdev/vector/issues/14742

**Closed by jszwedko** 2022-10-07 18:35 UTC
Labels: transform: filter, domain: metrics, domain: filtering
