### ISSUE TITLE
Multiple Kafka source only consumes first source

### ISSUE THREAD

**Issue by jpds** [vectordotdev/vector#21329] opened 2024-09-20 23:17 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have a Vector instance which is configured with different topics for the same Kafka servers/group ID.

With `LOG="vector=info,rdkafka=trace"` I can see that Vector "rebalances" the three topics and then proceeds to only fetch the first configured topic.

### Configuration

```text
[sources.kafka_topic_1]
type = "kafka"
bootstrap_servers = "bootstrap1:9092,bootstrap2:9092"
group_id = "vector"
topic = [ "foo" ]

decoding.codec = "arvo"
decoding.arvo.schema = "...."

[sources.kafka_topic_2]
type = "kafka"
bootstrap_servers = "bootstrap1:9092,bootstrap2:9092"
group_id = "vector"
topic = [ "bar" ]

decoding.codec = "arvo"
decoding.arvo.schema = "...."

[sources.kafka_topic_3]
type = "kafka"
bootstrap_servers = "bootstrap1:9092,bootstrap2:9092"
group_id = "vector"
topic = [ "topic3" ]

decoding.codec = "json"

[sinks.vector]
#...
inputs = [ "kafka_topic_1", "kafka_topic_2", "kafka_topic_3" ]
```

### Version

0.41.0

**Comment by jszwedko** [comment] 2024-10-09 23:20
Hi @jpds !

I'm having trouble reproducing this. I created a local broker with three topics and the config:

```toml
[sources.kafka_topic_1]
type = "kafka"
bootstrap_servers = "localhost:9092"
group_id = "vector"
topics  = [ "test-topic-0" ]

decoding.codec = "bytes"

[sources.kafka_topic_2]
type = "kafka"
bootstrap_servers = "localhost:9092"
group_id = "vector"
topics  = [ "test-topic-1" ]

decoding.codec = "bytes"

[sources.kafka_topic_3]
type = "kafka"
bootstrap_servers = "localhost:9092"
group_id = "vector"
topics = [ "test-topic-2" ]

decoding.codec = "bytes"

[sinks.console]
type = "console"
encoding.codec = "json"
inputs = [ "kafka_topic_1", "kafka_topic_2", "kafka_topic_3" ]
```

And Vector read from all three topics when I published messages to each of them.

Is there any chance you could come up with a runnable MRE for us to reproduce this?

**Comment by jszwedko** [comment] 2024-10-23 17:40
Closing since I haven't been able to reproduce this, but please feel free to reopen with a more complete reproduction case so that we can dig into this.

**Closed by jszwedko** 2024-10-23 17:40 UTC
Labels: type: bug, source: kafka

**Comment by jpds** [comment] 2024-10-24 09:21
I suspect this has something to do with the Avro parsing code - when I shutdown Vector; I see it very quickly iterate through the other topics after the first one.

I have not had any time to look into this in more detail, and in the meantime - we've migrated from Vector to ClickHouse for the schema registry support (#19546).
