### ISSUE TITLE
Vector does not detect AWS credential file changes

### ISSUE THREAD

**Issue by wmyre** [vectordotdev/vector#19313] opened 2023-12-05 16:25 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Whenever credentials get updated in a credentials file that Vector references in `auth.credentials_file` for an AWS S3 sink, Vector does not detect the changes. This causes Vector to continue using the same credentials it used on initial load instead of refreshing its credentials cache with the new credentials.

### Configuration

```text
[sinks.aws_s3]
type = "aws_s3"
region = "${AWS_S3_BUCKET_REGION}"
auth.credentials_file = "${AWS_SHARED_CREDENTIALS_FILE:?credentials file must be defined!}"
healthcheck.enabled = true
```
```


### Version

0.34.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment] 2023-12-05 18:39
Hi @wmyre !

I think this is a duplicate of https://github.com/vectordotdev/vector/issues/18591 . I'll close this out, but let me know if you disagree.

I'd recommend using https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html which does handle extrenal credential reload when the credentials expire.

**Closed by jszwedko** 2023-12-05 18:39 UTC
Labels: type: bug

**Comment by wmyre** [comment] 2023-12-05 18:44
That is the same behavior we are experiencing, yes this can be closed, thanks!
