### ISSUE TITLE
Log error=Missing environment variable in config for comment in config

### ISSUE THREAD

**Issue by alexpts** [vectordotdev/vector#20679] opened 2024-06-15 17:11 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

On start I have ` ERROR vector::cli: Configuration error. error=Missing environment variable in config. name = "ES_HOST"`

I don't expect variables to be checked in configuration comments.

### Configuration

```text
sinks:
  es:
    inputs: ["json_parser"]
    type: "elasticsearch"
    mode: "bulk"
    acknowledgements:
      enabled: true
    bulk:
      index: "vector-{{ _vector._es_index }}-%Y.%m.%d" # https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html#specifiers
      #index = "{{ _es_index }}"
    #endpoints = "${ES_HOST}"  # указывается с протоколом и портом
    endpoints: ["http://elasticsearch:9200"]
    compression: "gzip"
```

### Version

version="0.38.0" arch="aarch64" revision="ea0ec6f 2024-05-07 14:34:39.794027186"

### Additional Context

macos 14.5 + docker image timberio/vector:0.38.X-alpine

**Comment by jszwedko** [comment] 2024-06-17 13:57
Thanks for filing @alexpts ! I think this is a duplicate of https://github.com/vectordotdev/vector/issues/797 so I'll close this one, but let me know if you disagree (and feel free to follow along on that issue).

**Closed by jszwedko** 2024-06-17 13:57 UTC
Labels: type: bug
