### ISSUE TITLE
Batching on Disk

### ISSUE THREAD

**Issue by scMarkus** [vectordotdev/vector#17985] opened 2023-07-16 20:12 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I started using a Vector aggregator architecture with the intent to batch some amount of data into fewer files then writing from the agents directly to s3 (fewer files and therefore faster s3 listing, less space used when gziped). Vector does support this use case per se but my aggregator consumes quite a bit of memory at times since the data seams to be batched there. Furthermore I am not feeling confident with longer batching periods (for collecting more data before writing) when the data is only stored in memory. 

### Proposal

Extending the batching to use some persistent storage similar to the `buffer.type: disk`. Ideally this would involve some technique to use NFS mounted storage as well since this would be a fast and easy way to access larger amounts of storage when using some Kubernetes like cloud setups with ephemeral contains.

Similarity (if viable) maybe some batch config could be blocking so that the buffer will be used instead? I would be interested in some behavior like that sine apparently there is effort going on to use S3 as alternative buffer which I think is interesting.

### References

#3829
#9923

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

**Comment by spencergilbert** [comment] 2023-07-17 13:01
Some overlap/duplicate of https://github.com/vectordotdev/vector/issues/3829

**Comment by jszwedko** [comment] 2023-07-17 14:42
Thanks @scMarkus !

I think this issue is actually covered by https://github.com/vectordotdev/vector/issues/10392 . I'll close this one and reference it there, but let me know if you disagree!

As you noted https://github.com/vectordotdev/vector/issues/3829 is related.

**Closed by jszwedko** 2023-07-17 14:42 UTC
Labels: type: feature

**Comment by scMarkus** [comment] 2023-07-17 20:48
Thx for the quick response.

@spencergilbert agreed that there is some overlap/duplicate.
@jszwedko thx for referencing in #10392. Yes, my goal would be archived by the other issue. Although the proposed solution is narrower then what is suggested here.

I will watch #10281 for the ongoing durability development  :)
