### ISSUE TITLE
Performance degradation with VRL

### ISSUE THREAD

**Issue by valerypetrov** [vectordotdev/vector#9967] opened 2021-11-09 14:28 UTC
### Vector Version

```
vector --version
vector 0.17.3 (x86_64-unknown-linux-gnu d72c6e7 2021-10-21)
```

### Vector Configuration File

Here is an example of the problem part of the config file

```
  if !(match(.component_type, r'^[\w]{3,}$') && match(.log_type, r'^[\w.-]{3,}$')){
       log(.component_type, level: "error", rate_limit_secs: 60)
       log(.log_type, level: "error", rate_limit_secs: 60)
       del(.message)
  }
```

With this one, it's working fine
```
[transforms.regex_component]

  type = "regex_parser"
  inputs = ["json_parser_app"]
  drop_failed = true
  drop_field = false
  field = "component_type"
  patterns = ['^[\w]{3,}$']

[transforms.regex_log_type]

  type = "regex_parser"
  inputs = ["regex_component"]
  drop_failed = true
  drop_field = false
  field = "log_type"
  patterns =  ['^[\w.-]{3,}$']
```

Performance metrics for VRL:
<img width="1685" alt="Screenshot 2021-11-09 at 17 21 47" src="https://user-images.githubusercontent.com/33148246/140942141-de75e9ad-feb6-400e-bd07-eb7eed8b36f3.png">

Performance metrics for transform:
<img width="1057" alt="Screenshot 2021-11-09 at 17 22 18" src="https://user-images.githubusercontent.com/33148246/140942220-38fa5aa6-0e9c-48ae-be94-5f4841390c59.png">

**Comment by jszwedko** [comment] 2021-11-09 15:52
Hey @valerypetrov !

Thanks for this report! Would you be able to share:

* Your `remap` transform configuration
* Some example input lines (both that do and do not match the regexes)
* A rough idea of the proportion of events that would or would not match the regex?

We do expect `remap` to be slightly slower than the native `regex_parser` transform, but not at that magnitude. We are are also working on closing that gap by making VRL more performant.

**Comment by valerypetrov** [comment] 2021-11-10 09:31
Hey. Sure, remap configuration:
```
[sources.internal_metrics_app]
  type = "internal_metrics"

[sources.kafka_source]
  type = "kafka"
  bootstrap_servers = "brokers"
  group_id = "qp11grrr-consumer-group"
  topics = ["app"]
  auto_offset_reset = "earliest"

[transforms.json_parser_app]
  type = "json_parser"
  inputs = ["kafka_source"]
  drop_field = true
  drop_invalid = true
  field = "message"

[transforms.remap_app]
  type = "remap"
  inputs = ["json_parser_app"]
  source = '''
  .component_type, err = downcase(.component_type)
  .log_type, err = downcase(.log_type)
  if !(match(.component_type, r'^[\w]{3,}$') && match(.log_type, r'^[\w.-]{3,}$')){
       log(.component_type, level: "error", rate_limit_secs: 60)
       log(.log_type, level: "error", rate_limit_secs: 60)
       del(.message)
  }

  if (.component_type == "zzz" || .component_type == "xxx" || .component_type == "yyy" || .component_type == "ccc" || .component_type == "vvv" || .component_type == "bbb" || .component_type == "nnn" || .component_type == "mmm" ){
      .vector_routing_rule = "rule_c01"
   } else if (.component_type == "qqq" || .component_type == "www" || .component_type == "eee" || .component_type == "rrr" || .component_type == "ttt"){
      .vector_routing_rule = "rule_c02"
   } else  {
      .vector_routing_rule = "rule_c03"
   }

  if (exists(.message) && length(.message) > 30000){
   .long_field = "long_field_warn"
   }

  if (exists(.message) && length(.message) > 80000){
   .long_field = "long_field_crit"
   }

  if (exists(.message) && length(.message) > 100000){
   .long_field = "long_field_truncated"
   .message,err = truncate(.message, limit:  100000)
   }
  if (exists(.stack_trace) && length(.stack_trace) > 30000){
   .long_field =  "long_field_warn"
   }

  if (exists(.stack_trace) && length(.stack_trace) > 80000){
   .long_field = "long_field_crit"
   }

  if ( exists(.stack_trace) && length(.stack_trace) > 100000){
   .long_field = "long_field_truncated"
   .stack_trace, err = truncate(.stack_trace, limit:  100000)
   }

  .index_pattern = .component_type + "-" + .log_type
  .consumer = "${HOSTNAME}"
  .consumer_time = now()

'''

other processing rules
````````````````````````
```

Here is the example of a log that matches regex:
```
{"app_name":"billinqwdlkmqr","component_type":"ACM","duration_ms":1,"env_name":"SDM-KJSN-ZMK","env_unit":"01","host":"19238129390123","hostname":"qsdnqo12983dskl","level":"DEBUG","level_value":10000,"location":"128iods","log_format":"json","log_type":"main","logger_name":"sdkfmiosd.wqoijqowie.wjkfowepkdpo.qwpekqwpe","marathonappid":"wiodniowd0123isdij1239jsdolqw","message":"statement:[/* AccountDAO.findPackageLicenses */ woeidjo 1 i12eoidooi o12n onondokcsmml kl1 mlkmlkadml akm12 kmwlsmd bfhjadskn inlkdvnldnfvhfnk 1iu njkndksdnfi1 bjkvjkdjbfjkfnksjdbfiuwnvjnfdiublfdjs] took 1 millis","request_id":"IGL:b5ab557b-7451-4e18-ab66-a9b5e24e637a-14626-1946","request_token":"OIJO:dkfnodfoweihweifdiwefhwe","source_type":"socket","thread_name":"dw-15188 - GET /restapi/account-manager/v1.0/account/opfewkpkwofpew/package/odmwop/pwodpweo","timestamp":"2020-06-02T09:54:24.543+00:00","version":"1"}
```

Don't match the regex
```
{"app_name":"billinqwdlkmqr","component_type":"zxcvbnm","duration_ms":1,"env_name":"SDM-KJSN-ZMK","env_unit":"01","host":"19238129390123","hostname":"qsdnqo12983dskl","level":"DEBUG","level_value":10000,"location":"128iods","log_format":"json","log_type":"main","logger_name":"sdkfmiosd.wqoijqowie.wjkfowepkdpo.qwpekqwpe","marathonappid":"wiodniowd0123isdij1239jsdolqw","message":"statement:[/* AccountDAO.findPackageLicenses */ woeidjo 1 i12eoidooi o12n onondokcsmml kl1 mlkmlkadml akm12 kmwlsmd bfhjadskn inlkdvnldnfvhfnk 1iu njkndksdnfi1 bjkvjkdjbfjkfnksjdbfiuwnvjnfdiublfdjs] took 1 millis","request_id":"IGL:b5ab557b-7451-4e18-ab66-a9b5e24e637a-14626-1946","request_token":"OIJO:dkfnodfoweihweifdiwefhwe","source_type":"socket","thread_name":"dw-15188 - GET /restapi/account-manager/v1.0/account/opfewkpkwofpew/package/odmwop/pwodpweo","timestamp":"2020-06-02T09:54:24.543+00:00","version":"1"}
```

> A rough idea of the proportion of events that would or would not match the regex?
Around 1-5% of overall data

**Comment by back2root** [comment] 2021-11-12 12:38
Hi there!

@hhromic already also reported and benchmarked performance issues with RegEx parsing, when using _replace_ in VRL.
Have a look for his comment including a benchmark showing a drop from 160k EPS => ~2k EPS: https://github.com/vectordotdev/vector/issues/6882#issuecomment-938957766

I faced similar issues with comparable performance drops, that made _match_/_replace_ within vector useless for me.

Without being used to rust and being able to have an look into the code right now: It feels like if VRL is maybe compiling the RegEx for every event. But it should compile the regex once and then apply in to each event.
(Just a guess, but that would be the most obvious reason for me for such an performance decrease, though using rust build in RegEx crate.

**Comment by KonPaw** [comment] 2021-11-19 11:03
I've did an upgrade yesterday of our vector setup. We had a 0.10.x version (so no remap etc.) and I've upgraded to the newest version.
I like that VRL looks much cleaner however I use a lot of regex in our system and when I've moved from old functions (swimlanes, check_fields) performance dropped by a lot. What's interesting is that CPU also went a little down.

We use syslog -> vector -> clickhouse. It's mostly http traffic, and in peak time it got to about 17k/s clickhouse input (1M/minute). 

I didn't convert all of the code to remap, i did it part by part, so I could see the impact on clickhouse input and debug any possible issues. One change decreased clickhouse input from 1M/minute to about 750K/minute. It's a decrease of 1/4 of performance just by one regex. That was the time I've decided to rollback all the changes. 

Change from:
```
[transforms.cdn_parser]
  inputs = ["cdn_dvr_divide.varnishncsa"]
  type = "regex_parser"
  drop_field = true
  drop_failed = false
  field = "message"
  patterns = ["^(?P<timestamp>[^\\|]+)\\|(?P<method>[^\\|]+)\\|(?P<log_source>[^\\|]+)\\|(?P<user_agent>[^\\|]+)\\|(?P<request>[^\\|]+)\\|(?P<request_source_ip>[^\\|]+)\\|(?P<test1>[^\\|]+)\\|(?P<hit_or_miss>[^\\|]+)\\|(?P<test2>[^\\|]+)\\|(?P<redirect_target>[^\\|]+)\\|(?P<http_answer>[^\\|]+)\\|(?P<file_type>[^\\|]+)\\|(?P<test4>[^\\|]+)$"]

 [transforms.cdn_parser.types]
  timestamp = "string"
  method = "string"
  log_source = "string"
  user_agent = "string"
  request = "string"
  request_source_ip = "string"
  test1 = "string"
  hit_or_miss = "string"
  test2 = "string"
  http_answer = "int"
  file_type = "string"
  test4 = "string"
```

To:

```
[transforms.cdn_parser]
  type= "remap"
  inputs= ["cdn_dvr_divide.varnishncsa"]
  source = '''
  ., err |= parse_regex(.message, r'^(?P<timestamp>[^\|]+)\|(?P<method>[^\|]+)\|(?P<log_source>[^\|]+)\|(?P<user_agent>[^\|]+)\|(?P<request>[^\|]+)\|(?P<request_source_ip>[^\|]+)\|(?P<test1>[^\|]+)\|(?P<hit_or_miss>[^\|]+)\|(?P<test2>[^\|]+)\|(?P<redirect_target>[^\|]+)\|(?P<http_answer>[^\|]+)\|(?P<file_type>[^\|]+)\|(?P<test4>[^\|]+)$')

  .http_answer = to_int!(.http_answer)
  '''
```


CPU Load according by zabbix went from 6-8 before remap to 3,5-4,5.
Just changing config to one before the changes fixed the issue. Config with remap but version 0.12 instead of 0.17 still has the same regex performance issue.
I may change those transforms to not regex ones (split in above case could probably work fine) however it seems there is quite a problem with regex which was introduced in VRL.

**Comment by jszwedko** [comment] 2022-12-23 21:56
At this point we've removed the `regex_parser` transform so the VRL regex parsing performance should be considered the new baseline (to which we can make improvements). There have been improvements to VRL performance since 0.17.0 though, so it's possible the regression vs. `regex_parser` has decreased.

**Closed by jszwedko** 2022-12-23 21:56 UTC
Labels: domain: performance, domain: vrl, vrl: stdlib
