### ISSUE TITLE
ec2_metadata sink: locks up Vector if ec2 metadata endpoint not reachable

### ISSUE THREAD

**Issue by akasprzok** [vectordotdev/vector#12916] opened 2022-05-31 19:32 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using the ec2 metadata transform on an ASG where metadata isn't accessible, or the hop limit isn't set to 2, vector will lock up.

I suggest it should emit an error message indicating it is unable to reach the endpoint at the very least.
Having a default _value for ec2_metadata fields when the endpoint is unreachable would also be great, in addition to the log.

### Configuration

```text
[transforms.ec2_metadata]
  type = "aws_ec2_metadata"
  inputs = [ "loki_structured_logs"]
  fields = [ "instance-id", "vpc-id", "ami-id"]
  refresh_interval_secs = 300
```

### Version

0.21.x

### Debug Output

```text
Can add debug output later - here's INFO:


docker logs a3f -f
2022-05-31T18:47:07.552127Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-05-31T18:47:07.552241Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
2022-05-31T18:47:07.556645Z  INFO vector::sources::docker_logs: Capturing logs from now on. now=2022-05-31T18:47:07.556576651+00:00
2022-05-31T18:47:07.557318Z  INFO vector::sources::docker_logs: Listening to docker log events.
2022-05-31T18:47:07.557483Z  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
2022-05-31T18:47:07.557492Z  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
```

Above I expected output informing me of my sink/source/transform setup, instead vector locks up and becomes unhealthy to EC2.
```


### Example Data

_No response_

### Additional Context

Running in ECS.

### References

_No response_

**Comment by jszwedko** [comment] 2022-05-31 19:36
Thanks for the report @akasprzok ! I think this is a duplicate of https://github.com/vectordotdev/vector/issues/9749 so I'll close in-lieu of that one but feel free to leave any additional thoughts there.

**Closed by jszwedko** 2022-05-31 19:36 UTC
Labels: type: bug, transform: aws_ec2_metadata
