### ISSUE TITLE
Grafana Loki Sink needs to support log metadata

### ISSUE THREAD

**Issue by miadabrin** [vectordotdev/vector#20885] opened 2024-07-18 15:56 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

currently Loki supports metadata on the logline https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/ but the loki sink doesn't support it. This makes a lot of challenges for finding logs in loki properly

### Attempted Solutions

the http sink also doesn't work in this case since it doesn't allow sending an array for the http endpoint (instead of a json object)

### Proposal

add support for adding metadata to log lines

**Comment by jszwedko** [comment] 2024-07-18 16:11
I think this is a duplicate of https://github.com/vectordotdev/vector/issues/18876 but let me know if I'm wrong!

**Closed by jszwedko** 2024-07-18 16:11 UTC
Labels: type: feature
