### ISSUE TITLE
aws_kinesis_firehose sink doesn't use batches properly

### ISSUE THREAD

**Issue by gromnsk** [vectordotdev/vector#18939] opened 2023-10-25 19:33 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

to reduce costs on kinesis firehose all events should be written in batches. As I can see now there is no batches in this sink because when I switch some logs from another solution on vector `incoming put requests` metric in CloudWatch show significant increase(up to 1000x).
Same problem with big amount of put requests from vector can be cause of throttling on AWS firehose side because of limits on streams

### Proposal

If I understood right aws_kinesis_firehose sink uses `PutRecords` endpoint instead of `PutRecordsBatch`, it would be great to switch to PutRecordsBatch endpoint to avoid problems with high cost of firehose and limitations problem

**Comment by neuronull** [comment] 2023-10-25 22:12
This looks like it could potentially be a duplicate of https://github.com/vectordotdev/vector/issues/1407

**Comment by gromnsk** [comment] 2023-10-26 18:34
ah, sorry, yes, you are right, but there is almost 4 years and problem still exists

**Closed** 2023-10-26 18:35 UTC
Labels: type: feature
