### ISSUE TITLE
Ability to fetch Prometheus metrics using the HTTP API or remote_read protocol

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2304] opened 2020-04-12 12:45 UTC
From our chat:

> the real "prometheus source" thing I miss: ability to fetch metric from prometheus tsdb (or compatible like victoriametrics, thanos, ...) using http api or "remote_read" protocol ... in this case it's possible to make amazing "pull-push conversion" stuff like sending metrics from prometheus to statuspage.io (prometheus->transforms->http) or more complex pipelines (had to create additional services to implement it)

If I understand this correctly, this basically tailing data from an actual Prometheus database. Not only would this be good for the use case listed above, but also for backup.

Before we begin work we need to collect more details and firm up the requirements.

/cc @afoninsky

**Comment by jszwedko** [comment] 2022-08-02 21:50
Duplicate of https://github.com/vectordotdev/vector/issues/4162

**Closed by jszwedko** 2022-08-02 21:50 UTC
Labels: type: enhancement, needs: approval, needs: requirements, meta: feedback, have: nice, domain: metrics, source: prometheus_scrape
