### ISSUE TITLE
log_to_metric documentation rendering error

### ISSUE THREAD

**Issue by mjperrone** [vectordotdev/vector#14623] opened 2022-09-28 22:09 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://vector.dev/docs/reference/configuration/transforms/log_to_metric/

The common configuration listed at the top includes the `metrics.field` which is required and not mentioned anywhere on the page.

It looks like the metrics array dropdown is broken as well, maybe it's a rendering bug in the docs.
<img width="712" alt="Screen Shot 2022-09-28 at 15 09 46" src="https://user-images.githubusercontent.com/3848371/192897709-ef19f6cd-4cde-47b1-b931-1737be6f8727.png">

### Version

irrelevant

**Comment by spencergilbert** [comment] 2022-09-29 00:20
Definitely looks to be a rendering error - the raw documentation has `metrics.field` as a required option:

```cue
field: {
	description: "The log field to use as the metric."
	required:    true
	type: string: {
		examples: ["duration", "parent.child"]
	}
}
```

**Comment by mjperrone** [comment] 2022-10-03 17:19
Looks like this is broken in [v15 docs](https://v0-15.vector.dev/docs/reference/configuration/transforms/log_to_metric/#metrics) and also in [master](https://master.vector.dev/docs/reference/configuration/transforms/log_to_metric/#metrics).

**Comment by jszwedko** [comment] 2022-10-04 17:26
Duplicate of https://github.com/vectordotdev/vector/issues/9387

**Closed by jszwedko** 2022-10-04 17:26 UTC
Labels: type: bug, website: template
