### ISSUE TITLE
Bytes not reported from `vector top`

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#11987] opened 2022-03-25 16:42 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/11903873/160162969-73053fd5-1769-4291-b683-ea383aa08088.png">

Events In/Out are present for all components, but Bytes are only available for the `console` sink

### Configuration

```text
data_dir: /vector-data-dir
  api:
    enabled: true
    address: 0.0.0.0:8686
    playground: false
  sources:
    datadog_agent:
      address: 0.0.0.0:8282
      type: datadog_agent
      multiple_outputs: true
    internal_logs:
      type: internal_logs
    internal_metrics:
      type: internal_metrics
  transforms:
    remap_logs:
      type: remap
      inputs:
        - datadog_agent.logs
        - internal_logs
      source: |
        # Add ddtags for internal_logs
        if .source_type == "internal_logs" {
          .ddtags = "service:vector"
        }

        # Parse the received .ddtags field so we can more easily access the contained tags
        .ddtags = parse_key_value!(.ddtags, key_value_delimiter: ":", field_delimiter: ",")
        .ddtags.sender = "vector"
        .ddtags.vector_aggregator = get_hostname!()
        # Re-encode Datadog tags as a string for the `datadog_logs` sink
        .ddtags = encode_key_value!(.ddtags, key_value_delimiter: ":", field_delimiter: ",")

        # Datadog Agents pass a "status" field that is stripped when ingested
        del(.status)
  sinks:
    datadog_logs:
      type: datadog_logs
      inputs:
        - remap_logs
        - internal_logs
      default_api_key: ${DATADOG_API_KEY}
      compression: gzip
    datadog_metrics:
      type: datadog_metrics
      inputs:
        - datadog_agent.metrics
        - internal_metrics
      default_api_key: ${DATADOG_API_KEY}
    stdout:
      type: console
      inputs:
        - remap_logs
      encoding:
        codec: json
```

### Version

`version="0.21.0" arch="aarch64" build_id="b3c1977 2022-03-24"` and `0.20.0`

### Additional Context

Running in Kubernetes while working on https://github.com/vectordotdev/helm-charts/pull/176 - could almost certainly get a smaller reproduction config

**Comment by 001wwang** [comment] 2022-03-25 17:05
To add some context here for posterity, this is because the `Bytes` column of `vector top` currently reports each component's `processed_bytes_total` metric. Since `top`'s initial implementation, new component instrumentation standards have been made, and `processed_bytes_total` is being deprecated, so not every component will report (or ever reported) `processed_bytes_total`. Hence, the potentially confusing `N/A`s. We'd like to instead use the standard component metrics here (e.g. `component_*_bytes_total`).

To that end, closing as a duplicate of https://github.com/vectordotdev/vector/issues/11071

**Closed by 001wwang** 2022-03-25 17:05 UTC
Labels: domain: observability, domain: api
