### ISSUE TITLE
commented out env var substitutions can bork vector if the var is not set

### ISSUE THREAD

**Issue by jdef** [vectordotdev/vector#15927] opened 2023-01-12 15:02 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

vector refuses to start when commented-out environment variable "required" refs are present, and said variables are not defined. this is unexpected since the required reference appears on a commented line.

### Configuration

```text
consider a configuration:

[transforms.foo]
type="remap"
inputs=[...]
# timezone="${TZ:?timezone must be set}"
source='''
...
'''
```
```


### Version

0.27.0

### Debug Output

```text
sorry, air-gapped cluster. no copy/paste
```

### Additional Context

tested on 0.25.1 and nightly build from 2023-01-12 - same problem on both

**Comment by jszwedko** [comment] 2023-01-12 15:49
Thanks for this report! I think this is a duplicate of https://github.com/vectordotdev/vector/issues/797

**Closed by jszwedko** 2023-01-12 15:49 UTC
Labels: type: bug
