### ISSUE TITLE
Reader encountered unrecoverable error: PartialWrite

### ISSUE THREAD

**Issue by chidambaranathan-karthikeyan** [vectordotdev/vector#15388] opened 2022-11-29 17:51 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

'vector-worker' panicked at 'reader encountered unrecoverable error: PartialWrite', /project/lib/vector-buffers/src/topology/channel/receiver.rs:64:18

### Configuration

```text
[sinks.XXXXX]
 type = "elasticsearch"
 inputs = ["add_fields"]
 doc_type = "_doc"
 healthcheck = true
 endpoint = "XXXXXX"
 id_key = "id"
 bulk.index = "XXXXX"
 bulk.action = "create"
 compression = "gzip"
 auth.strategy = "XXXX"
 auth.password = "XXXXX"
 auth.user = "XXXXXXX"
 # Batch
 batch.max_size = 10490000
 batch.timeout_secs = 1

 # Buffer
 buffer.type = "disk"
 buffer.max_size = 268435488
 buffer.when_full = "drop_newest"

 # Request
 request.rate_limit_duration_secs = 1
 request.rate_limit_num = 5
 request.retry_attempts = 3
 request.retry_initial_backoff_secs = 1
 request.retry_max_duration_secs = 10
 request.timeout_secs = 60

 # TLS
 tls.verify_certificate = false
 tls.verify_hostname = false
```

### Version

vector 0.22.3 (x86_64-unknown-linux-gnu)

### Debug Output

```text
Nov 29 17:27:42 <host-name> vector: thread 'vector-worker' panicked at 'reader encountered unrecoverable error: PartialWrite', /project/lib/vector-buffers/src/topology/channel/receiver.rs:64:18
Nov 29 17:27:42 <host-name> vector: stack backtrace:
Nov 29 17:27:42 <host-name> vector: 0:     0x557409ac24ac - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
Nov 29 17:27:42 <host-name> vector: 1:     0x557409ac24ac - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
Nov 29 17:27:42 <host-name> vector: 2:     0x557409ac24ac - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
Nov 29 17:27:42 <host-name> vector: 3:     0x557409ac24ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
Nov 29 17:27:42 <host-name> vector: 4:     0x557409b1e8bc - core::fmt::write::h513b07ca38f4fb1b
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
Nov 29 17:27:42 <host-name> vector: 5:     0x557409ab26f5 - std::io::Write::write_fmt::haf8c932b52111354
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
Nov 29 17:27:42 <host-name> vector: 6:     0x557409ac5550 - std::sys_common::backtrace::_print::h195c38364780a303
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
Nov 29 17:27:42 <host-name> vector: 7:     0x557409ac5550 - std::sys_common::backtrace::print::hc09dfdea923b6730
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
Nov 29 17:27:42 <host-name> vector: 8:     0x557409ac5550 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
Nov 29 17:27:42 <host-name> vector: 9:     0x557409ac5105 - std::panicking::default_hook::h60284635b0ad54a8
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
Nov 29 17:27:42 <host-name> vector: 10:     0x557409ac5d44 - std::panicking::rust_panic_with_hook::ha677a669fb275654
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
Nov 29 17:27:42 <host-name> vector: 11:     0x557409ac5820 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
Nov 29 17:27:42 <host-name> vector: 12:     0x557409ac2954 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
Nov 29 17:27:42 <host-name> vector: 13:     0x557409ac5789 - rust_begin_unwind
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
Nov 29 17:27:42 <host-name> vector: 14:     0x5574042508a1 - core::panicking::panic_fmt::h35f3a62252ba0fd2
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
Nov 29 17:27:42 <host-name> vector: 15:     0x557404250993 - core::result::unwrap_failed::hb53671404b9e33c2
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
Nov 29 17:27:42 <host-name> vector: 16:     0x557405aadc65 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0cc36c9848c07f0a
Nov 29 17:27:42 <host-name> vector: 17:     0x557405bd142c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h592998dd842a886c
Nov 29 17:27:42 <host-name> vector: 18:     0x557405e21d8d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf49e7d4ef5e9ab8b
Nov 29 17:27:42 <host-name> vector: 19:     0x557404281386 - <vector_buffers::topology::channel::receiver::BufferReceiverStream<T> as futures_core::stream::Stream>::poll_next::hb6c390fd4de8b6fb
Nov 29 17:27:42 <host-name> vector: 20:     0x557404e764f4 - <vector::utilization::Utilization<S> as futures_core::stream::Stream>::poll_next::h320fa6c86d52063c
Nov 29 17:27:42 <host-name> vector: 21:     0x557404eb5f62 - <futures_util::stream::stream::filter::Filter<St,Fut,F> as futures_core::stream::Stream>::poll_next::h33a21e26d0d2042a
Nov 29 17:27:42 <host-name> vector: 22:     0x557404abb632 - <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::ha2fd72b99f0934e0
Nov 29 17:27:42 <host-name> vector: 23:     0x557405875152 - <stream_cancel::combinator::TakeUntilIf<S,F> as futures_core::stream::Stream>::poll_next::hd1e9fb2ebb1f1a25
Nov 29 17:27:42 <host-name> vector: 24:     0x557405f962e7 - <futures_util::stream::stream::flatten::Flatten<St,<St as futures_core::stream::Stream>::Item> as futures_core::stream::Stream>::poll_next::he3d5fde5fff31395
Nov 29 17:27:42 <host-name> vector: 25:     0x5574063a5e89 - <futures_util::stream::stream::FlatMap<St,U,F> as futures_core::stream::Stream>::poll_next::hd754ac2c30fe9d12
Nov 29 17:27:42 <host-name> vector: 26:     0x557405771636 - <futures_util::stream::stream::scan::Scan<St,S,Fut,F> as futures_core::stream::Stream>::poll_next::h469801cd7d403322
Nov 29 17:27:42 <host-name> vector: 27:     0x557404ac7c58 - <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next::h1cae3a32c774d647
Nov 29 17:27:42 <host-name> vector: 28:     0x5574061006cd - <vector_core::stream::batcher::Batcher<S,C> as futures_core::stream::Stream>::poll_next::hc5af365739adf171
Nov 29 17:27:42 <host-name> vector: 29:     0x557404591941 - <vector_core::stream::concurrent_map::ConcurrentMap<St,T> as futures_core::stream::Stream>::poll_next::h38d3ab758e0681af
Nov 29 17:27:42 <host-name> vector: 30:     0x557404acc6a1 - <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next::hb16d53df5591b9b5
Nov 29 17:27:42 <host-name> vector: 31:     0x5574049c4d5b - <futures_util::stream::stream::ready_chunks::ReadyChunks<St> as futures_core::stream::Stream>::poll_next::ha7df7a82fedab91b
Nov 29 17:27:42 <host-name> vector: 32:     0x557404b85d52 - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h4e83da26e3ba4bf0
Nov 29 17:27:42 <host-name> vector: 33:     0x557405e9df32 - vector::sinks::elasticsearch::sink::ElasticsearchSink<S>::run_inner::{{closure}}::h7d87d76569874f6d
Nov 29 17:27:42 <host-name> vector: 34:     0x557405bac78c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4af6b4d5d244285f
Nov 29 17:27:42 <host-name> vector: 35:     0x557405dd337c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdf6bce5cd2723add
Nov 29 17:27:42 <host-name> vector: 36:     0x557405b0702c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1ea826c558989a9d
Nov 29 17:27:42 <host-name> vector: 37:     0x557405bf6d8f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h61f4ddd8e79c9a04
Nov 29 17:27:42 <host-name> vector: 38:     0x5574052b0fe5 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h259fc7b2a1d783d4
Nov 29 17:27:42 <host-name> vector: 39:     0x5574043d1b57 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h46b5d5cb27694c34
Nov 29 17:27:42 <host-name> vector: 40:     0x557406064ad8 - tokio::runtime::task::harness::Harness<T,S>::poll::h30f2fc9d2f754cac
Nov 29 17:27:42 <host-name> vector: 41:     0x55740965e500 - std::thread::local::LocalKey<T>::with::h3a67992e3291b394
Nov 29 17:27:42 <host-name> vector: 42:     0x5574096907c1 - tokio::runtime::thread_pool::worker::Context::run_task::hdef055e2346ff769
Nov 29 17:27:42 <host-name> vector: 43:     0x55740968f679 - tokio::runtime::thread_pool::worker::Context::run::h69579b54f2b93c8b
Nov 29 17:27:42 <host-name> vector: 44:     0x5574096687f5 - tokio::macros::scoped_tls::ScopedKey<T>::set::h934a915ea0c68d84
Nov 29 17:27:42 <host-name> vector: 45:     0x55740968f06c - tokio::runtime::thread_pool::worker::run::hf0fbd2a368b76462
Nov 29 17:27:42 <host-name> vector: 46:     0x557409697e6f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h7d6d9129dc6cac56
Nov 29 17:27:42 <host-name> vector: 47:     0x55740967ad9d - tokio::runtime::task::harness::Harness<T,S>::poll::h48272495361a7da0
Nov 29 17:27:42 <host-name> vector: 48:     0x55740966f605 - tokio::runtime::blocking::pool::Inner::run::h63d0ab6212c7c43d
Nov 29 17:27:42 <host-name> vector: 49:     0x55740965e28e - std::sys_common::backtrace::__rust_begin_short_backtrace::h05fd32e319beda24
Nov 29 17:27:42 <host-name> vector: 50:     0x55740965f3fa - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6f5450aa9e7ae143
Nov 29 17:27:42 <host-name> vector: 51:     0x557409ad15e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcbc6d2d80772be64
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9
Nov 29 17:27:42 <host-name> vector: 52:     0x557409ad15e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9bffa2ca65a1d6e6
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9
Nov 29 17:27:42 <host-name> vector: 53:     0x557409ad15e3 - std::sys::unix::thread::Thread::new::thread_start::ha678a8b0caec8f55
Nov 29 17:27:42 <host-name> vector: at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/thread.rs:106:17
Nov 29 17:27:42 <host-name> vector: 54:     0x7f6cfa3e3e25 - start_thread
Nov 29 17:27:42 <host-name> vector: 55:     0x7f6cf92c9bad - clone
Nov 29 17:27:42 <host-name> vector: 56:                0x0 - <unknown>
Nov 29 17:27:42 <host-name> vector: 2022-11-29T17:27:42.874769Z ERROR sink{component_kind="sink" component_id=XXXXX component_type=elasticsearch component_name=XXXX}: vector::topology: An error occurred that Vector couldn't handle.
Nov 29 17:27:42 <host-name> vector: 2022-11-29T17:27:42.875071Z  INFO vector: Vector has stopped.
```

### Additional Context

Right now, systemd settings

CPUQuota=10%
Environment=RUST_BACKTRACE=full
ExecStart=/usr/bin/vector
ExecReload=/bin/kill -HUP $MAINPID
MemoryLimit=1G
Restart=always
RestartSec=5000ms
RUST_BACKTRACE=1
StandardOutput=null
StandardError=syslog
SyslogIdentifier=vector

**Comment by jszwedko** [comment] 2022-11-29 19:27
Hi @chidambaranathan-karthikeyan !

I think this is a duplicate of https://github.com/vectordotdev/vector/issues/13178 which was fixed in v0.23.0. Could you try upgrading?

I'll close this, but feel free to re-open if you still see it after upgrading.

**Closed by jszwedko** 2022-11-29 19:27 UTC
Labels: type: bug
