### ISSUE TITLE
[source] Add Pulsar source

### ISSUE THREAD

**Issue by caibirdme** [vectordotdev/vector#12711] opened 2022-05-12 06:49 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We've replaced kafka with pulsar, so we need consume log from pulsar and remap log and send them into sinks.

### Attempted Solutions

Try to find pulsar source, transform and send to sinks, but pulsar source not found. There is only a pulsar sink

### Proposal

Add pulsar as a source type

### Version

0.21.1

**Comment by jszwedko** [comment] 2022-12-24 01:35
Duplicate of https://github.com/vectordotdev/vector/issues/8285

**Closed by jszwedko** 2022-12-24 01:35 UTC
Labels: domain: sources, type: feature
