### ISSUE TITLE
Vector sink/source compression not working for metrics data

### ISSUE THREAD

**Issue by ee07b415** [vectordotdev/vector#18623] opened 2023-09-21 05:54 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

On the vector sink, there is a config for compression, I try to enable it to see if I can save the volume, but it seems did nothing for the metrics data

Here is one example config I'm using
```
    vector_sink:
      type: vector
      inputs:
      - remap_*
      address: _
      tls:
        alpn_protocols:
        - h2
        enabled: true
      buffer:
        type: disk
        when_full: drop_newest
        max_size: 10737418240
      batch:
        max_bytes: 2500000
        timeout_secs: 15
      healthcheck: true
      compression: false
```
<img width="1703" alt="Screenshot 2023-09-20 at 10 39 54 PM" src="https://github.com/vectordotdev/vector/assets/7738043/b9e27c43-ba8d-4be0-9551-bebcddc0b453">
I try to change the above compression and trigger job for the same metrics generator, the volume is the same.

I also verified on the server side where I print out the heade has the grpc_encoding:
```
time="2023-09-21T03:13:52Z" level=info msg="Headers:" 
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-Method: POST"
time="2023-09-21T03:13:52Z" level=info msg="Content-Type: application/grpc"
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-Server: _"
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-Uri: /vector.Vector/PushEvents"
time="2023-09-21T03:13:52Z" level=info msg="Grpc-Encoding: gzip"
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-Port: 8903"
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-Proto: https"
time="2023-09-21T03:13:52Z" level=info msg="X-Real-Ip: _"
time="2023-09-21T03:13:52Z" level=info msg="User-Agent: http/1.1"
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-For: _"
time="2023-09-21T03:13:52Z" level=info msg="X-Forwarded-Host: _"
time="2023-09-21T03:13:52Z" level=info msg="Accept-Encoding: gzip" 
```

The metrics data is generated by the prometheus avalanche which looks like:
```
# HELP avalanche_metric_mmmmm_0_0 A tasty metric morsel
# TYPE avalanche_metric_mmmmm_0_0 gauge
avalanche_metric_mmmmm_0_0{cycle_id="0",label_key_kkkkk_0="label_val_vvvvv_0",label_key_kkkkk_1="label_val_vvvvv_1",label_key_kkkkk_2="label_val_vvvvv_2",label_key_kkkkk_3="label_val_vvvvv_3",label_key_kkkkk_4="label_val_vvvvv_4",label_key_kkkkk_5="label_val_vvvvv_5",label_key_kkkkk_6="label_val_vvvvv_6",label_key_kkkkk_7="label_val_vvvvv_7",label_key_kkkkk_8="label_val_vvvvv_8",label_key_kkkkk_9="label_val_vvvvv_9",series_id="0"} 63
```

And I have a kafka sink get the server received data as:
```
{
  "name": "avalanche_metric_mmmmm_0_106",
  "tags": {
    "component": "",
    "cycle_id": "0",
    "label_key_kkkkk_0": "label_val_vvvvv_0",
    "label_key_kkkkk_1": "label_val_vvvvv_1",
    "label_key_kkkkk_2": "label_val_vvvvv_2",
    "label_key_kkkkk_3": "label_val_vvvvv_3",
    "label_key_kkkkk_4": "label_val_vvvvv_4",
    "label_key_kkkkk_5": "label_val_vvvvv_5",
    "label_key_kkkkk_6": "label_val_vvvvv_6",
    "label_key_kkkkk_7": "label_val_vvvvv_7",
    "label_key_kkkkk_8": "label_val_vvvvv_8",
    "label_key_kkkkk_9": "label_val_vvvvv_9",
    "namespace": "avalanche",
    "pod_name": "avalanche-0",
    "series_id": "9",
    "source_type": "application",
  },
  "timestamp": "2023-09-21T05:52:05.769375408Z",
  "kind": "absolute",
  "gauge": {
    "value": 85
  }
}
```

So I think the overall metrics pipeline is working, just the compression didn't save the bandwidth, not sure if this is as expected. And I also tried to use http sink to send the same data with gzip and I can get 90% reduce in the traffic.

### Configuration

```text
vector_sink:
      type: vector
      inputs:
      - remap_*
      address: _
      tls:
        alpn_protocols:
        - h2
        enabled: true
      buffer:
        type: disk
        when_full: drop_newest
        max_size: 10737418240
      batch:
        max_bytes: 2500000
        timeout_secs: 15
      healthcheck: true
      compression: false
```

### Version

vector 0.33.0

**Comment by jszwedko** [comment] 2023-09-21 15:54
Hi @ee07b415 !

I think it is expected that  compression won't save you too much bandwidth for the `vector` sink because it is encoding the data as protobuf, which is already pretty space efficient. I know there are other compression used with protobuf like snappy -- maybe that would give better results -- but the `vector` sink currently only supports gzip compression.

You didn't share the `http` sink config but, assuming you are sending JSON, then compression will help significantly.

I'll close this out since the feature is working as intended even if you don't get much benefit from gzip compression on top of the protobuf encoded data.

**Closed by jszwedko** 2023-09-21 15:54 UTC
Labels: type: bug

**Comment by ee07b415** [comment] 2023-09-21 16:46
Hi @jszwedko , make sense, thanks for clarify!

**Comment by ee07b415** [comment] 2023-09-22 01:32
Hi @jszwedko , sorry to comment in the closed ticket, but I want to make sure I understand the problem correctly.

From the kubernetes cluster(where the vector running) metrics, actually I can see the out going byte is at compressed size, while the vector internal metrics shows a much larger number so I'm thinking maybe it is the metrics's issue.

From the code I find:
https://github.com/vectordotdev/vector/blob/466ef846bdd7c58f1c341dc557fe01eac47bcc1d/lib/vector-core/src/event/metric/mod.rs#L473

Which means for metrics data, we are calculate the size of the metrics object's size, while the event data calculate the real json encoded size. And because we need to get the metrics event object, so when we calculate the size, it is actually already decompressed, so thats why I can't find any different from the vector internal metrics and vector source see much bigger volume than http server source.

**Comment by jszwedko** [comment] 2023-09-25 17:14
Hi @ee07b415 !

Yes, `component_sent_event_bytes_total`, uses the "estimated JSON" size of the event in its calculations. That is: the estimated size of the event were it encoded as JSON. The intent is to have a neutral measure that applies across all components. There is a corresponding `component_received_event_bytes_total`.

There is also `component_sent_bytes_total` which attempts to measure the number of bytes sent successfully (prior to compression). There is a corresponding `component_received_bytes_total` that attempts to measure the number of successfully received bytes post-decompression.

https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md#instrumentation describes these metrics in more detail.
