### ISSUE TITLE
In v0.33.0 `dnstap` can no longer parse DNS records with DNSSEC/RRSIG RRs

### ISSUE THREAD

**Issue by james-stevens** [vectordotdev/vector#18854] opened 2023-10-16 16:44 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In v0.33.0 `dnstap` can no longer succesfully parse DNS records with DNSSEC/RRSIG records and fails with a `WARN` (see below)

The exact same DNSSEC/RRSIG records could be successfully parsed by v0.32.1

The same issue happens on RHEL9 and Alpine v3.18 - Bug appears in `dnstap` records sent from either `dnsdist` (tested on both RHEL9 & Alpine) or `unbound` (only tested on RHEL9)
```
2023-10-16T16:33:30.581181Z  WARN source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::internal_events::dnstap: Recoverable error occurred while parsing dnstap data. error=Encountered error : Unsupported rdata DNSSEC(RRSIG(RRSIG(SIG { type_covered: A, algorithm: RSASHA256, num_labels: 2, original_ttl: 300, sig_expiration: 1699991362, sig_inception: 1696965506, key_tag: 58609, signer_name: Name("nominet.uk."), sig: [137, 173, 161, 216, 84, 83, 187, 115, 69, 140, 106, 89, 11, 152, 114, 41, 33, 113, 162, 142, 12, 105, 131, 106, 73, 39, 191, 180, 244, 2, 222, 226, 204, 195, 186, 53, 31, 63, 213, 201, 9, 57, 18, 86, 118, 40, 58, 77, 168, 89, 21, 36, 180, 143, 208, 188, 58, 166, 144, 0, 117, 130, 93, 247, 54, 159, 127, 152, 132, 66, 188, 87, 123, 25, 184, 66, 226, 184, 212, 249, 116, 119, 21, 130, 253, 115, 105, 186, 109, 70, 139, 219, 4, 136, 38, 103, 161, 39, 213, 183, 18, 255, 183, 215, 255, 85, 79, 64, 8, 76, 151, 135, 34, 233, 178, 8, 132, 60, 233, 16, 140, 136, 32, 73, 37, 122, 51, 62, 216, 159, 142, 223, 182, 216, 81, 31, 170, 11, 159, 225, 31, 222, 156, 21, 110, 112, 211, 161, 227, 208, 253, 36, 169, 146, 40, 6, 231, 159, 145, 163, 166, 148, 77, 152, 150, 220, 158, 173, 73, 10, 50, 59, 196, 5, 118, 227, 60, 74, 123, 200, 105, 241, 41, 235, 171, 254, 110, 165, 240, 133, 24, 46, 202, 212, 14, 94, 207, 83, 57, 221, 37, 195, 102, 62, 111, 112, 133, 43, 157, 90, 163, 74, 3, 192, 11, 2, 137, 78, 239, 225, 65, 217, 179, 148, 24, 144, 39, 165, 241, 105, 122, 102, 251, 47, 127, 31, 151, 242, 16, 201, 89, 214, 28, 225, 94, 185, 243, 137, 183, 160, 9, 24, 51, 50, 65, 68] }))) stage="processing" error_type="parser_failed" internal_log_rate_limit=true
```

### Configuration

```text
$ cat /etc/vector/vector.toml
data_dir = "/opt/vector/data"
api.enabled=true
healthchecks.require_healthy=true

[sources.dnsdist]
type="dnstap"
socket_path="/run/dnstap.sock"
socket_file_mode=0o777

[sinks.files]
inputs = ["dnsdist"]
type="file"
healthcheck.enabled=true
path="/opt/vector/data/dnstap_%s.log"
framing.method="newline_delimited"
encoding.codec="json"
encoding.metric_tag_values="full"
```
```


### Version

vector 0.33.0 (x86_64-unknown-linux-musl 89605fb 2023-09-27 14:18:24.180809939)

### Debug Output

```text
2023-10-16T16:43:50.370795Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::utilization: utilization=0.000038792498122036976
2023-10-16T16:43:51.370801Z TRACE vector: Beep.
2023-10-16T16:43:52.370793Z TRACE vector: Beep.
2023-10-16T16:43:53.220833Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_common::internal_event::bytes_received: Bytes received. byte_size=104 protocol=protobuf
2023-10-16T16:43:53.221015Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::internal_events::socket: Events received. count=1 byte_size=759 mode=unix
2023-10-16T16:43:53.221058Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_common::internal_event::bytes_received: Bytes received. byte_size=431 protocol=protobuf
2023-10-16T16:43:53.221172Z  WARN source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::internal_events::dnstap: Recoverable error occurred while parsing dnstap data. error=Encountered error : Unsupported rdata DNSSEC(RRSIG(RRSIG(SIG { type_covered: A, algorithm: RSASHA256, num_labels: 2, original_ttl: 300, sig_expiration: 1699991362, sig_inception: 1696965506, key_tag: 58609, signer_name: Name("nominet.uk."), sig: [137, 173, 161, 216, 84, 83, 187, 115, 69, 140, 106, 89, 11, 152, 114, 41, 33, 113, 162, 142, 12, 105, 131, 106, 73, 39, 191, 180, 244, 2, 222, 226, 204, 195, 186, 53, 31, 63, 213, 201, 9, 57, 18, 86, 118, 40, 58, 77, 168, 89, 21, 36, 180, 143, 208, 188, 58, 166, 144, 0, 117, 130, 93, 247, 54, 159, 127, 152, 132, 66, 188, 87, 123, 25, 184, 66, 226, 184, 212, 249, 116, 119, 21, 130, 253, 115, 105, 186, 109, 70, 139, 219, 4, 136, 38, 103, 161, 39, 213, 183, 18, 255, 183, 215, 255, 85, 79, 64, 8, 76, 151, 135, 34, 233, 178, 8, 132, 60, 233, 16, 140, 136, 32, 73, 37, 122, 51, 62, 216, 159, 142, 223, 182, 216, 81, 31, 170, 11, 159, 225, 31, 222, 156, 21, 110, 112, 211, 161, 227, 208, 253, 36, 169, 146, 40, 6, 231, 159, 145, 163, 166, 148, 77, 152, 150, 220, 158, 173, 73, 10, 50, 59, 196, 5, 118, 227, 60, 74, 123, 200, 105, 241, 41, 235, 171, 254, 110, 165, 240, 133, 24, 46, 202, 212, 14, 94, 207, 83, 57, 221, 37, 195, 102, 62, 111, 112, 133, 43, 157, 90, 163, 74, 3, 192, 11, 2, 137, 78, 239, 225, 65, 217, 179, 148, 24, 144, 39, 165, 241, 105, 122, 102, 251, 47, 127, 31, 151, 242, 16, 201, 89, 214, 28, 225, 94, 185, 243, 137, 183, 160, 9, 24, 51, 50, 65, 68] }))) stage="processing" error_type="parser_failed" internal_log_rate_limit=true
2023-10-16T16:43:53.221237Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::internal_events::socket: Events received. count=1 byte_size=2967 mode=unix
2023-10-16T16:43:53.221276Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_buffers::topology::channel::limited_queue: Sent item.
2023-10-16T16:43:53.221289Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_common::internal_event::events_sent: Events sent. count=2 byte_size=3775 output=_default
2023-10-16T16:43:53.221310Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector_core::fanout: Processing control message outside of send: ControlMessage::Add(ComponentKey { id: "files" })
2023-10-16T16:43:53.221328Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector_buffers::topology::channel::limited_queue: Sent item.
2023-10-16T16:43:53.221362Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector_core::fanout: Sent item to fanout.
2023-10-16T16:43:53.221387Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector_common::internal_event::events_received: Events received. count=2 byte_size=3775
2023-10-16T16:43:53.221416Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 2703362, tv_nsec: 380588611 } path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:53.221439Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Opening new file. path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:53.221866Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Writing an event to file. path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:53.221966Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=782
2023-10-16T16:43:53.221992Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::internal_events::file: Bytes sent. byte_size=783 protocol="file" file=/opt/vector/data/dnstap_1697474631.log
2023-10-16T16:43:53.222034Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 2703362, tv_nsec: 381207632 } path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:53.222050Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Working with an already opened file. path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:53.222058Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Writing an event to file. path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:53.222206Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=2990
2023-10-16T16:43:53.222225Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::internal_events::file: Bytes sent. byte_size=2993 protocol="file" file=/opt/vector/data/dnstap_1697474631.log
2023-10-16T16:43:53.370795Z TRACE vector: Beep.
2023-10-16T16:43:54.370797Z TRACE vector: Beep.
^C2023-10-16T16:43:55.158794Z  INFO vector::signal: Signal received. signal="SIGINT"
2023-10-16T16:43:55.158863Z  INFO vector: Vector has stopped.
2023-10-16T16:43:55.158952Z  INFO source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::sources::util::framestream: Finished sending.
2023-10-16T16:43:55.159104Z DEBUG source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector::topology::builder: Source finished normally.
2023-10-16T16:43:55.159123Z DEBUG source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector::topology::builder: Source pump finished normally.
2023-10-16T16:43:55.159166Z DEBUG source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector::topology::builder: Source pump supervisor task finished normally.
2023-10-16T16:43:55.159185Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Receiver exhausted, terminating the processing loop.
2023-10-16T16:43:55.159204Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Closing all the open files.
2023-10-16T16:43:55.160819Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="files" time_remaining="59 seconds left"
2023-10-16T16:43:55.240218Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Successfully closed file. path=b"/opt/vector/data/dnstap_1697474631.log"
2023-10-16T16:43:55.240252Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::topology::builder: Sink finished normally.
```

### Example Data

`dig @192.168.1.145 +dnssec nominet.uk`

**Comment by james-stevens** [comment] 2023-10-16 16:49
This is the trace logging the exact same DNS query & response `dnstap` data, but this time using vector v0.32.1
```
2023-10-16T16:46:31.780784Z TRACE vector: Beep.
2023-10-16T16:46:32.780776Z TRACE vector: Beep.
2023-10-16T16:46:32.780796Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::utilization: utilization=0.00029691273360209143
2023-10-16T16:46:33.780787Z TRACE vector: Beep.
2023-10-16T16:46:34.130835Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_common::internal_event::bytes_received: Bytes received. byte_size=104 protocol=protobuf
2023-10-16T16:46:34.131822Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::internal_events::socket: Events received. count=1 byte_size=759 mode=unix
2023-10-16T16:46:34.131859Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_common::internal_event::bytes_received: Bytes received. byte_size=431 protocol=protobuf
2023-10-16T16:46:34.131956Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::internal_events::socket: Events received. count=1 byte_size=1445 mode=unix
2023-10-16T16:46:34.132005Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_buffers::topology::channel::limited_queue: Sent item.
2023-10-16T16:46:34.132014Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector_common::internal_event::events_sent: Events sent. count=2 byte_size=2253 output=_default
2023-10-16T16:46:34.132034Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector_core::fanout: Processing control message outside of send: ControlMessage::Add(ComponentKey { id: "files" })
2023-10-16T16:46:34.132058Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector_buffers::topology::channel::limited_queue: Sent item.
2023-10-16T16:46:34.132072Z TRACE source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector_core::fanout: Sent item to fanout.
2023-10-16T16:46:34.132090Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector_common::internal_event::events_received: Events received. count=2 byte_size=2253
2023-10-16T16:46:34.132111Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 2703523, tv_nsec: 291283712 } path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:34.160210Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Opening new file. path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:34.160612Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Writing an event to file. path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:34.160787Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=782
2023-10-16T16:46:34.160804Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::internal_events::file: Bytes sent. byte_size=783 protocol="file" file=/opt/vector/data/dnstap_1697474792.log
2023-10-16T16:46:34.160856Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 2703523, tv_nsec: 320029201 } path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:34.160883Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Working with an already opened file. path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:34.160904Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Writing an event to file. path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:34.161121Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=1468
2023-10-16T16:46:34.161139Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::internal_events::file: Bytes sent. byte_size=1469 protocol="file" file=/opt/vector/data/dnstap_1697474792.log
2023-10-16T16:46:34.780779Z TRACE vector: Beep.
2023-10-16T16:46:35.780798Z TRACE vector: Beep.
^C2023-10-16T16:46:36.368366Z  INFO vector::signal: Signal received. signal="SIGINT"
2023-10-16T16:46:36.368453Z  INFO vector: Vector has stopped.
2023-10-16T16:46:36.368551Z  INFO source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}:connection: vector::sources::util::framestream: Finished sending.
2023-10-16T16:46:36.368751Z DEBUG source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector::topology::builder: Source finished normally.
2023-10-16T16:46:36.368816Z DEBUG source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector::topology::builder: Source pump finished normally.
2023-10-16T16:46:36.368859Z DEBUG source{component_kind="source" component_id=dnsdist component_type=dnstap component_name=dnsdist}: vector::topology::builder: Source pump supervisor task finished normally.
2023-10-16T16:46:36.368886Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Receiver exhausted, terminating the processing loop.
2023-10-16T16:46:36.368894Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Closing all the open files.
2023-10-16T16:46:36.368938Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="files" time_remaining="59 seconds left"
2023-10-16T16:46:36.532078Z TRACE sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::sinks::file: Successfully closed file. path=b"/opt/vector/data/dnstap_1697474792.log"
2023-10-16T16:46:36.532117Z DEBUG sink{component_kind="sink" component_id=files component_type=file component_name=files}: vector::topology::builder: Sink finished normally.
```

**Comment by james-stevens** [comment] 2023-10-17 09:18
I have confirmed this is *NOT* an issue for v0.32.2 on RHEL9 - DNSSEC/RRSIG records are correctly parsed using this version

    vector 0.32.2 (x86_64-unknown-linux-gnu beb74c1 2023-09-20 19:46:02.271601143)

NOTE: For me, using the v0.32.2 binary provided by OEM required two environment variables to be set

    VECTOR_OPENSSL_LEGACY_PROVIDER=false
    VECTOR_CONFIG_YAML=/etc/vector/vector.yaml

The first one was a required setting related to `openssl`, the second was because I had used a YAML format config file, which is selected automatically in v0.33.0, but must be manually forced in v0.32.2

On RHEL9 these settings can be put into `/etc/default/vector`, but must also be exported in your shell if (for example) you wish to run `vector validate`

**Comment by neuronull** [comment] 2023-10-17 20:21
Ok, I think I tracked this down.

In Vector `v0.33.0`, this included a commit which upgraded the `trust-dns-proto` crate, which is used in the parsing of the dns messages for the `dnstap` source (https://github.com/vectordotdev/vector/pull/18349)

That dependency crate upgrade from `v0.22.0` to `v0.23.0` , introduced this change: https://github.com/hickory-dns/hickory-dns/commit/0f21992811ee2dbf09cd00a419a3d6d0868a748c#diff-21e0dc5da2afd7765e8fb341c7d09d6442bf9b6c6731dd3e6f1f30d4fe7d0d06 , wherein the enum `DNSSECRData` was expanded with a new variant, `RSIG`.

We can see from the warning message in the Vector log that this is the rdata type we are receiving:

```
Unsupported rdata DNSSEC(RRSIG(RRSIG(SIG
```

Inspecting the relevant code, it looks like that rdata type was previously considered "Unknown" by the `trust-dns-proto` , and in Vector we considered that Ok. But now it falls into the catch-all case in Vector, because we don't have a specific handling for the `RSIG` rdata type.

https://github.com/vectordotdev/vector/blob/8a5b67e452772887d5353ff245d33bd4e2ed19ba/lib/dnsmsg-parser/src/dns_message_parser.rs#L747-L750

So this is a case of an upstream dependency upgrade silently (our existing tests didn't cover this case) introducing logic that results in a functional regression in Vector.
I think the fix will just involve expanding the `dnsmsg-parser` library in Vector, to properly handle the new rdata type. We should probably also add some tests for this.

**Comment by neuronull** [comment] 2023-10-17 22:22
I am working on the fix for this.

**Comment by james-stevens** [comment] 2023-10-19 14:10
that was quick !

**Closed** 2023-10-20 18:44 UTC
Labels: type: bug, domain: parsing, source: dnstap, meta: confirmed
