### ISSUE TITLE
vector outputs warning (stderr self logs) when using $xxx env var at commented out yaml config line

### ISSUE THREAD

**Issue by suiluj** [vectordotdev/vector#17712] opened 2023-06-20 13:24 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Not a big issue but I noticed that vector outputs a warning when a comment contains the format of an environment variable ( `$<some_text>`). In my opinion comments should just be ignored at configuration checks.

I use a yaml config file and when I run vector it outputs a warning. It still works without problem.

```yaml
.
.
.
# just some comments in my config...
# example grafana query for clickouse: SELECT timestamp, message,..., formatDateTime(extra_timestamp_column,'%F %T%z') as extra_timestamp_column_converted FROM testdb."testtable" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) LIMIT 1000
.
.
.
```

here is the part of the vector internal logs that I caputre in stderr

```
2023-06-20T13:12:17.589922Z  WARN vector::config::loading: Unknown env var in config. name = "__fromTime"
2023-06-20T13:12:17.589950Z  WARN vector::config::loading: Unknown env var in config. name = "__toTime"
2023-06-20T13:12:17.589953Z  WARN vector::config::loading: Unknown env var in config. name = "__fromTime"
2023-06-20T13:12:17.589955Z  WARN vector::config::loading: Unknown env var in config. name = "__toTime"
2023-06-20T13:12:17.590619Z  INFO vector::sources::file_descriptors: Capturing stdin.
2023-06-20T13:12:17.602598Z  INFO vector::topology::running: Running healthchecks.
2023-06-20T13:12:17.602691Z  INFO vector: Vector has started. debug="false" version="0.29.1" arch="x86_64" revision="74ae15e 2023-04-20 14:50:42.739094536"
2023-06-20T13:12:17.602700Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2023-06-20T13:12:17.602755Z  INFO vector::topology::builder: Healthcheck passed.
2023-06-20T13:12:17.603789Z  INFO vector_common::shutdown: All sources have finished.
2023-06-20T13:12:17.603813Z  INFO vector_common::shutdown: All sources have finished.
2023-06-20T13:12:17.604234Z  INFO vector::app: All sources have finished.
2023-06-20T13:12:17.604250Z  INFO vector: Vector has stopped.
```

### Version

0.29.1

**Comment by spencergilbert** [comment] 2023-06-20 14:59
Thanks for raising @suiluj - This is a duplicate of https://github.com/vectordotdev/vector/issues/797, so I'm going to close this issue out.

**Closed by spencergilbert** 2023-06-20 14:59 UTC
Labels: type: bug
