### ISSUE TITLE
Support multiple endpoints in Elasticsearch sink

### ISSUE THREAD

**Issue by bryanasdev000** [vectordotdev/vector#13900] opened 2022-08-09 13:32 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Load balance writing to ES clusters.

### Attempted Solutions

Using the helm chart, I tried to use comma to separate hosts and YAML list, got:

```
Configuration error. error=invalid type: sequence, expected a string for key `sinks.elasticsearch`
```

### Version

timberio/vector:0.22.3-distroless-libc

**Comment by spencergilbert** [comment] 2022-08-09 13:35
👋 
Closing as a duplicate of https://github.com/vectordotdev/vector/issues/3649, and there's a WIP PR to add support here: https://github.com/vectordotdev/vector/pull/13236

**Closed by spencergilbert** 2022-08-09 13:35 UTC
Labels: type: feature

**Comment by bryanasdev000** [comment] 2022-08-09 13:46
> wave Closing as a duplicate of #3649, and there's a WIP PR to add support here: #13236

Doh!

Github search tricks me again.

Thanks!

**Comment by spencergilbert** [comment] 2022-08-09 13:48
NP, I know how finicky search can be 😃 - I expect the PR to land _fairly_ soon, we've hashed out most of the design issues, if I remember correctly.
