### ISSUE TITLE
Convert QuickCheck code to PropTest

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9131] opened 2021-09-13 18:38 UTC
In #8960 I used [proptest](https://github.com/AltSysrq/proptest) instead of quickcheck as I normally would have, and as we do in core. In the long-term I would like to see the project use tools like [propverify](https://github.com/project-oak/rust-verification-tools) for critical components, which makes proptesting a requirement. I've been happy with the experience of proptest so far and would like to complete the conversion of any existing quickcheck code to proptest. 

Most of our quickcheck code is in core. We should be able to reduce the arbitrary constraints on `Value` creation imposed by the use of quickcheck, owing to proptest's improved support for recursive structures.

**Comment by jszwedko** [comment] 2022-12-29 16:18
Closing this since we've just been doing it as we go.

**Closed by jszwedko** 2022-12-29 16:18 UTC
Labels: type: enhancement, domain: tests

**Comment by spencergilbert** [comment] 2023-01-04 14:11
I think we should still have a discoverable note about this somewhere, it was asked recently which we were migrating to - and this issue helped confirm that, rather than being in memory for some set of engineers. Perhaps just `TODO`'s alongside the existing quickcheck usages?

**Comment by jszwedko** [comment] 2023-01-04 14:18
> I think we should still have a discoverable note about this somewhere, it was asked recently which we were migrating to - and this issue helped confirm that, rather than being in memory for some set of engineers. Perhaps just `TODO`'s alongside the existing quickcheck usages?

Agreed. I'd suggest something in `DEVELOPING.md`. Notably the issue is still here, just closed, so it is usable as a reference 😄

**Comment by spencergilbert** [comment] 2023-01-04 14:23
Fair, I think with the defaults I end up having closed issues filtered out - but that's a reasonable suggestion.
