### ISSUE TITLE
 Log the client IP address - HTTP Server Source

### ISSUE THREAD

**Issue by vsrivatsa-juspay** [vectordotdev/vector#19562] opened 2024-01-09 07:43 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Support logging the client IP address when HTTP Server is being used as the source

**Comment by jszwedko** [comment] 2024-01-09 15:30
Hi @vsrivatsa-juspay ! Thanks for opening this. I think it is a duplicate of https://github.com/vectordotdev/vector/issues/4221. I'll close this one, but feel free to follow along there.

**Closed by jszwedko** 2024-01-09 15:30 UTC
Labels: type: feature
