### ISSUE TITLE
Vector: Compression for Vector Source/Sink

### ISSUE THREAD

**Issue by splitice** [vectordotdev/vector#10748] opened 2022-01-06 23:41 UTC
### Use-cases

Reduce bandwidth transfer when working with remote vector instances

### Proposal

I havent looked into the source/sink much but both gRPC and HTTP have compression standards, could we just use that?

P.S would an enhancement to rename the vector source/sink to a seperate name be accepted as an issue? Its a minor inconvenience but confusing to reference since it shares a name with the parent protocol.

**Comment by jszwedko** [comment] 2022-01-19 22:30
Duplicate of https://github.com/vectordotdev/vector/issues/9558 . We should definitely do this though.

**Closed by jszwedko** 2022-01-19 22:30 UTC
Labels: type: enhancement, sink: vector, source: vector
