### ISSUE TITLE
gcp_storage sink "An error occurred that Vector couldn't handle"

### ISSUE THREAD

**Issue by gschier** [vectordotdev/vector#13077] opened 2022-06-09 21:43 UTC
### Problem

We at [Railway](railway.app) tried out the the `gcp_pubsub` source in production today and found some bugs (#12846, #13075). We use `--watch-config` to update our Vector configuration on deployment, and after doing so, Vector crashed and could not recover after restarting. The config change we made was switching the source on our `gcp_storage` sink which I assume was not handled correctly by Vector and lead to some sort of corruption? We changed the name of the `gcp_storage` component to "reset" it and it started fine after that.

Here's the error from our logs:

```
ERROR sink{component_kind="sink" component_id=out_google_cloud_storage component_type=gcp_cloud_storage component_name=out_google_cloud_storage}: vector::topology: An error occurred that Vector couldn't handle.
```

### Configuration

```text
data_dir = "${LOGGER_VECTOR_PATH}"

[api]
enabled = true
playground = false

[sources.in_vector]
type = "vector"
version = "2"
address = "0.0.0.0:5143"

[sources.in_pubsub]
type = "gcp_pubsub"
project = "railway-infra"
subscription = "railway-production-logs-sub"

[transforms.extract_pubsub_message]
type = "remap"
inputs = [ "in_pubsub" ]
source = ". = parse_json!(.message)"

[sinks.out_file]
type = "file"
inputs = ["in_pubsub"]
compression = "none"
encoding = "ndjson"
path = "${LOGGER_VECTOR_PATH}/out_file/logs/%F_%H/{{ appname }}.log"

[sinks.out_google_cloud_storage]
type = "gcp_cloud_storage"
inputs = ["in_pubsub"]
bucket = "${LOGGER_BUCKET_NAME:-railway-develop-logs}"
key_prefix = "logs/{{ appname }}/"
compression = "none"
buffer.type = "disk"
buffer.max_size = 1_500_000_000_000 # 1.5 TB
batch.timeout_secs = 600 # 10 Minutes
batch.max_bytes = 10_000_000 # 1 MB
filename_append_uuid = false
encoding = "ndjson"
# Note: Time in `filename_time_format` uses time-of-last-log unlike `key_prefix` which uses time-of-first-log
filename_time_format = "%F/%T"

# Internal metrics for our reporting to DataDog

[sources.in_internal]
type = "internal_metrics"
namespace = "vector"
scrape_interval_secs = 60

[transforms.transform_datadog]
type = "filter"
inputs = [ "in_internal" ]
condition = '.name == "utilization" || .name == "component_sent_event_bytes_total" || .name == "component_received_event_bytes_total"'

[sinks.out_datadog]
type = "datadog_metrics"
inputs = ["transform_datadog"]
api_key = "${DD_API_KEY}"
```

### Version

vector 0.22.0 (x86_64-unknown-linux-gnu 5e937e3 2022-06-01)

**Comment by jszwedko** [comment] 2022-06-13 14:42
Hi @gschier !

Thanks for this report. Would it be possible to provide the before and after configuration that triggered the issue?

**Comment by gschier** [comment] 2022-06-15 20:11
I believe this was the change that did it

<img width="837" alt="image" src="https://user-images.githubusercontent.com/587576/173918078-373b2b3b-20ad-44ac-a2c0-78214a0a6d78.png">

Note: I also updated the config in my original issue description to match what it was a the time of this change.

I appreciate the help!

**Comment by lukesteensen** [comment] 2022-07-12 22:03
It took some doing, but I was finally able to reproduce this. I'm not sure that it's entirely deterministic. Some more detailed errors logs here:

```
2022-07-12T21:53:33.162036Z  INFO vector::config::watcher: Configuration file changed.
2022-07-12T21:53:33.162822Z  WARN vector::config::loading: Transform "extract_pubsub_message" has no consumers
2022-07-12T21:53:33.162840Z  WARN vector::config::loading: Source "in_vector" has no consumers
2022-07-12T21:53:33.162854Z  INFO vector::topology::running: Reloading running topology with new configuration.
thread 'vector-worker' panicked at 'Pausing non-existent sink is not valid: out_google_cloud_storage', lib/vector-core/src/fanout.rs:315:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'vector-worker' panicked at 'join error: JoinError::Panic(Id(47), ...)', src/topology/builder.rs:212:30
2022-07-12T21:53:33.163151Z ERROR source{component_kind="source" component_id=in_vector component_type=demo_logs component_name=in_vector}: vector::internal_events::common: Failed to forward event(s), downstream is closed. error_code="stream_closed" error_type="writer_failed" stage="sending" count=1
2022-07-12T21:53:33.163189Z ERROR source{component_kind="source" component_id=in_vector component_type=demo_logs component_name=in_vector}: vector::topology: An error occurred that Vector couldn't handle.
2022-07-12T21:53:33.177800Z ERROR source{component_kind="source" component_id=in_vector component_type=demo_logs component_name=in_vector}: vector::topology: An error occurred that Vector couldn't handle.
```

I'm guessing that this has something to do with the use of disk buffers, as those trigger a somewhat different path through our reload logic to ensure that we don't drop any events currently in the buffer. The error is complaining about pausing writes to the sink (which we do while rebuilding for new inputs) when the sink is not present in the fanout instance (which implies we've already removed it, likely temporarily, as part of the reload). I'll walk through the code and try to find where we'd be doing this redundant remove/pause for this particular situation.

**Comment by lukesteensen** [comment] 2022-07-26 19:15
After some more experimentation, I was able to reduce this further to the following config:

```toml
[sources.in_vector]
type = "demo_logs"
format = "json"
interval = 0.0

[sources.in_pubsub]
type = "demo_logs"
format = "json"
interval = 0.0

[sinks.out_google_cloud_storage]
type = "blackhole"
inputs = ["in_vector"]
rate = 1
```

This would error quite reliably when switching the sink's input between the two sources, which seems to imply I was wrong about the disk buffer path above.

I also found that I was unable to reproduce the issue this way after 8d484b244ba500abcd18ccc1778fbcfa109bc088, which means it may have already been fixed as part of https://github.com/vectordotdev/vector/pull/13375. @gschier would it be possible for you to test a recent nightly build and see if you're still encountering this issue?

**Comment by jszwedko** [comment] 2022-08-08 20:20
Closing since this seems to be resolved, but please feel free to re-open if you see this again!

**Comment by khaskelbergTAU** [comment] 2022-10-08 19:39
i have managed to trigger this bug again as of 0.24.1. compiling from source, using config pasted below.

it is non deterministic, im triggering it by running with --watch-config and then causing rebuilds by changing the ip field until one of them causes the panic.
```
[sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 0

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
.ip = "ip"
'''


# Print parsed logs to stdout
[sinks.print]
type = "blackhole"
inputs = ["parse_logs"]
```

**Comment by jszwedko** [comment] 2022-10-26 17:31
👍 thanks for the report @khaskelbergTAU . Re-opening.

**Comment by StephenWakely** [comment] 2023-09-11 14:59
I'm trying with Version 32.1 with all the above configs and am unable to reproduce, so I think we shall close again.

**Closed by StephenWakely** 2023-09-11 14:59 UTC
Labels: domain: config, domain: reload
