### ISSUE TITLE
kubernetes_logs  support custom logfile

### ISSUE THREAD

**Issue by XuHandsome** [vectordotdev/vector#20366] opened 2024-04-24 09:42 UTC
### Use Cases

Now that vector supports kubernetes_logs, why find logs only in /var/log/pods?

In my application scenario, the in-container service prints logs to a different directory instead of standard output! For example:
```yaml
volumes:
- emptyDir: {}
name: logdir
```

In this case, on the host it should be "/var/lib/kubelet/pods/*/volumes/kubernetes.io~empty-dir/logdir/*/*.log",

In filebeat, I can specify this location with filestream to scan for the log files I want, and then add rich data with `processors.add_kubernetes_metadata`

### References

[filebeat add-kubernetes-metadata](https://www.elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html)

### Version

latest

**Comment by jszwedko** [comment] 2024-04-24 15:56
Hi @XuHandsome !

We had actually discussed this idea of a separate transform (similar to filebeat processors) to enrich the k8s metadata. I discovered the issue was closed, though, so I reopened it: https://github.com/vectordotdev/vector/issues/5077. I'll close this as a duplicate of that one but feel free to add additional thoughts there.

**Closed by jszwedko** 2024-04-24 15:56 UTC
Labels: type: feature
