### ISSUE TITLE
Error collecting logs from Docker containers

### ISSUE THREAD

**Issue by dmitriydya** [vectordotdev/vector#16144] opened 2023-01-26 17:38 UTC
### A note for the community

I use vector to collect logs from docker containers and then send them to elastic or files.

### Problem

When the log file size is limited by docker/docker-compose, the vector stops sending logs after the first file is full and docker creates a new log file.

### Configuration

vector.yaml
```
# ------------ SOURCE SECTION -------------
[sources.docker_logs]
  type = "docker_logs"
  docker_host = "/var/run/docker.sock"
  auto_partial_merge = true
  include_containers = [ "" ]
  exclude_containers = [ "vector" ]
  retry_backoff_secs = 1
  host_key = "host"

# ------------ SINK SECTION ---------------
[sinks.to_logs_server]
  type = "vector"
  inputs = ["docker_logs"]
  address = "10.10.10.10:1010"
  healthcheck = true
  buffer.type = "memory"
```

docker-compose.yaml
```
version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    logging:
      options:
        max-size: "5m"
        max-file: "1"
```

### Version

Vector - 0.27.0, Docker - 20.10.22

### Debug Output

The logs do not show errors. In fact, they don't exist for a vector.
Vector does not know that container logs start to be written to another file after the first file is 5 MB full.

**Comment by jszwedko** [comment] 2023-01-26 17:41
@MrDimaFIX thanks for the report! The `docker_logs` source actually just reads the logs from the Docker API rather than tailing the files themselves so it _shouldn't_ be affected by rotation. Do you know if `docker logs` correctly streams logs after rotation? Can you share your docker container info (`docker info ...`)?

**Comment by MrDimaFIX** [comment] 2023-01-26 17:59
The `docker logs nginx -f` command works correctly. After the file has overflowed, new log entries are shown in the console, but vector does not see them.
At first, I thought that the problem was in elastic itself. I have enabled the output of the vector messages to the log in this way:
```
[sinks.console-log]
type = "console"
inputs = [ "docker_log" ]
target = "stdout"
encoding.codec = "json"
```
After the file overflows (the time can be different, with my workload it happens from 20 to 40 minutes), the vector stops receiving and sending new messages to the log

My docker inspect output:

```
[
    {
        "Id": "4a4e8843b3b37f1688fd0ce6e49a3640d10978c57b6a604fa540eecc6dcc81b9",
        "Created": "2023-01-26T17:41:09.286706071Z",
        "Path": "/bin/bash",
        "Args": [
            "/scripts/entrypoint.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 834849,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-01-26T17:41:09.681131863Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:ea7311ebbe0df2abfe681b2908b72ba94581a4cb412375c64b0af81c255936ec",
        "ResolvConfPath": "/var/lib/docker/containers/4a4e8843b3b37f1688fd0ce6e49a3640d10978c57b6a604fa540eecc6dcc81b9/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4a4e8843b3b37f1688fd0ce6e49a3640d10978c57b6a604fa540eecc6dcc81b9/hostname",
        "HostsPath": "/var/lib/docker/containers/4a4e8843b3b37f1688fd0ce6e49a3640d10978c57b6a604fa540eecc6dcc81b9/hosts",
        "LogPath": "/var/lib/docker/containers/4a4e8843b3b37f1688fd0ce6e49a3640d10978c57b6a604fa540eecc6dcc81b9/4a4e8843b3b37f1688fd0ce6e49a3640d10978c57b6a604fa540eecc6dcc81b9-json.log",
        "Name": "/nginx",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/docker/nginx/conf.d:/etc/nginx/user.conf.d:rw",
                "/docker/nginx/ssl:/etc/nginx/ssl:rw",
                "/docker/nginx/letsencrypt:/etc/letsencrypt:rw",
                "/docker/nginx/configs:/etc/nginx/configs:ro",
                "/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "5m"
                }
            },
            "NetworkMode": "nginx",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": [
                {
                    "Name": "nofile",
                    "Hard": 65535,
                    "Soft": 65535
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/86cc43b5640af1f772e31ab71ea0b4793a9164b744d35d89b078c7322fbcdd75-init/diff:/var/lib/docker/overlay2/37fcab3e803c95e53e54e7b95e91029d4a8293311242046a5489f3c45c84f2fd/diff:/var/lib/docker/overlay2/41f9b5dc598bbc296a9d331cd46d35cbd6a10e90194dadbea4845e83efbf62a9/diff:/var/lib/docker/overlay2/697145f92b6ae2742e610a81c126b533ccdf9a0eb676b650876c3797dff3e0ab/diff:/var/lib/docker/overlay2/960a8649c26275f877418dfd49f7524f015a7d0aac91aebded1f53174f0b1c11/diff:/var/lib/docker/overlay2/137420b760f119a2ee1c1ae2ab171ff5c2702d8c68d20cc121afe240a36cb661/diff:/var/lib/docker/overlay2/f8ced8d42009e5442bdf2bc976ad7eab2b3da7f751d580986af3144706abe85e/diff:/var/lib/docker/overlay2/3f3aea63e43896b4375a6923ab58588c8727c7a413a9648723a38087a4475c5f/diff:/var/lib/docker/overlay2/b42cdaa48b04ac9940d85956191bf9c33fba1ec4c7f9ccce0754f8148db77c78/diff:/var/lib/docker/overlay2/c139d4ac6052bc627be59cd6aec580262073b9a63c2f728b16bfd8386d065917/diff:/var/lib/docker/overlay2/be741b7f9e52d1c9c613be4d084eb56932ae440926de1e067459dbc421d1de32/diff:/var/lib/docker/overlay2/64caa563fedb633333f54940b5a62899acbedcf64febba21c009d4564cd03e24/diff:/var/lib/docker/overlay2/f9ef5dd0a74c2c3f016aa7fe81fd05351329ad5cd847ee1b434f792b1ef795b3/diff:/var/lib/docker/overlay2/49a149dc458d186feaa7b9177deccace65ca021639a76a05605cbd117c896e2e/diff",
                "MergedDir": "/var/lib/docker/overlay2/86cc43b5640af1f772e31ab71ea0b4793a9164b744d35d89b078c7322fbcdd75/merged",
                "UpperDir": "/var/lib/docker/overlay2/86cc43b5640af1f772e31ab71ea0b4793a9164b744d35d89b078c7322fbcdd75/diff",
                "WorkDir": "/var/lib/docker/overlay2/86cc43b5640af1f772e31ab71ea0b4793a9164b744d35d89b078c7322fbcdd75/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/docker/nginx/conf.d",
                "Destination": "/etc/nginx/user.conf.d",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/docker/nginx/ssl",
                "Destination": "/etc/nginx/ssl",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/docker/nginx/letsencrypt",
                "Destination": "/etc/letsencrypt",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/docker/nginx/configs",
                "Destination": "/etc/nginx/configs",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/docker/nginx/nginx.conf",
                "Destination": "/etc/nginx/nginx.conf",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "4a4e8843b3b3",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "CERTBOT_EMAIL=devops@mail.local",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.22.1",
                "NJS_VERSION=0.7.7",
                "PKG_RELEASE=1~bullseye"
            ],
            "Cmd": [
                "/bin/bash",
                "/scripts/entrypoint.sh"
            ],
            "Image": "registry.server.local/docker-images/nginx-le-cf:latest",
            "Volumes": {
                "/etc/letsencrypt": {},
                "/etc/localtime": {},
                "/etc/nginx/configs": {},
                "/etc/nginx/nginx.conf": {},
                "/etc/nginx/ssl": {},
                "/etc/nginx/user.conf.d": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "706013e7b18a7a29250aa8b0b8cd9ab19399dcacb1df4c2b30d3d9f148dbaa6d",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:ea7311ebbe0df2abfe681b2908b72ba94581a4cb412375c64b0af81c255936ec",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "nginx",
                "com.docker.compose.project.config_files": "/docker/nginx/docker-compose.yaml",
                "com.docker.compose.project.working_dir": "/docker/nginx",
                "com.docker.compose.service": "nginx",
                "com.docker.compose.version": "2.14.1",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>"
            },
            "StopSignal": "SIGQUIT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9b1b68d81f6cb091a4cc4bfbf68935e528b80a95aac33210cdc75b161b08b1b7",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/9b1b68d81f6c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nginx": {
                    "IPAMConfig": {
                        "IPv4Address": "172.18.0.2"
                    },
                    "Links": null,
                    "Aliases": [
                        "nginx",
                        "nginx",
                        "4a4e8843b3b3"
                    ],
                    "NetworkID": "79c3d5866a2b847ffc332eb3788d236fcbc91ccc4268fd488830fc056046cfe2",
                    "EndpointID": "23f76abd50082568e31eb1bfb1e8ab902361ee2c9456dd1ae1c6f579d9176d93",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by fuchsnj** [comment] 2023-03-15 17:52
I ran a simple test with a docker container that rotates files every several seconds and wasn't able to reproduce.
If you are able to produce a setup to reproduce this issue, that would be really helpful.

### Test setup

docker container (it just quickly prints out logs, with the log size limited to 1mb)
```sh
docker run --log-driver json-file --log-opt max-size=1m chentex/random-logger:latest 1 1
```

Vector config (same source listed above)
```toml
[sources.docker_logs]
type = "docker_logs"
docker_host = "/var/run/docker.sock"
auto_partial_merge = true
include_containers = [ "" ]
exclude_containers = [ "vector" ]
retry_backoff_secs = 1
host_key = "host"

[sinks.console]
type = "console"
encoding.codec = "json"
inputs = ["docker_logs"]
```
 logs can be viewed with `ls -la /var/lib/docker/containers/<containerid>`

**Comment by jszwedko** [comment] 2023-09-28 01:56
Closing since we haven't been able to reproduce this issue. If you have a reproduction case, please drop a comment with it!

**Closed by jszwedko** 2023-09-28 01:56 UTC
