### ISSUE TITLE
`prometheus_remote_write` sink always fails healthcheck with 405 Method Not Allowed

### ISSUE THREAD

**Issue by nzxwang** [vectordotdev/vector#21627] opened 2024-10-26 21:09 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `prometheus_remote_write` sink always fail its healthcheck: 
```
ERROR vector::topology::builder: msg="Healthcheck failed." error=Unexpected status: 405 Method Not Allowed component_kind="sink" component_type="prometheus_remote_write" component_id=sink_prometheus_remote_write
```

I tested this with the `prometheus_remote_write` source and the logs on the receiving side suggests that the `prometheus_remote_write` sink performs some GET request upon initiation:
```
ERROR source{component_kind="source" component_id=prometheus_remote_write_endpoint component_type=prometheus_remote_write}:http-request{method=GET path=/}: vector::internal_events::http: Internal error: Rejection(MethodNotAllowed) error_type="connection_failed" stage="receiving" internal_log_rate_limit=true
```

### Configuration

```text
[sinks.sink_prometheus_remote_write]
type = "prometheus_remote_write"
inputs = [ "source_heartbeat_metric" ]
endpoint = "http://localhost:9090"

[sources.prometheus_remote_write_endpoint]
type = "prometheus_remote_write"
address = "0.0.0.0:9090"
```

### Version

vector 0.42.0 (x86_64-apple-darwin 3d16e34 2024-10-21 14:10:14.375255220)

**Comment by jszwedko** [comment] 2024-10-28 14:24
Hi @nzxwang ! Thanks for opening this. I think it is a duplicate of https://github.com/vectordotdev/vector/issues/8279 so I'll close this one but let me know if you disagree.

**Closed by jszwedko** 2024-10-28 14:24 UTC
Labels: type: bug
