### ISSUE TITLE
Unrecoverable error -  Last record written to data file is behind expected position

### ISSUE THREAD

**Issue by StarpTech** [vectordotdev/vector#16463] opened 2023-02-15 18:33 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

```
2023-02-15T18:23:37.440 app[b8fb6d87] ewr [info] 2023-02-15T18:23:37.439844Z ERROR vector_buffers::variants::disk_v2::writer: Last record written to data file is behind expected position. Events have likely been lost. ledger_next=128545 last_record_id=128542 record_events=1
```

After that log, the healthcheck endpoint `:8686/health` no longer returns ok. The only solution here is to re-create the volumes.

### Version

0.27.0

**Comment by jszwedko** [comment] 2023-03-06 15:45
Thanks for the report @StarpTech ! This looks like a duplicate of https://github.com/vectordotdev/vector/issues/16231 so I'll close this one out. The user over there noted they could workaround it by just deleting the disk buffer checkpoint file rather than recreating the whole volume so you could try that if you run into it again.

**Closed by jszwedko** 2023-03-06 15:45 UTC
Labels: type: bug
