### ISSUE TITLE
Customizable template syntax delimiters

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#8410] opened 2021-07-21 18:46 UTC
https://vector.dev/docs/reference/configuration/template-syntax/#event-fields

The current `{{ ... }}` syntax clashes with Helm and causes a lot of headache when configuring Vector via our Helm charts.

We should allow for configuration of the delimiters to make configuration easier for users.

Ref: https://svn.python.org/projects/external/Jinja-1.2/docs/html/altsyntax.html

**Comment by spencergilbert** [comment] 2021-07-21 18:47
See some examples of painful config that includes curly braces: https://github.com/helm/helm/issues/2798

**Comment by LinTechSo** [comment] 2022-02-12 14:35
Hi, same issue, any updates?

**Comment by jszwedko** [comment] 2022-12-29 17:26
Duplicate of https://github.com/vectordotdev/vector/issues/7586

**Closed by jszwedko** 2022-12-29 17:26 UTC
Labels: type: enhancement, domain: config, domain: templating, platform: helm

**Comment by szibis** [comment] 2024-09-29 20:21
> Hi @LinTechSo - this work has yet to be prioritized but does have a workaround, see [here](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/README.md#using-template-syntax-in-customconfig) where I included Vector templates within a helm templated file.

Will not work just as example in https://github.com/vectordotdev/vector/issues/7586. When using helmfile for example with helm we will have double templating in place which needs to be double escaped and this is crazy.
