### ISSUE TITLE
Source TCP Socket: thread 'vector-worker' panicked

### ISSUE THREAD

**Issue by arch-xtof** [vectordotdev/vector#16794] opened 2023-03-14 12:50 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

**Problem**
vector-worker panics when establishing a TCP session if it does not have at least 2 vCPU cores.

**Expectation**
This does not happen

**Further information**
If required I can provide Kubernetes manifest to reproduce this issue

### Configuration

```text
[sources.gelf_tcp]
      type = "socket"
      address = "0.0.0.0:8122"
      mode = "tcp"
      framing.method = "newline_delimited"
      framing.newline_delimited.max_length = 16000
```

### Version

0.28.1-distroless-libc

### Debug Output

```text
2023-03-14T12:37:06.086207Z DEBUG source{component_kind="source" component_id=gelf_tcp component_type=socket component_name=gelf_tcp}:connection{peer_addr=127.0.0.1:42538}: vector::sources::util::net::tcp: Accepted a new connection. peer_addr=127.0.0.1:42538
thread 'vector-worker' panicked at 'assertion failed: min <= max', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/cmp.rs:860:9
stack backtrace:
   0:     0x55d6493bc12e - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d6493bc12e - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d6493bc12e - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55d6493bc12e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d648a3efee - core::fmt::write::h062c617411b691df
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:     0x55d649387b84 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:     0x55d6493bd47f - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55d6493bd47f - std::sys_common::backtrace::print::hca896ae22beb06cb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55d6493bcf7d - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:     0x55d6493be236 - std::panicking::default_hook::h8932b573145a321b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:     0x55d6493be236 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
  11:     0x55d6493bdb93 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:577:13
  12:     0x55d6493bdb2c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55d6493bdb01 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  14:     0x55d64842bd82 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  15:     0x55d64842be7c - core::panicking::panic::h622b2a38bce78ff3
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:115:5
  16:     0x55d64b7a7146 - core::ptr::drop_in_place<vector::sources::util::net::tcp::request_limiter::RequestLimiterPermit>::h01878bcfbbfae14c
  17:     0x55d64bda686b - vector::sources::util::net::tcp::handle_stream::{{closure}}::h656f69dd94a5d36f
  18:     0x55d64bda2bfb - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h272386960f4324ed
  19:     0x55d64bda13aa - tokio::runtime::task::raw::poll::h4372d3e0a9adc932
  20:     0x55d649400142 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h33539002602b1525
  21:     0x55d649407725 - tokio::runtime::task::raw::poll::h64182bd6a085124b
  22:     0x55d6493e9fb9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h20578a280d0b76ec
  23:     0x55d6493e9c3d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdff6c2a300b2b036
  24:     0x55d6493c0673 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6202d10b0224e7b0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  25:     0x55d6493c0673 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4dbea73c9cec160b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  26:     0x55d6493c0673 - std::sys::unix::thread::Thread::new::thread_start::h0a2f4c32ba2f2278
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f96b174afa3 - start_thread
  28:     0x7f96b14f1eff - clone
  29:                0x0 - <unknown>
```

### Additional Context

Vector is running inside of a Kubernetes pod. This pod has another container that wants to open a TCP session with Vector.

### References

* #16273
* #16103

**Comment by fuchsnj** [comment] 2023-03-14 13:21
This seems to be a duplicate of the issue you linked (https://github.com/vectordotdev/vector/issues/16273).
I'm closing this one, but thanks for the additional information / context.

**Closed** 2023-03-14 13:22 UTC
Labels: type: bug
