### ISSUE TITLE
certificate verify failed when sources is kubernetes_logs with self-signed certificate

### ISSUE THREAD

**Issue by kingqtl** [vectordotdev/vector#19555] opened 2024-01-09 02:26 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kingqtl** [comment] 2024-01-09 02:27
WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(HyperError(hyper::Error(Connect, ConnectError { error: Error { code: ErrorCode(1), cause: │
│  Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "(unknown function)", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1890 }]))) }, verify_result: X509VerifyRe │
│ sult { code: 18, error: "self-signed certificate" } })))                                                                                                                                                                       │
│ 2024-01-09T02:27:32.502540Z ERROR kube_client::client::builder: failed with error error trying to connect: error:0A000086:SSL routines:(unknown function):certificate verify failed:ssl/statem/statem_clnt.c:1890:: self-signe │
│ d certificate                                                                                                                                                                                                                  │
│ 2024-01-09T02:27:32.502578Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(HyperError(hyper::Error(Connect, ConnectError { error: Error { code: ErrorCode(1), cause: │
│  Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "(unknown function)", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1890 }]))) }, verify_result: X509VerifyRe │
│ sult { code: 18, error: "self-signed certificate" } })))                                                                                                                                                                       │
│ 2024-01-09T02:27:32.616088Z ERROR kube_client::client::builder: failed with error error trying to connect: error:0A000086:SSL routines:(unknown function):certificate verify failed:ssl/statem/statem_clnt.c:1890:: self-signe │
│ d certificate                                                                                                                                                                                                                  │
│ 2024-01-09T02:27:32.616121Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(HyperError(hyper::Error(Connect, ConnectError { error: Error { code: ErrorCode(1), cause: │
│  Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "(unknown function)", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1890 }]))) }, verify_result: X509VerifyRe │
│ sult { code: 18, error: "self-signed certificate" } })))

**Comment by jszwedko** [comment] 2024-01-09 14:45
Hi @kingqtl ! This appears to be a duplicate of https://github.com/vectordotdev/vector/issues/19224. I see you already found that other issue.

**Closed by jszwedko** 2024-01-09 14:45 UTC
Labels: type: feature
