### ISSUE TITLE
Enable the benchmarking check to fail

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6470] opened 2021-02-17 15:26 UTC
See https://github.com/timberio/vector/pull/6442#issuecomment-779857238

**Comment by jszwedko** [comment] 2021-03-05 21:50
Maybe post as a comment?

**Comment by jszwedko** [comment] 2022-12-28 17:08
Closing since the regression test suite does currently block CI.

**Closed by jszwedko** 2022-12-28 17:08 UTC
Labels: type: task, domain: ci, domain: performance
