### ISSUE TITLE
Adding a websocket source

### ISSUE THREAD

**Issue by sunng87** [vectordotdev/vector#21335] opened 2024-09-22 21:17 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We have a scenario that users are using websocket for metrics transport. After looking into vector's sources/sinks, I found there is websocket sink but no source.

### Proposal

Because websocket is mostly message based, so the source will start a websocket server and listen to client to send messages. We will also need to support decoding on those messages.

**Comment by jszwedko** [comment] 2024-09-23 17:39
Hi! I think this is a duplicate of https://github.com/vectordotdev/vector/issues/6491. Feel free to follow along on that other issue.

**Closed by jszwedko** 2024-09-23 17:39 UTC
Labels: type: feature
