### ISSUE TITLE
Apple M2 installation from script failed - vector: unsupported arch: aarch64-apple-darwin

### ISSUE THREAD

**Issue by buzzdan** [vectordotdev/vector#17405] opened 2023-05-16 08:52 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

trying to install Vector by using the script on my new Apple M2 didnt work:

```shell
❯ curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash
                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via a pre-built archive at https://packages.timber.io/vector/0.29.1/
>>> Ready to proceed? (y/n)

>>> y

--------------------------------------------------------------------------------

vector: unsupported arch: aarch64-apple-darwin
```

i ended up installing vector via [Homebrew](https://vector.dev/docs/setup/installation/package-managers/homebrew/) 

### Version

vector 0.29.1 (x86_64-apple-darwin 74ae15e 2023-04-20 14:50:42.739094536)

### Additional Context

MacBook Pro 14-inch, 2023
Apple M2 Max
32 GB
MacOS Ventura 13.3.1 (a) (22E772610a)

**Comment by spencergilbert** [comment] 2023-05-16 13:48
👋 closing as a duplicate of https://github.com/vectordotdev/vector/issues/10193, once release builds are created the install script should work as well.

**Closed by spencergilbert** 2023-05-16 13:48 UTC
Labels: type: bug
