### ISSUE TITLE
Wrong evaluation of `if false ... else if true .. else if true`

### ISSUE THREAD

**Issue by ypid-geberit** [vectordotdev/vector#9360] opened 2021-09-28 17:42 UTC
### Vector Version

```
vector 0.17.0 (x86_64-unknown-linux-gnu 3f225b7 2021-09-28)
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Vector Configuration File

This unit test should pass:

```toml
[transforms.remap_if_else_else_with_last_two_true]
  inputs = []
  type = "remap"
  source = """
    if false {
      .branch_1 = true
    } else if true {
      .branch_2 = true
    } else if true {
      .branch_3 = true
    }
  """

[[tests]]
  name = "remap_if_else_else_with_last_two_true"
  [tests.input]
    insert_at = "remap_if_else_else_with_last_two_true"
    type = "log"
    [tests.input.log_fields]
      foo = true
  [[tests.outputs]]
    extract_from = "remap_if_else_else_with_last_two_true"
    [[tests.outputs.conditions]]
      type = "vrl"
      source = "!exists(.branch_1) && .branch_2 == true && !exists(.branch_3)"
```

### Expected Behavior

See unit test.

### Actual Behavior

The last if condition branch is executed.

```
Running tests
test remap_if_else_else_with_last_two_true ... failed

failures:

test remap_if_else_else_with_last_two_true:

check transform 'remap_if_else_else_with_last_two_true' failed conditions:
  condition[0]: source execution resolved to false
payloads (events encoded as JSON):
   input: {"foo":true,"message":"","timestamp":"2021-09-28T17:39:37.326373283Z"}
  output: {"branch_3":true,"foo":true,"message":"","timestamp":"2021-09-28T17:39:37.326373283Z"}
```

### Example Data

See unit test.

**Comment by jszwedko** [comment] 2021-09-28 17:45
Hmm, yeah, that's definitely not right. Thanks for reporting this @ypid-geberit .

@StephenWakely or @JeanMertz is this something you could take a look at? It'd be nice to get a fix in the next release next week.

**Comment by StephenWakely** [comment] 2021-09-28 19:49
This is a dupe of #8284.

**Comment by jszwedko** [comment] 2021-09-28 19:50
Ah, and so it is. I'll close this in-lieu of that one.

**Closed by jszwedko** 2021-09-28 19:50 UTC
Labels: type: bug, domain: vrl
