### ISSUE TITLE
`statsd` sink should properly normalize metrics

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#9985] opened 2021-11-10 15:58 UTC
Cumulative metrics (ex: counters) are expected to be sent to `statsd` as incremental, and reset on each sent. These are not being normalized for `statsd`, and are being sent as absolute/cumulative values instead.

AWS Cloudwatch is an example of a sink that is normalizing metrics: https://github.com/vectordotdev/vector/blob/c1d9c727e9d584ca22ecf2d51b8e0908ef20f0c7/src/sinks/aws_cloudwatch_metrics.rs

The expected behavior for different metrics types are:

|metric | normalization|
----------|-----------------------
|counters|incremental|
| gauges| absolute |
|sets|incremental|
|distributions|incremental|

**Comment by jszwedko** [comment] 2021-11-10 16:40
@fuchsnj I think this is actually a duplicate of #9718

**Closed** 2021-11-10 16:55 UTC
Labels: type: bug, sink: statsd, domain: metrics
