### ISSUE TITLE
`throttle` transform

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7409] opened 2021-05-11 20:24 UTC
Requested by user in discord: https://discord.com/channels/742820443487993987/746070604192415834/841751555426484306

They'd like to throttle messages based on a key. This is related to, but different then, sampling. It is possible that we could support both in one transform where it would throttle and then either sample or drop when the rate is exceeded.

Prior art: https://docs.fluentbit.io/manual/pipeline/filters/throttle

**Comment by mrmassis** [comment] 2021-05-11 23:20
Tkz for your time and support. This is very important in environment multi-tenant. I alread use this approach with fluentd in logs context, and it will be very welcome in metrics context.

**Comment by spencergilbert** [comment] 2021-09-20 17:05
Duplicate of https://github.com/vectordotdev/vector/issues/258

**Closed by spencergilbert** 2021-09-20 17:05 UTC
Labels: domain: transforms, type: feature
