### ISSUE TITLE
FIPS compliance

### ISSUE THREAD

**Issue by elibramson** [vectordotdev/vector#18230] opened 2023-08-13 09:52 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

We look for a **FIPS-compliant solution** to address specific security concerns and meet regulatory requirements. We can't find anything related to the FIPS compliance in the Vector documentation.  We would like to know if any plan exists to support the FIPS in the future. Or is there a way to customize Vector to make it FIPS-enabled?

**Comment by jszwedko** [comment] 2023-08-14 14:50
Hi @elibogomolnyi ! This looks like a duplicate of https://github.com/vectordotdev/vector/issues/8435 . See also: https://github.com/vectordotdev/vector/issues/16535

**Closed by jszwedko** 2023-08-14 14:50 UTC
