### ISSUE TITLE
Seeing rate limited warnings when using adaptive concurrency with Loki sink.

### ISSUE THREAD

**Issue by sam-mcbr** [vectordotdev/vector#10364] opened 2021-12-08 21:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

### Vector Configuration File

```yaml
vector:
          role: Stateless-Aggregator
          fullnameOverride: {{ .Values.vectorApplicationName}}
          image:
            repository: <repo>
            tag: 0.18.1-debian
          replicas: {{ int .Values.vectorNumReplicas }}
          resources: {{- toYaml .Values.vectorResources | nindent 12 }}
          serviceAccount:
            create: true
            annotations:
# ...
            automountToken: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
          tolerations: []
          podMonitor:
            enabled: true
            port: prometheus
            additionalLabels:
# ...
            metricRelabelings:
              {{- toYaml .Values.vectorMetricRelabelings | nindent 14 }}
          autoscaling:
            enabled: true
            minReplicas: {{ int .Values.vectorNumReplicas }}
            maxReplicas: 15
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 70
          customConfig:
            data_dir: /vector-data-dir
            api:
              enabled: true
              address: 0.0.0.0:8686
              playground: false
            sources:
              internal_metrics:
                type: internal_metrics
              {{- toYaml .Values.vectorSources | nindent 14 }}
            transforms:
# ...
            sinks:
              prometheus:
                type: prometheus
                inputs: [internal_metrics]
                address: 0.0.0.0:9090
              loki:
                type: loki
                inputs: [<from_our_transform>]
                endpoint: <endpoint>
                encoding:
                  codec: json
                batch:
                  max_bytes: 400000
                out_of_order_action: rewrite_timestamp
                labels:
# ...
                remove_label_fields: true
```

### Expected Behavior

On `0.16.0-nightly-2021-07-28`, we were just seeing pod logs like with warnings about rewriting timestamps. We do not configure any loki sink adaptive concurrency options. We upgraded to `0.18.1` and expected to continue seeing those warnings, but not warnings about rate limiting since this should be handled automatically.

### Actual Behavior

On `0.18.1`, we are now seeing additional warning logs about rate limiting the internal logs.

### Example Data

Logs on `0.16.0-nightly-2021-07-28`:
```
2021-12-08T20:30:35.509399Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Received out-of-order event, rewriting timestamp. internal_log_rate_secs=30
```

Logs on `0.18.1`:
```
2021-12-08T20:29:47.938987Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Received out-of-order event, rewriting timestamp. internal_log_rate_secs=30

2021-12-08T20:29:47.939024Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Internal log [Received out-of-order event, rewriting timestamp.] is being rate limited.

2021-12-08T20:30:35.509370Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Internal log [Received out-of-order event, rewriting timestamp.] has been rate limited 2982 times.
```

### Additional Context

[Discord thread.](https://discord.com/channels/742820443487993987/753400475545501836/917858955227717682)

**Comment by spencergilbert** [comment] 2021-12-08 21:18
@jszwedko I think this may be an poorly leveled log message, it's WARN but it's doing what the loki config instructs it to do so?

**Comment by jszwedko** [comment] 2021-12-08 21:26
Hmm, yeah, that's true. I could see dropping this down to `debug`. Especially since we publish a metric about it.

**Comment by spencergilbert** [comment] 2021-12-08 21:27
> Hmm, yeah, that's true. I could see dropping this down to `debug`. Especially since we publish a metric about it.

I think wether or not we should still be seeing out of order events is another matter of course, and we need an option to know if we care (if loki 2.4 is the target)

**Comment by jszwedko** [comment] 2021-12-08 21:29
Agreed, we could allow configuring Vector to not rewrite timestamps at all now per https://github.com/vectordotdev/vector/issues/9223. We should still support the behavior for older Loki versions (for now) though.

**Comment by spencergilbert** [comment] 2021-12-10 20:49
@sam-mcbr is the throughput equal between the versions?

**Comment by sam-mcbr** [comment] 2021-12-13 14:20
@spencergilbert We connected to more regions after the upgrade so throughput should have increased, though I'm not sure by how much. We have an old instance of vector (running on the 0.16.0 chart) that is only connected to one region and we have never seen these warnings on that instance.

**Comment by mehta-ankit** [comment] 2021-12-13 14:28
@spencergilbert Reading Sam's reply above, I was thinking, is it just a case of adaptive rate limiting vector and this log being printed as a WARN because of extra load we now  have (with new regions which coincided with the version upgrade) ?

In that case, is it possible for 1 our of X pods to not work and others to handle the load ? Or will adaptive make the load among pods equal ? 🤔  Wouldn't it also depend on which pod is connecting to which source ? (We have multi region SQS queues) ?

**Comment by spencergilbert** [comment] 2021-12-13 14:32
So those logs are printing because we're seeing more out-of-order logs from the perspective of Loki. I figured this _could_ be from us sending more logs or from increased concurrency (causing more to be out of order).

**Comment by sam-mcbr** [comment] 2021-12-13 15:04
@spencergilbert Just checked and we occasionally get these errors from loki (does not appear to have directly caused this):
```
"level=error ts=2021-12-04T15:34:55.107888641Z caller=flush.go:220 org_id=fake msg=\"failed to flush user\" err=\"SlowDown: Please reduce your request rate.\\n\\tstatus code: 503
```

We are still receiving these intermittently.

**Comment by jszwedko** [comment] 2021-12-13 21:39
> In that case, is it possible for 1 our of X pods to not work and others to handle the load ? Or will adaptive make the load among pods equal ? 🤔 Wouldn't it also depend on which pod is connecting to which source ? (We have multi region SQS queues) ?

Do you have multiple Vector replicas writing to the same Loki streams (same combination of labels)?

**Comment by mehta-ankit** [comment] 2021-12-13 22:17
> > In that case, is it possible for 1 our of X pods to not work and others to handle the load ? Or will adaptive make the load among pods equal ? 🤔 Wouldn't it also depend on which pod is connecting to which source ? (We have multi region SQS queues) ?
> 
> Do you have multiple Vector replicas writing to the same Loki streams (same combination of labels)?

We do have multiple vector replica's (we use an HPA, so we can have 1 to 15 vector pods). They do write to same Loki deployment, but not same stream, coz we use a host label on our logs like this:
```
.vector_host = get_hostname() ?? "unknown"
```
We (as in you and me 😅 ) had a chat on discord a while back and decided to use it when using multiple vectors.

**Comment by jszwedko** [comment] 2021-12-13 23:28
Aha 😄 Yes, good, that should ensure they are writing to different log streams and so won't be conflicting with each other.

Just to take a step back here: the issue is that Vector is rewriting the timestamps for logs because they are viewed to be out-of-order. The log you see in Vector's log output indicates this.

Just out of curiosity, will you be or are you running Loki 2.4? We are working on a change to allow just passing through events without rewriting the timestamp since Loki 2.4 can accept events out-of-order. This could make this issue moot.

**Comment by mehta-ankit** [comment] 2021-12-14 13:38
> Just out of curiosity, will you be or are you running Loki 2.4? We are working on a change to allow just passing through events without rewriting the timestamp since Loki 2.4 can accept events out-of-order. This could make this issue moot.

Yes we have it on our roadmap and are starting work on it today. Last time we tried it we had issues with our deployment. Hopefully it will be easy this time. Also good thing is @sam-mcbr is working on it, so he can report here when we are done and as you said hopefully this issue is moot then.
We ll make sure to check all vector pods are doing work and not sitting idle (which was the original reason we started this thread and issue).

**Comment by sam-mcbr** [comment] 2021-12-15 15:57
After upgrading to Loki 2.4, we are still seeing the rate limiting warnings. I believe this is because we still need the `out_of_order_action: rewrite_timestamp` key in our config (since the only other option is to drop the logs). Once #9223 gets merged I would be happy to update vector and check again.

**Comment by jszwedko** [comment] 2021-12-15 15:59
Great! Thanks for confirming @sam-mcbr . We do aim to get https://github.com/vectordotdev/vector/issues/9223 in shortly.

**Comment by jszwedko** [comment] 2022-02-04 22:52
This is closed by https://github.com/vectordotdev/vector/issues/10401

We do have https://github.com/vectordotdev/vector/issues/9223 tracking forwarding out-of-order writes in Vector.

**Closed by jszwedko** 2022-02-04 22:52 UTC
Labels: type: bug, sink: loki
