### ISSUE TITLE
aws_cloudwatch_logs healthcheck is failing when using a templatized group name

### ISSUE THREAD

**Issue by dambaron** [vectordotdev/vector#18706] opened 2023-09-28 11:02 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using the `aws_cloudwatch_logs` sink the healthcheck is failing if the `group_name` parameter is using a template.

The `DescribeLogGroups` request sent to AWS will end with a `InvalidParameterException`

### Configuration

```text
[sinks.aws_cloudwatch_logs]
type = "aws_cloudwatch_logs"
...
create_missing_group = true
create_missing_stream = true
...
group_name = "/aws/ec2/myService/{{ .session_id }}"
stream_name = "{{ .instance_id }}"
```

### Version

0.32.2

**Comment by jszwedko** [comment] 2023-09-28 13:49
Hi @dambaron ! Thanks for opening this: I think it is a duplicate of https://github.com/vectordotdev/vector/issues/10787.

**Closed by jszwedko** 2023-09-28 13:49 UTC
Labels: type: bug
