### ISSUE TITLE
Add ability to require a default for templated config items

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#1846] opened 2020-02-18 21:20 UTC
In some cases we want the ability to require a default for templates where the render of templates fails. We can right now support this if we have two options where one is the default and it only sets the default if the template render fails. This seems brittle and a bit confusing, I'd rather we find a method to allow someone to specify a default if they set a template.

cc @lukesteensen

**Comment by lukesteensen** [comment] 2020-02-26 02:54
I've encouraged users to handle defaulting logic with a Lua transform in front of the sink, but I agree there's room for improvement here.

I believe we plan on spending some time with templates to add the idea of "filter" a la [Jinja](https://jinja.palletsprojects.com/en/2.11.x/templates/#filters). It'd be nice to leverage one of the existing templating crates for this (e.g. [handlebars](https://github.com/sunng87/handlebars-rust), [liquid](https://github.com/cobalt-org/liquid-rust), [tera](https://github.com/Keats/tera), [templar](https://github.com/proctorlabs/templar), etc).

**Comment by jszwedko** [comment] 2022-08-01 21:25
Duplicate of https://github.com/vectordotdev/vector/issues/2063

**Closed by jszwedko** 2022-08-01 21:25 UTC
Labels: type: enhancement, domain: config, domain: templating
