### ISSUE TITLE
Loki out of order handling no longer needed with recent Loki version

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#11131] opened 2022-02-01 13:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.19.1
```

### Vector Configuration File

```toml
...
```

### Expected Behavior

Loki sink should determine Loki version that can handle out of order records and disable this filter. Eventually there could be third option of `out_of_order_action` which could be `ignore`.

Related Loki issue: https://github.com/grafana/loki/issues/1544 (fixed since 2.4.0)

### Actual Behavior

Vector pro-actively drops events that could be actually handled by recent Loki.

**Comment by fpytloun** [comment] 2022-02-01 13:47
Suggested fix: https://github.com/vectordotdev/vector/pull/11133

**Comment by jszwedko** [comment] 2022-02-01 15:17
@fpytloun thanks for reporting and for the PR! I think this issue is a duplicate of https://github.com/vectordotdev/vector/issues/9223 so I'll close it in-lieu of that.

**Closed by jszwedko** 2022-02-01 15:17 UTC
Labels: type: bug

**Comment by fpytloun** [comment] 2022-02-01 15:19
@jszwedko indeed, thank you for noticing. What about my simple fix, will that work?
