### ISSUE TITLE
Mutually exclusive routing in the `route` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9100] opened 2021-09-09 20:36 UTC
The `route` transform currently routes events to _any_ route that matches. We need a mode that only routes events to the _first_ route that matches, making the routes mutually exclusive.

Related #4644

**Comment by jszwedko** [comment] 2024-07-22 18:20
Closing as a duplicate of https://github.com/vectordotdev/vector/issues/17040 since the latter has more discussion.

**Closed by jszwedko** 2024-07-22 18:20 UTC
Labels: type: enhancement, transform: route
