### ISSUE TITLE
env vars are interpeted inside comments

### ISSUE THREAD

**Issue by buzzdan** [vectordotdev/vector#17851] opened 2023-07-04 06:53 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

i have a comment in my TOML file:
```
#   log_format nginx '$remote_addr - $remote_user [$time_local] '
#                    '"$request" $status $body_bytes_sent $request_time '
#                    '"$http_referer" "$http_user_agent" "$http_x_jrpc_method"';
```

now when i run `vector validate` it warns me with this message:

~ Unknown env var in config. name = "remote_addr"
~ Unknown env var in config. name = "remote_user"
~ Unknown env var in config. name = "time_local"
~ Unknown env var in config. name = "request"
~ Unknown env var in config. name = "status"
~ Unknown env var in config. name = "body_bytes_sent"
~ Unknown env var in config. name = "request_time"
~ Unknown env var in config. name = "http_referer"
~ Unknown env var in config. name = "http_user_agent"
~ Unknown env var in config. name = "http_x_jrpc_method"

when i remove the comment `vector validate` runs smoothly

### Configuration

```text
### Sources ###
[sources.nginx_stdout_log]
type = "file"
include = ["/path/to/vector/project/**/nginx-stdout.log"]

### Transforms ###

# nginx costum log format. taken from: /path/to/another/project/nginx.conf.mustache
#   log_format nginx '$remote_addr - $remote_user [$time_local] '
#                    '"$request" $status $body_bytes_sent $request_time '
#                    '"$http_referer" "$http_user_agent" "$http_x_jrpc_method"';
[transforms.nginx_stdout_parser]
inputs = ["nginx_stdout_log"]
type = "remap"
source = '''
    structured = parse_regex!(.message, r'^(?P<remote_addr>[^ ]+) - (?P<remote_user>[^ ]+) \[(?P<time_local>[^\]]+)\] "(?P<request>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) (?P<request_time>\S+) "(?P<http_referer>[^"]+)" "(?P<http_user_agent>[^"]+)" "(?P<http_x_jrpc_method>[^"]+)"$')
    . = merge(., structured)
'''

[transforms.nginx_stdout_remap]
inputs = ["extract_container_name"]
type = "remap"
source = '''

    .timestamp = parse_timestamp!(.time_local, "%d/%b/%Y:%T %z")
    del(.time_local)

    .http_status = parse_int!(.status)
    del(.status)


    .request_time = to_float!(.request_time)

'''
```

### Version

vector 0.30.0 (x86_64-apple-darwin 38c3f0b 2023-05-22 17:38:48.655488673)

### Debug Output

```text
❯ RUST_BACKTRACE=full vector -vvv validate --config-dir $(pwd)/common --config-dir $(pwd)/configs --no-environment
2023-07-04T06:48:06.983264Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-07-04T06:48:06.984376Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
Loaded with warnings ["/path/to/vector/project/common", "/path/to/vector/project/configs"]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ Unknown env var in config. name = "remote_addr"
~ Unknown env var in config. name = "remote_user"
~ Unknown env var in config. name = "time_local"
~ Unknown env var in config. name = "request"
~ Unknown env var in config. name = "status"
~ Unknown env var in config. name = "body_bytes_sent"
~ Unknown env var in config. name = "request_time"
~ Unknown env var in config. name = "http_referer"
~ Unknown env var in config. name = "http_user_agent"
~ Unknown env var in config. name = "http_x_jrpc_method"

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                           Validated
```

### Example Data

201.69.207.46 - - [31/May/2023:13:42:24 +0300] "POST /api/v1 HTTP/1.0" 200 56 0.004 "-" "-" "host_form"

**Comment by spencergilbert** [comment] 2023-07-05 15:16
Duplicate of https://github.com/vectordotdev/vector/issues/797

**Closed by spencergilbert** 2023-07-05 15:16 UTC
Labels: domain: config
