### ISSUE TITLE
Enabling disk buffers also caused back pressure to the edge

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#15900] opened 2023-01-11 08:52 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I've tried to enable Vector aggregator's blackhole disk with disk buffers but it poses an unexpected behavior: Whenever there are container logs generated, Vector Agent's buffer at Vector sink had a lot of events in buffer, even when disk buffer at Vector aggregator's blackhole sink isn't full yet. In contrast, when Vector aggregator's blackhole sink uses memory buffers this behavior didn't show up.

If I understand correctly, it means Vector aggregator applied back pressure to the edge (Vector agent's Vector sink in this case), but it should do this _only_ when Vector aggregator's disk buffer is full and `buffer.when_full` is block. My expectation with disk buffers would be fast and _not_ causing back pressure to the edge like this

### Configuration

```text
Development system:
- GKE v1.24
- node specs: t2d-standard-8 (8 CPUs, 32GB memory)
- persistent volume: 100GiB pd-ssd

Vector Helm chart values

<details>
<summary>Vector Agent configs</summary>


customConfig:
  data_dir: "/vector-data-dir"
  expire_metrics_secs: 3600
  api:
    enabled: true
    address: 0.0.0.0:8686
    playground: false
  sources:
    kubernetes:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 3600000  # value in millis => 1 hour
      glob_minimum_cooldown_ms: 2000  # value in millis

  sinks:
    vector-aggregator:
      type: vector
      acknowledgements:
        enabled: false
      compression: false
      buffer:
        max_events: 100000
      inputs:
        - kubernetes
      address: vector-aggregator.vector.svc.cluster.local:9088

</details>

<details>
<summary>Vector aggregator configs</summary>

```yaml
persistence:
  enabled: true
  size: "100Gi"

customConfig:
  data_dir: "/vector-data-dir"
  api:
    enabled: true
    address: 0.0.0.0:8686
    playground: false
  timezone: Etc/UTC
  sources:
    kubernetes_v2:
      type: vector
      address: 0.0.0.0:9088

  sinks:
    blackhole:
      type: blackhole
      inputs:
        - kubernetes_v2
      acknowledgements:
        enabled: false
      buffer:
        type: disk
        max_size: 80000000000 # 80GB
        when_full: drop_newest
      rate: 100000
      print_interval_secs: 0
```
</details>

Create a k8s job to generate random logs:
<details>
<summary>Dummy logs job</summary>

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-logs-json
  labels:
    component: test
spec:
  parallelism: 3
  backoffLimit: 1
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        name: dummy-logs-json
    spec:
      containers:
      - name: flog
        image: mingrammer/flog
        imagePullPolicy: IfNotPresent
        command:
        - flog
        - -f
        - json
        - -b
        - "524288000"
        - -s
        - "300ms"
      restartPolicy: Never
```
</details>
```


### Version

0.24.2

### Debug Output

_No response_

### Example Data

Prometheus metrics: ```sum(vector_buffer_events) by (pod)``` 
<img width="1596" alt="Screenshot 2023-01-11 at 08 27 41" src="https://user-images.githubusercontent.com/46129063/211757794-39114c60-afc5-4e5d-9bc8-d18a4bbf1e53.png">

Vector events out metrics: ```sum(rate(vector_component_sent_events_total{component_kind="sink", }[$__rate_interval])) by (component_id)```
<img width="1596" alt="Screenshot 2023-01-11 at 08 27 09" src="https://user-images.githubusercontent.com/46129063/211758157-37f04cc9-2672-4cc8-89d1-ee6be537920f.png">

Vector persistent volume metrics:
<img width="1597" alt="Screenshot 2023-01-11 at 08 26 31" src="https://user-images.githubusercontent.com/46129063/211758426-8d07155f-708d-4755-8f1b-94a61c2f0b5c.png">

Persistent volume IOPS:
<img width="1589" alt="Screenshot 2023-01-11 at 08 50 52" src="https://user-images.githubusercontent.com/46129063/211760810-8bf65b78-a0b2-4364-8101-a057de2d448d.png">


### Additional Context

Topology:

```
[Kubernetes logs] -> [Vector Agent] ----> [Vector Aggregator] -> [Blackhole]
```

### References

_No response_

**Comment by spencergilbert** [comment] 2023-01-11 16:37
Hey @namm2, I'm curious if you see the same behavior if you remove the `rate` configuration from the `blackhole` sink you've configured. Would you mind testing that?

**Comment by namm2** [comment] 2023-01-12 03:25
@spencergilbert I tried without the rate config in blackhole sink but it didn't have any effect. Also I tried with a HTTP sink (nginx server that responds 200 to any requests) but had the same behavior.

**Comment by namm2** [comment] 2023-01-12 05:01
I tried with global `acknowledgements.enabled: true` on both Vector agent and aggregator, and it did reduce the buffered events in Vector agent:

<img width="1598" alt="Screenshot 2023-01-12 at 04 49 09" src="https://user-images.githubusercontent.com/46129063/211979962-d291132d-9f48-4953-8cc2-4f9e43cddc47.png">

With acknowledments enabled, number of received (read) kubernetes events on the right graphs look sub-par with the number of aggregator's received events:

<img width="1597" alt="Screenshot 2023-01-12 at 04 51 13" src="https://user-images.githubusercontent.com/46129063/211980054-2c1ebf62-6a9b-48bc-aea7-565709a52671.png">

I assume Vector agent waited the ack receipt before reading new logs, is it correct? Then it will cause another unwanted effect in the real system where container logs were rotated really fast and Vector agent would miss many logs.

**Comment by spencergilbert** [comment] 2023-01-12 20:41
> I assume Vector agent waited the ack receipt before reading new logs, is it correct? Then it will cause another unwanted effect in the real system where container logs were rotated really fast and Vector agent would miss many logs.

Vector will continue to read new logs, but hold the handle for the existing file - so it should still capture new events coming in.

Along with `vector_buffer_events` could you graph `vector_buffer_received_events_total - vector_buffer_sent_events_total` and share that?

**Comment by namm2** [comment] 2023-01-13 06:08
> Along with `vector_buffer_events` could you graph `vector_buffer_received_events_total - vector_buffer_sent_events_total` and share that?

I tried differently with logs generator (with delays) to slowly ramp up generated events. But still similar behavior with disk buffers:

<img width="1596" alt="Screenshot 2023-01-13 at 06 05 50" src="https://user-images.githubusercontent.com/46129063/212249272-4436c12b-eeb9-466c-805d-0476ff3cec8c.png">


<img width="1597" alt="Screenshot 2023-01-13 at 06 04 39" src="https://user-images.githubusercontent.com/46129063/212249255-a3281399-0cad-4118-b113-2aa7f1e2fc71.png">

**Comment by tobz** [comment] 2023-01-13 21:13
So, reviewing your configurations and all of the data you provided -- thank you for that, by the way! -- I would say that this is performing as we/I would expect.

In general, disk buffering is slower than in-memory buffering. There's really no way around that, as we're talking about having to perform disk I/O, including not only writing to disk but also synchronizing the data to disk via `fsync`. This will already impose a throughput reduction compared to in-memory buffers.

However, in your case, your disk buffers never actually fill up. Without the buffers filling up, the `when_full` logic is never triggered. That's why there's no inflection point where the aggregator magically gets faster because it's able to more quickly process events by simply dropping them. However, what _is_ apparent from the graphs is that you're consuming 100% of the available throughput for your persistent disk. Looking at [the PD-SSD performance documentation](https://cloud.google.com/compute/docs/disks/performance), we can see that the highest throughput we can possibly expect from a PD-SSD is ~0.5MB/s/GB. With your 100GiB PD-SSD, this would be 50MB/s, which lines up almost exactly with your throughput graphs.

Given that there's no reason for events to be dropped, and so we know they all are being pushed through the disk buffer, and given that we can see that you're likely hitting the physical throughput limits of the disk, I would conclude that the backpressure behavior you're seeing when disk buffers are enabled is normal and to be expected.

**Comment by fuchsnj** [comment] 2023-03-09 20:16
Closing since this seems to be expected behavior. Please re-open / comment if you would like to continue the discussion.

**Closed by fuchsnj** 2023-03-09 20:16 UTC
Labels: domain: buffers
