### ISSUE TITLE
Vector command sink

### ISSUE THREAD

**Issue by Joshualy94** [vectordotdev/vector#20189] opened 2024-03-27 05:15 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Is there a way we can let vector run specific command as sink?
For example, I want to run curl to send http post request. (vector http sink would wrap payload in array, which is a problem for me)

**Comment by jszwedko** [comment] 2024-03-27 13:49
Hey @Joshualy94 ! Thanks for opening this. I think it is a duplicate of https://github.com/vectordotdev/vector/issues/935 so I'll close this one, but feel free to add any thoughts on the other. I agree this would be nice-to-have.

**Closed by jszwedko** 2024-03-27 13:49 UTC
Labels: type: feature
