### ISSUE TITLE
YAML Merges are not support in Config

### ISSUE THREAD

**Issue by lattwood** [vectordotdev/vector#21729] opened 2024-11-07 17:35 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

YAML configuration parsing doesn't support merging, part of the YAML 1.1 > spec.

This is due to not calling `serde_yaml::apply_merge` after `serde_yaml::from_str`.

I'm opening this issue due to `CONTRIBUTING.md` saying there should be an issue for pull requests.

### Configuration

```text
transforms:
  enhance_node_exporter_data: &enrichRemap
    type: remap
    inputs:
    - node_exporter
    source: |-
      .tags.country = "meta.country"
    enhance_statsd_metrics_data:
      <<: *enrichRemap
      inputs:
      - statsd_metrics
```
```


### Version

0.43.0-custom-e2b83f219

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by pront** [comment] 2024-11-07 17:46
Thank you @lattwood! We will review the PR shortly.

**Comment by lattwood** [comment] 2024-11-07 17:50
@pront awesome! Can't wait for a release with it so I can dry up my vector config!

**Comment by jszwedko** [comment] 2024-11-07 17:52
I think this is a duplicate of https://github.com/vectordotdev/vector/issues/20853 so I'll close this one, but thank you for the PR to address it!

**Closed by jszwedko** 2024-11-07 17:52 UTC
Labels: type: bug, domain: config

**Comment by lattwood** [comment] 2024-11-07 17:54
Even better, solving a problem others are currently experiencing!
