### ISSUE TITLE
Add field names as parameter to parse_csv remap function

### ISSUE THREAD

**Issue by alexeynl** [vectordotdev/vector#22052] opened 2024-12-18 10:50 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I have csv formatted events with constant set of fields:

value1,value2,value3

and disctict constant array with field names:

[field_name1,field_name2,field_name3]

The resulting parsed event must be:
{
  "field_name1": "value1",
  "field_name2": "value2",
  "field_name3": "value3"
}

[PaloAlto events](https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions) is the real use case.

### Attempted Solutions

Tried parse_csv for event like
value1,value2,value3
got me array as result
["value1","value2","value3"]

### Proposal

Add array of field names as input parameter for parse_csv function and output object like this:

{
  "field_name1": "value1",
  "field_name2": "value2",
  "field_name3": "value3"
}

**Comment by jszwedko** [comment] 2024-12-18 15:52
Thanks for filing this @alexeynl . I think it is a duplicate of https://github.com/vectordotdev/vrl/issues/130 so I'll close this one, but feel free to follow the other issue for updates.

**Closed by jszwedko** 2024-12-18 15:52 UTC
Labels: type: feature
