### ISSUE TITLE
[sink] clickhouse support native protocol & more metrics

### ISSUE THREAD

**Issue by caibirdme** [vectordotdev/vector#13701] opened 2022-07-25 08:02 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

clickhouse sink now is using http + jsoneachrow format to insert data, but that's inefficient. We tested inserting 200_000 lines data into clickhouse in one request. When using tcp + native protocol, it costs around 5s, while http+jsoneachrow costs over 30s. And the CPU is much slower when using tcp+native protocol.
Since clickhouse has the trend to become the main backend for storing log data in the future, it's important to improve the write performance.

And before swtiching to tcp + native protocol, I suggest that we can add more metrics data to observe the insert performance:
* histogram: remote_write_request_duration_seconds

### Proposal

1. add metrics
2. switching to tcp+native protocol, [clickhouse-rs](https://github.com/suharev7/clickhouse-rs) might be a quick choice 

### Version

v0.23.0

**Comment by spencergilbert** [comment] 2022-07-25 13:43
Noting that I think we should already request duration metrics from the sink in the form of `adaptive_concurrency_observed_rtt`?

**Comment by caibirdme** [comment] 2022-07-26 01:42
> Noting that I think we should already request duration metrics from the sink in the form of `adaptive_concurrency_observed_rtt`?

Don't find this metric in [official docs](https://vector.dev/docs/reference/configuration/sinks/clickhouse/#telemetry)

**Comment by spencergilbert** [comment] 2022-07-26 13:03
Any sink that uses ARC should emit that metric, it may be a doc error.

**Comment by jszwedko** [comment] 2022-07-26 18:53
Hi @caibirdme !

I think this is a duplicate of https://github.com/vectordotdev/vector/issues/9000 . I'll close this one, but feel free to follow along there or add any additional thoughts. It is good to have the additional motivation you listed above around performance.

**Closed by jszwedko** 2022-07-26 18:53 UTC
Labels: sink: clickhouse

**Comment by bin** [comment] 2022-08-03 18:41
@jszwedko I think this isn't a duplicate w.r.t adding metrics support, as #9000 doesn't mention that.

**Comment by jszwedko** [comment] 2022-08-03 19:22
> @jszwedko I think this isn't a duplicate w.r.t adding metrics support, as #9000 doesn't mention that.

We already publish request metrics for the HTTP requests made to Clickhouse. Agreed that we would want similar request metrics if/when we add support for the raw TCP interface though. I added that note over on #9000 as https://github.com/vectordotdev/vector/issues/9000#issuecomment-1204378954
