### ISSUE TITLE
Add VRL function to calculate SHA-256 HMAC

### ISSUE THREAD

**Issue by sbalmos** [vectordotdev/vector#15325] opened 2022-11-22 22:08 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Most HTTP webhooks nowadays advise to authenticate the event came from a valid server by calculating a SHA-256 HMAC and comparing against a header value. This is in lieu of a Basic authentication user-pass or IP whitelisting.

### Attempted Solutions

It doesn't look like VRL has a function to calculate a SHA-256 HMAC given a string and secret key. sha1/2/3() nor encrypt() seem to apply.

### Proposal

Add a hmac_sha256(body: string, key: string): bytes function, which would then typically be fed into encode_base64(). Or have the output of hmac_sha256() be in Base64 format already.

### Version

0.25.1

**Comment by AvihaiSam** [comment] 2022-11-23 11:17
it's a duplicate of https://github.com/vectordotdev/vector/issues/10333

I'd really like that feature too!

**Comment by bruceg** [comment] 2022-11-24 19:00
Closing as duplicate of #10333

**Closed by bruceg** 2022-11-24 19:00 UTC
Labels: type: feature
