### ISSUE TITLE
kafka log-end-offset changed when failing on sinking data to elasticsearch

### ISSUE THREAD

**Issue by isaacchn** [vectordotdev/vector#14963] opened 2022-10-26 06:11 UTC
### Problem

My vector pipeline looks like this: `kafka(source)->lua(transform)->remap(transform)->elasticsearch(sink)`. Both the kafka source and  elasticsearch sink configuration were set `acknowledgements.enabled=true`. However, when I set a wrong elasticsearch password to the configuration file on purpose, the application reported error on writing elasticsearch but still commited offset on kafka topic, which I thought should not happen.

Thanks for your help!

### Configuration

```text
---
sources:
  src_kafka:
    type: kafka
    acknowledgements:
      enabled: true
    bootstrap_servers: my-kafka:9092
    auto_offset_reset: beginning
    group_id: vector
    topics:
      - "vector-test"

transforms:
  trans_with_lua:
    type: lua
    inputs:
      - src_kafka
    version: "2"
    hooks:
      process: |-
        function (event, emit)
            ...
        end
        
  trans_with_remap:
    type: remap
    inputs:
      - trans_with_lua
    source: del(.message)

sinks:
  sink_to_elasticsearch:
    type: elasticsearch
    inputs:
      - trans_with_remap
    endpoint: http://my-elasticsearch:9200
    mode: bulk
    bulk:
      index: vector-%Y-%m-%d
    acknowledgements:
      enabled: true
    auth:
      user: elastic
      password: {a-wrong-password}
      strategy: basic
```

### Version

0.24.2-debian (docker)

### Additional Context

vector error output when writing to elasticsearch:

```
2022-10-26T05:51:51.754437Z ERROR sink{component_kind="sink" component_id=sink_to_elasticsearch component_type=elasticsearch component_name=sink_to_elasticsearch}:request{request_id=9}: vector::sinks::util::retries: Not retriable; dropping the request. reason="client-side error, 401 Unauthorized: {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [elastic] for REST request [/_bulk?timeout=60s]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [elastic] for REST request [/_bulk?timeout=60s]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}"
```

**Comment by jszwedko** [comment] 2022-10-26 17:13
Hi @isaacchn !

Yeah, that is a unfortunate gotcha that Vector will consider the data "ack'd" in that scenario. We have an issue to have Vector retry all requests, https://github.com/vectordotdev/vector/issues/10870, that will avoid this. I'll close this one as a duplicate of that issue, but please leave any additional feedback you have there.

**Closed by jszwedko** 2022-10-26 17:13 UTC
Labels: type: bug
