### ISSUE TITLE
syslog source unwrap error

### ISSUE THREAD

**Issue by davidhuie-dd** [vectordotdev/vector#16103] opened 2023-01-24 17:45 UTC
### Discussed in https://github.com/vectordotdev/vector/discussions/16095

<div type='discussions-op-text'>

<sup>Originally posted by **muneesMohammed** January 24, 2023</sup>
While running vector in Kubernetes, everything went smoothly, but a few days later, it began to report these errors, and I had no idea what they were. If anyone can help, that would be deeply appreciated.
 
source{component_kind="source" component_id=syslog component_type=syslog component_name=syslog}: vector::source thread 'vector-worker' panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace thread 'vector-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }'</div>

**Comment by jszwedko** [comment] 2023-02-01 19:21
Closing this due to lack of sufficient context to reproduce, but feel free to re-open this @muneesMohammed, if you are able to provide the context. I think it'd be best as a [new bug report](https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+bug&template=bug.yml).

**Closed by jszwedko** 2023-02-01 19:21 UTC
Labels: type: bug, source: syslog

**Comment by christophemorio** [comment] 2023-02-03 08:18
> Closing this due to lack of sufficient context to reproduce, but feel free to re-open this @muneesMohammed, if you are able to provide the context. I think it'd be best as a [new bug report](https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+bug&template=bug.yml).

Thanks, it's done (#16273)
