### ISSUE TITLE
Add response latency metrics for HTTP-based sources

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#9692] opened 2021-10-19 01:12 UTC
When Vector is configured to ingest data via an HTTP-based source, the amount of time it takes to process each request can be a very valuable signal to operators. Increasing latency can be a direct indication of backpressure propagating from elsewhere in the system, and of the overall Vector node being saturated.

**Comment by jszwedko** [comment] 2021-10-19 01:16
I think this is a duplicate of https://github.com/vectordotdev/vector/issues/9520

**Closed** 2021-10-19 01:26 UTC
Labels: type: enhancement, domain: observability, domain: sources, source: splunk_hec
