### ISSUE TITLE
Panic when new config file found in watched dir

### ISSUE THREAD

**Issue by jorgebay** [vectordotdev/vector#12273] opened 2022-04-19 09:47 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

After starting vector with `--config-dir` and `-w` options, when a new valid config file is added to the directory `vector` panics.

### Steps to reproduce

Create a directory with a config file in it:

```bash
mkdir sample_config

cat > sample_config/vector1.toml <<EOF
> [sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 1

[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

[sinks.print]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"
> EOF
```

Start vector

```bash
./bin/vector --config-dir ./sample_config -w
```

In another shell, create another valid vector config:

```bash
cat > sample_config/vector2.toml <<EOF
> [sources.dummy_logs2]
type = "demo_logs"
format = "syslog"
interval = 1

[transforms.parse_logs2]
type = "remap"
inputs = ["dummy_logs2"]
source = '''
. = parse_syslog!(string!(.message))
'''

[sinks.print2]
type = "console"
inputs = ["parse_logs2"]
encoding.codec = "text"

> EOF
```

and the process crashes: 

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/topology/running.rs:646:14
```

Note that starting the process will work with the 2 files being considered.

### Version

0.21.0

### Debug Output

```text
2022-04-19T09:35:38.604374Z  INFO vector::config::watcher: Configuration file changed.
2022-04-19T09:35:38.606928Z  INFO vector::topology::running: Reloading running topology with new configuration.
2022-04-19T09:35:38.609098Z  INFO vector::topology::running: Running healthchecks.
2022-04-19T09:35:38.609176Z  INFO vector::topology::builder: Healthcheck: Passed.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/topology/running.rs:646:14
```
```


### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by spencergilbert** [comment] 2022-04-19 12:02
@lukesteensen likely introduced here https://github.com/vectordotdev/vector/commit/593932149fe40b133c5416b44044c9a6720f5849? If you'd like me to I can bisect down and confirm though.

**Comment by jszwedko** [comment] 2022-04-19 16:22
I actually bisected it down to dac35ef44f46e05443142972608dad7624cf73c1 . I'll see if @tobz can take a look.

**Comment by tobz** [comment] 2022-04-19 18:05
From the configurations provided in the reproduction, it looks like this code is broken insofar as always expecting there to be previous inputs: https://github.com/vectordotdev/vector/commit/dac35ef44f46e05443142972608dad7624cf73c1#diff-bdafd184965fb9c8ceeb9213965a2d5dbe43037d8f5f3501f3d0fb9d11b4cc8fR642-R649

I _think_ it should be as simple as dropping the `.unwrap()`, since `Option<T>` impls `Iterator`, and then adding a `.flatten()` to bring it back to the correct iterator shape.

I'll report back shortly.

**Comment by jszwedko** [comment] 2022-04-20 14:49
Closed by https://github.com/vectordotdev/vector/pull/12290

**Closed by jszwedko** 2022-04-20 14:49 UTC
Labels: type: bug, domain: topology, meta: regression, domain: config, domain: reload

**Comment by jorgebay** [comment] 2022-04-20 15:45
Thanks folks, that's super fast!

**Comment by tobz** [comment] 2022-04-20 15:55
We really hate regressions. 😂
