### ISSUE TITLE
Vector memory leak with in-memory buffer

### ISSUE THREAD

**Issue by valerypetrov** [vectordotdev/vector#9582] opened 2021-10-13 09:32 UTC
Hi there,

We've deployed a vector to our Linux host (centos 7.8). And configured the Kafka as a Source and Minio(S3) as a Sink. We've also set the mem buffer and looks like that there are some issues with memory leakage. Here is the memory usage:

<img width="2234" alt="Screenshot 2021-10-12 at 15 46 44" src="https://user-images.githubusercontent.com/33148246/137106587-b7dabd73-41c7-47b5-9235-1653d762bd10.png">

### Vector version:
```
vector --version
vector 0.16.0 (x86_64-unknown-linux-gnu 9e4174d 2021-08-25)
```

### Vector Configuration File
```
[api]
  enabled = true

[sources.kafka_source_rsyslog-etc]
  type = "kafka"
  bootstrap_servers = ""
  group_id = "s3-vector-001-consumer-group-test"
  topics = ["rsyslog_etc"]
  auto_offset_reset = "earliest"
  [sources.kafka_source_rsyslog-etc.librdkafka_options]
    "fetch.max.bytes" = "102428800"
    "receive.message.max.bytes" = "2147483647"

[transforms.copy_original_message_rsyslog-etc]
  type = "remap"
  inputs = ["kafka_source_rsyslog-etc"]
  source = '''
  .original_message, err = to_string(.message)
  '''

[transforms.json_parser_rsyslog-etc]
  type = "json_parser"
  inputs = ["copy_original_message_rsyslog-etc"]
  drop_field = true
  drop_invalid = true
  field = "message"

[transforms.to_downcase_rsyslog-etc]
  type = "remap"
  inputs = ["json_parser_rsyslog-etc"]
  source = '''
  .component_type, err = downcase(.component_type)
  .log_type, err = downcase(.log_type)
  '''

[transforms.regex_component_rsyslog-etc]
  type = "regex_parser"
  inputs = ["to_downcase_rsyslog-etc"]
  drop_failed = true
  drop_field = false
  field = "component_type"
  patterns = ['^[\w]{3,}$']

[transforms.regex_log_type_rsyslog-etc]
  type = "regex_parser"
  inputs = ["regex_component_rsyslog-etc"]
  drop_failed = true
  drop_field = false
  field = "log_type"
  patterns = ['^[\w.-]{3,}$']

[sinks.output_s3_rsyslog-etc]
  inputs = ["regex_log_type_rsyslog-etc"]
  type = "aws_s3"
  compression = "none"
  endpoint = ""
  bucket = "logs"
  key_prefix   = "kafka/%F/{{ component_type }}/"
  encoding     = "ndjson"
  auth.access_key_id = "logstash"
  auth.secret_access_key = "logstash"
  buffer.when_full = "block"
  buffer.type = "memory"
  buffer.max_events = 5000000
  batch.max_bytes = 52428800
  request.concurrency = "adaptive"


```

During the vector work, it may consume all free memory. Furthermore, I think that there might be an issue with the deletion of the already sent events to the S3 from the in-memory buffer. Because here not really the big difference in processing between modules( I mean the transforms and other modules on config file)

**Comment by jszwedko** [comment] 2021-11-09 22:16
Hi @valerypetrov ! Thanks for this report and apologies for the delayed response. I'm curious if you still see the same behavior on Vector 0.17.3. There were some changes to the `aws_s3` sink in 0.17 that should result in better behavior.

Do you have a rough idea of how many different values you should see for `component_type`? Each batch should be roughly 50 MB. If you had, say, commonly 10000 different values for that field, that would give you roughly 50 GB of memory usage.

I'm also curious what led you to believe that it is the in-memory buffer that is the culprit. Do you see better behavior using the `disk` buffer?

**Comment by valerypetrov** [comment] 2021-11-10 08:49
@jszwedko , hey. The different values in component type are not more than 150-200. 
We've also tried the disk buffer. But it was really slow as a turtle. The overall performance degradation with disk buffer was about 2x times. (we've tested it with fast SSD and checked that the hardware was not the issue)

**Comment by jszwedko** [comment] 2021-11-10 15:42
Hey @valerypetrov !

Gotcha, then yeah, seemingly the batching is not consuming more than 10 GB.

Yeah, the disk buffers do introduce significant overhead since every event has to be written to disk before it is processed. We are currently working on a few improvements there though: rewriting the disk buffer implementation to be Vector specific and thus more performant (we currently leverage leveldb for this which isn't really what it was built for) and adding in the concept of "overflow" buffers to only write events to disk if an in-memory buffer is full.

> I want to say that with a huge in-memory buffer looks like that vector didn't delete the events from memory that were already sent to the s3 sink.

Yeah, that does seem like it could match the symptoms you are seeing, but we haven't seen that isn't a known issue so, if that is the case, it seems likely something specific to the configuration here.

Would you want to try with 0.17.3 just to see if you see the same behavior? As I mentioned that sink was completely rewritten and has better performance characteristics in that version.

If you don't see an improvement, could you provide some example messages and I could try to run your pipeline to see if I can reproduce?

**Comment by valerypetrov** [comment] 2021-11-11 11:13
Hey, @jszwedko .
```
vector --version
vector 0.12.2 (v0.12.2 x86_64-unknown-linux-gnu 2021-03-30)
```
![telegram-cloud-document-2-5217872329580745260](https://user-images.githubusercontent.com/33148246/141288486-986187e9-1e09-4288-8d80-81a7f92e6425.jpg)

```
vector --version
vector 0.17.3 (x86_64-unknown-linux-musl d72c6e7 2021-10-21)
```
![telegram-cloud-document-2-5217872329580745266](https://user-images.githubusercontent.com/33148246/141288518-42070047-5abf-4a14-b5a9-0875e2ed06bf.jpg)

The configuration files were the same. It looks like that vector 0.12.2 is more performant than vector 0.17.3

**Comment by 3JIou-home** [comment] 2021-12-23 02:50
hi, it's situation looks like on my situation 
config
```
[sources.socket_logs]
type = "socket"
address = "127.0.0.1:1234"
max_length = 102400
mode = "udp"
decoding.codec = "syslog"

[transforms.repam_nginx_access_logs]
type = "remap"
inputs = ["socket_logs"]
drop_on_error = true
source = """
  . = parse_json!(.message)
  .remote_addr = ip_subnet!(.remote_addr, "/24")
  del(.remote_port)
  del(.time_iso8601)
"""

[transforms.metrics_nginx_access_logs]
type = "log_to_metric"
inputs = [ "repam_nginx_access_logs" ]

  [[transforms.metrics_nginx_access_logs.metrics]]
  field = "status"
  name = "request_total"
  type = "counter"
  tags.host = "${HOSTNAME}"
  tags.dc = "alakt"
  tags.project = "kolesa"
  tags.type = "strg_frontend"
  tags.job = "vector"
  tags.status = "{{status}}"
  tags.geoip_country_code = "{{ geoip_city_country_code }}"
  tags.geoip_city = "{{ geoip_city }}"

  [[transforms.metrics_nginx_access_logs.metrics]]
  type = "histogram"
  field = "request_time"
  name = "http_response_time_seconds"
  tags.host = "${HOSTNAME}"
  tags.dc = "alakt"
  tags.project = "kolesa"
  tags.type = "strg_frontend"
  tags.job = "vector"
  tags.geoip_country_code = "{{ geoip_city_country_code }}"
  tags.geoip_city = "{{ geoip_city }}"

[transforms.nginx_access_logs_remove_fields]
type = "remove_fields"
inputs = ["repam_nginx_access_logs"]
fields = ["_CMDLINE", "source_type", "_AUDIT_LOGINUID", "_AUDIT_SESSION", "_BOOT_ID", "_CAP_EFFECTIVE", "_EXE", "_MACHINE_ID", "_PID", "_SELINUX_CONTEXT", "_STREAM_ID", "_SYSTEMD_CGROUP", "_SYSTEMD_INVOCATION_ID", "_SYSTEMD_UNIT", "_TRANSPORT", "_UID", "__MONOTONIC_TIMESTAMP", "__REALTIME_TIMESTAMP", "_GID"]

[sources.nginx_error_logs]
type = "file"
include = ["/var/log/nginx/*error.log"]
glob_minimum_cooldown = 10000
max_line_bytes = 102400
file_key = "file"
host_key = "hostname"
max_read_bytes = 20480
ignore_older_secs = 600
start_at_beginning = false

[transforms.repam_nginx_error_logs]
type = "remap"
inputs = ["nginx_error_logs"]
drop_on_error = true
source = """
  . = parse_nginx_log!(.messages, "error")
"""
[sources.internal_vector]
type = "internal_metrics"
scrape_interval_secs = 5

[transforms.add_tags_internal_vector]
type = "add_tags"
inputs = [ "internal_vector" ]
  [transforms.add_tags_internal_vector.tags]
  source = "kolesa-phc2.alakt.kz.prod.bash.kz"

[sinks.loki]
type = "loki"
encoding.codec = "logfmt"
inputs = [ "nginx_access_logs_remove_fields", "repam_nginx_error_logs" ]
batch.timeout_secs = 60
batch.max_events = 1000
buffer.max_events  = 1000
#buffer.type = "disk"
request.concurrency = 10
request.rate_limit_duration_secs = 1
request.rate_limit_num = 10
request.retry_attempts = 1
out_of_order_action = "rewrite_timestamp"
endpoint = "http://loki.kolesa-team.org"
healthcheck.enabled = false
labels.log_type = "vector"
labels.source = "{{ hostname }}"
labels.type = "strg_frontend"
labels.dc = "alakt"
labels.project = "kolesa"
labels.request_method = "{{ request_method }}"
labels.status = "{{ status }}"
labels.server_name = "{{ server_name }}"
labels.geoip_country_code = "{{ geoip_city_country_code }}"
labels.geoip_city = "{{ geoip_city }}"

[sinks.metrics_for_prometheus]
type = "prometheus_exporter"
inputs = [ "metrics_nginx_access_logs", "add_tags_internal_vector" ]
address = "1.2.3.4:9080"
default_namespace = "service"

[api]
enabled = true
address = "127.0.0.1:8686"
```

version:
```ii  vector                               0.18.1```

graphs
buffer in-memory
![vector reserch - buffer in-memory](https://user-images.githubusercontent.com/18260331/147180503-8818d213-4fbe-4319-a09f-488eaae12143.png)
buffer on disk
![vector reserch - buffer on disk](https://user-images.githubusercontent.com/18260331/147180508-140d8bf6-6203-48c1-a5d6-89c9399f9614.png)

**Comment by 3JIou-home** [comment] 2021-12-23 02:55
as u see it's like be between two fires

**Comment by zamazan4ik** [comment] 2022-09-16 17:41
@valerypetrov @3JIou-home Do you still have the issues with Vectors' memory consumption with the latest Vector versions? For us it is kinda important since we are investigating using Vector for our log pipeline.

**Comment by 3JIou-home** [comment] 2022-09-19 02:25
ok, i check and send u results

**Comment by 3JIou-home** [comment] 2022-09-19 03:17
remove_fields - removed? that i can use instead?

**Comment by 3JIou-home** [comment] 2022-09-19 03:22
> remove_fields - removed? that i can use instead?

x unknown variant `remove_fields`, expected one of `aggregate`, `aws_ec2_metadata`, `dedupe`, `filter`, `geoip`, `log_to_metric`, `lua`, `metric_to_log`, `pipeline`, `pipelines`, `reduce`, `remap`, `route`, `sample`, `sampler`, `swimlanes`, `tag_cardinality_limit`, `throttle` for key `transforms.nginx_access_logs_remove_fields`

**Comment by 3JIou-home** [comment] 2022-09-20 03:22
> > > remove_fields - removed? that i can use instead?
> > 
> > 
> > x unknown variant `remove_fields`, expected one of `aggregate`, `aws_ec2_metadata`, `dedupe`, `filter`, `geoip`, `log_to_metric`, `lua`, `metric_to_log`, `pipeline`, `pipelines`, `reduce`, `remap`, `route`, `sample`, `sampler`, `swimlanes`, `tag_cardinality_limit`, `throttle` for key `transforms.nginx_access_logs_remove_fields`
> 
> `remove_fields` was fully removed in `0.24`: https://vector.dev/highlights/2022-08-16-0-24-0-upgrade-guide/#deprecated-transforms

this link help me, and i run test on memory leak

**Comment by 3JIou-home** [comment] 2022-09-20 03:44
> > > > remove_fields - removed? that i can use instead?
> > > 
> > > 
> > > x unknown variant `remove_fields`, expected one of `aggregate`, `aws_ec2_metadata`, `dedupe`, `filter`, `geoip`, `log_to_metric`, `lua`, `metric_to_log`, `pipeline`, `pipelines`, `reduce`, `remap`, `route`, `sample`, `sampler`, `swimlanes`, `tag_cardinality_limit`, `throttle` for key `transforms.nginx_access_logs_remove_fields`
> > 
> > 
> > `remove_fields` was fully removed in `0.24`: https://vector.dev/highlights/2022-08-16-0-24-0-upgrade-guide/#deprecated-transforms
> 
> this link help me, and i run test on memory leak

https://take.ms/KwB0D

looks like use more ram, but stable

**Comment by 3JIou-home** [comment] 2022-09-21 01:53
in my case bug was resolved

**Comment by jszwedko** [comment] 2023-03-29 16:29
Closing since we couldn't reproduce this and it is not clear if it is still an issue with the latest version of Vector which doesn't have some of these deprecated transforms. Please drop a comment here if you are still seeing this behavior.

**Closed by jszwedko** 2023-03-29 16:29 UTC
Labels: type: bug, domain: performance
