### ISSUE TITLE
Limit environment variable injection in pipeline transforms

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#9878] opened 2021-11-03 07:46 UTC
Following the issue https://github.com/vectordotdev/vector/issues/8136, regarding the pipelines transforms and the automatic namespacing, if we follow the scenario where only the admin has access to `/etc/vector/*` and regular user can modify `/etc/vector/path/to/pipeline`, any user will be able to load environment variables and leak them without the admin being able to avoid it.

Possible solution: put in place an "allow list" of the allowed environment variables at the admin level.

**Comment by jszwedko** [comment] 2021-11-04 17:19
I actually think this is more of an enhancement than a bug 😄  It is the expected behavior, but we would like to improve it for the Pipelines use-case.

**Comment by jszwedko** [comment] 2022-12-29 22:50
Closing since this transform was removed for now.

**Closed by jszwedko** 2022-12-29 22:50 UTC
Labels: type: enhancement, transform: pipelines
