### ISSUE TITLE
How to customize a time field currentdate with a value like 2023.04.30, and then reference it in the sink

### ISSUE THREAD

**Issue by uglyliu** [vectordotdev/vector#17251] opened 2023-04-29 16:04 UTC
The architecture is filebeat-->kafka-->vector-->vector. Since es created the index 8 hours late, I want to use the existing function of vector to customize a field to get the date of the day, such as 2023.04.30, Excuse me, has anyone done something similar?

_Originally posted by @uglyliu in https://github.com/vectordotdev/vector/discussions/17250_

**Comment by spencergilbert** [comment] 2023-05-01 13:19
Closing as a duplicate of the duplicate in Discussions.

**Closed by spencergilbert** 2023-05-01 13:19 UTC
