### ISSUE TITLE
Kubernetes: Could not create subdirectory (Read-only filesystem)

### ISSUE THREAD

**Issue by kevinmarrec** [vectordotdev/vector#14593] opened 2022-09-27 09:45 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

![image](https://user-images.githubusercontent.com/25272043/192492124-bd961a21-7ac0-418f-a105-57992ae97798.png)

Screenshot should be self explanatory, Vector is not able to create a subdirectory in `/var/lib/vector` cause of a read-only permission.

 In the Kubernetes Deamonset configuration, it mounts `/var/lib` as read only :
 https://github.com/vectordotdev/vector/blob/88506e819b596a3f69a275fafa2c5b31e3a336d6/distribution/kubernetes/vector-agent/daemonset.yaml#L66-L68
 
 It sounds to always have been the case (in oldest Kubernetes Vector Configuration versions), so I don't know what's wrong, unless the subdirectory creation is a recent change to Vector ?

### Configuration

```text
# vector-agent.toml

[sources.logtail_kubernetes_logs_xxx]
type = "kubernetes_logs"
```

### Version

0.24.1

**Comment by spencergilbert** [comment] 2022-09-27 12:37
Duplicate of: https://github.com/vectordotdev/helm-charts/issues/226

Additionally the `vector-agent` chart has been aggregated. The linked issue should cover all workarounds for the supported chart until we make some adjustments to the default mounts.

**Closed by spencergilbert** 2022-09-27 12:37 UTC
Labels: type: bug

**Comment by kevinmarrec** [comment] 2022-09-27 14:41
@spencergilbert Thanks for pointing me on the right issue !
