### ISSUE TITLE
Vector not processing squid access log (no errors)

### ISSUE THREAD

**Issue by dannylivington** [vectordotdev/vector#20045] opened 2024-03-09 08:43 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have `/var/log/squid/access.log` configured as source, and vector not reading the resource at all (as far as I can tell). vector not showing any error too

```
$ vector validate
√ Loaded ["/etc/vector/vector.yaml"]
√ Component configuration
√ Health check "squid_cloudwatch"
√ Health check "squid_s3"
----------------------------------------
                               Validated
```

An error in the log, or with validate output, would be appreciated to know whats happening here.

### Configuration

```text
sources:
  squid_access_source:
    type: "file"
    include:
      - /var/log/squid/access.log

sinks:
  squid_cloudwatch:
    type: aws_cloudwatch_logs
    inputs:
      - squid_access_source
    compression: none
    create_missing_group: false
    create_missing_stream: true
    group_name: squid-proxy-vector
    region: ap-southeast-2
    stream_name: "{{ host }}"
    encoding:
      codec: "text"
  squid_s3:
    type: "aws_s3"
    inputs:
      - squid_access_source
    bucket: "bucket-test-vector"
    key_prefix: "vector/"
    compression: gzip
    content_encoding: gzip
    content_type: application/gzip
    filename_extension: json.gz
    region: ap-southeast-2
    encoding:
      codec: "json"

api:
  enabled: true
  address: "127.0.0.1:8686"
```

### Version

0.35.0

### Debug Output

```text
systemctl status vector -l
● vector.service - Vector
   Loaded: loaded (/usr/lib/systemd/system/vector.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2024-03-09 08:12:34 UTC; 20min ago
     Docs: https://vector.dev
  Process: 23752 ExecStartPre=/usr/bin/vector validate (code=exited, status=0/SUCCESS)
 Main PID: 23759 (vector)
    Tasks: 6
   Memory: 56.4M
   CGroup: /system.slice/vector.service
           └─23759 /usr/bin/vector

Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.634983Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.yaml"]
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.776888Z  INFO vector::topology::running: Running healthchecks.
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.777068Z  INFO vector: Vector has started. debug="false" version="0.35.0" arch="x86_64" revision="e57c0c0 2024-01-08 14:42:10.103908779"
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.779205Z  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=http://127.0.0.1:8686/playground
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.779410Z  INFO source{component_kind="source" component_id=squid_access_source component_type=file}: vector::sources::file: Starting file server. include=["/var/log/squid/access.log"] exclude=[]
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.781834Z  INFO source{component_kind="source" component_id=squid_access_source component_type=file}:file_server: file_source::checkpointer: Loaded checkpoint data.
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.784676Z  INFO aws_credential_types::cache::lazy_caching: credentials cache miss occurred; retrieved new AWS credentials (took 6.181952ms)
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.786015Z  INFO aws_credential_types::cache::lazy_caching: credentials cache miss occurred; retrieved new AWS credentials (took 6.828861ms)
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.818194Z  INFO vector::topology::builder: Healthcheck passed.
Mar 09 08:12:34 myhost vector[23759]: 2024-03-09T08:12:34.836461Z  INFO vector::topology::builder: Healthcheck passed.
```
```


### Example Data

```
$ cat /var/log/squid/access.log

1709971424.170 logformat=recommended_squid duration=0 src_ip=127.0.0.1 src_port=58204 dest_ip=- dest_port=- user_ident="-" user="-" local_time=[09/Mar/2024:08:03:44 +0000] http_method=GET request_method_from_client=GET request_method_to_server=- url="/" http_referrer="-" http_user_agent="-" status=400 vendor_action=NONE dest_status=HIER_NONE total_time_milliseconds=- http_content_type="text/html" bytes=3925 bytes_in=78 bytes_out=3847 sni="-"
1709971458.008 logformat=recommended_squid duration=0 src_ip=127.0.0.1 src_port=58218 dest_ip=- dest_port=- user_ident="-" user="-" local_time=[09/Mar/2024:08:04:18 +0000] http_method=GET request_method_from_client=GET request_method_to_server=- url="/test" http_referrer="-" http_user_agent="-" status=400 vendor_action=NONE dest_status=HIER_NONE total_time_milliseconds=- http_content_type="text/html" bytes=3937 bytes_in=82 bytes_out=3855 sni="-"
```

### Additional Context

Strange thing is, Im notificing this behvaior only with `/var/log/squid/access.log`. If I change the source as `/var/log/message` or `/var/log/secure` everything works just fine.

I checked the file permission too. Vector normally reports any file permission error if there isnt a sufficient permission to read. However, with squid access log, it doesnt report any sort of that too. However, I made 755 and tried restarting vector. Still nothing.

Attaching vector start status (which shows no error at all)


```
 ls -lart /var/log/squid/access.log
-rwxr-xr-x. 1 squid squid 910 Mar  9 08:04 /var/log/squid/access.log
```

And Im generating some squid logs by sending curl too, I can see new logs are coming in, but vector not processing anything. (verified in `vector top` )

### References

_No response_

**Comment by jszwedko** [comment] 2024-03-11 14:42
I'd suggest clearing any checkpoints that may have been stored in `/var/lib/vector`. It's possible that Vector already thinks that it read that file past its current length.

**Comment by dannylivington** [comment] 2024-03-12 01:02
I'll try that, and will see the behavior

**Comment by dannylivington** [comment] 2024-03-12 03:36
Still nothing. This is what I did

1) Stopped the vector service
2) Removed the source directory from /var/lib/vector
3) Started vector service
4) Made sure that the source directory appears under /var/lib/vector

```
cat checkpoints.json
{"version":"1","checkpoints":[]}
```

5) Generated some test events

`curl http://127.0.0.1:3128/test2/rest4`

6) squid log shows new entry

```
cat /var/log/squid/access.log
.
1710214205.584 logformat=splunk_recommended_squid duration=0 src_ip=127.0.0.1 src_port=36300 dest_ip=- dest_port=- user_ident="-" user="-" local_time=[12/Mar/2024:03:30:05 +0000] http_method=GET request_method_from_client=GET request_method_to_server=- url="/test2/rest4" http_referrer="-" http_user_agent="-" status=400 vendor_action=NONE dest_status=HIER_NONE total_time_milliseconds=- http_content_type="text/html" bytes=3958 bytes_in=89 bytes_out=3869 sni="-"
```

7) Checkpoints sitll showing empty

```
cat checkpoints.json
{"version":"1","checkpoints":[]}
```

And nothing is processesed nor detected by vector

**Comment by jszwedko** [comment] 2024-03-12 20:04
Hmm, that's odd. From the output you shared in the original issue it seems like Vector is not even be opening that file. Some things I would think to try:

- Ensure that the `vector` user that the process runs under can access that file (try `sudo -u vector cat /var/log/squid/access.log`)
- Use `lsof` to see if the running `vector` process has an open file handle to the file

**Comment by dannylivington** [comment] 2024-03-14 00:54
looks like vector user doesnt have permission to read the log file, and after I fixed that, it looks ok. 
However, Im still wondering why that access issue is not reported in "sytemctl status vector" or journalctl output. For other logs like /var/log/message and /var/log/secure, it does reports in status or vector logs if there is no permission which gives a hint where this going wrong

But in this case, vector didnt reported any error at all

**Comment by jszwedko** [comment] 2024-03-14 15:25
I'm glad you were able to narrow it down!

I tried to reproduce this to see what the behavior is and I do see error logs in both `systemctl status` and in `journald` if there is a lack of file permissions:

```
$  systemctl status --full vector
● vector.service - Vector
     Loaded: loaded (/lib/systemd/system/vector.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-03-14 15:22:38 UTC; 2min 19s ago
       Docs: https://vector.dev
    Process: 4270 ExecStartPre=/usr/bin/vector validate (code=exited, status=0/SUCCESS)
   Main PID: 4279 (vector)
      Tasks: 11 (limit: 18605)
     Memory: 8.9M
        CPU: 63ms
     CGroup: /system.slice/vector.service
             └─4279 /usr/bin/vector

Mar 14 15:24:22 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:22.910224Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
Mar 14 15:24:31 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:31.105816Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] has been suppressed 4 times.
Mar 14 15:24:31 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:31.105835Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/tmp/foo/bar.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
Mar 14 15:24:33 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:33.155505Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
Mar 14 15:24:41 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:41.351090Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] has been suppressed 4 times.
Mar 14 15:24:41 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:41.351111Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/tmp/foo/bar.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
Mar 14 15:24:43 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:43.399784Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
Mar 14 15:24:51 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:51.596522Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] has been suppressed 4 times.
Mar 14 15:24:51 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:51.596542Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/tmp/foo/bar.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
Mar 14 15:24:53 ip-172-31-27-106 vector[4279]: 2024-03-14T15:24:53.645293Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
```
```
$ journalctl -xe -u vector | cat
Mar 14 15:22:38 ip-172-31-27-106 systemd[1]: Starting Vector...
░░ Subject: A start job for unit vector.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit vector.service has begun execution.
░░
░░ The job identifier is 2006.
Mar 14 15:22:38 ip-172-31-27-106 vector[4270]: √ Loaded ["/etc/vector/vector.yaml"]
Mar 14 15:22:38 ip-172-31-27-106 vector[4270]: √ Component configuration
Mar 14 15:22:38 ip-172-31-27-106 vector[4270]: √ Health check "sink1"
Mar 14 15:22:38 ip-172-31-27-106 vector[4270]: ------------------------------------
Mar 14 15:22:38 ip-172-31-27-106 vector[4270]:                            Validated
Mar 14 15:22:38 ip-172-31-27-106 systemd[1]: Started Vector.
░░ Subject: A start job for unit vector.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit vector.service has finished successfully.
░░
░░ The job identifier is 2006.
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.389490Z  INFO vector::app: Log level is enabled. level="info"
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.390768Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.yaml"]
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.392470Z  INFO vector::topology::running: Running healthchecks.
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.392534Z  INFO vector: Vector has started. debug="false" version="0.36.1" arch="x86_64" revision="2857180 2024-03-11 14:32:52.417737479"
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.392548Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.392547Z  INFO vector::topology::builder: Healthcheck passed.
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.392591Z  INFO source{component_kind="source" component_id=source0 component_type=file}: vector::sources::file: Starting file server. include=["/tmp/foo/bar.log"] exclude=[]
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.392981Z  INFO source{component_kind="source" component_id=source0 component_type=file}:file_server: file_source::checkpointer: Loaded checkpoint data.
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.393123Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/tmp/foo/bar.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
Mar 14 15:22:38 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:38.393182Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
Mar 14 15:22:48 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:48.646594Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] has been suppressed 6 times.
Mar 14 15:22:48 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:48.646614Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/tmp/foo/bar.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
Mar 14 15:22:50 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:50.696312Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
Mar 14 15:22:58 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:58.893061Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] has been suppressed 4 times.
Mar 14 15:22:58 ip-172-31-27-106 vector[4279]: 2024-03-14T15:22:58.893081Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/tmp/foo/bar.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
Mar 14 15:23:00 ip-172-31-27-106 vector[4279]: 2024-03-14T15:23:00.941780Z ERROR source{component_kind="source" component_id=source0 component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding
```

I'll close this out since it seems to be resolved.

**Closed by jszwedko** 2024-03-14 15:25 UTC
Labels: type: bug, source: file
