### ISSUE TITLE
Metrics to give batching insight and help user with optimizations

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#20284] opened 2024-04-11 09:46 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

For many sinks, it is crucial to optimize batching (Elasticsearch, Clickhouse). Unfortunately Vector does not provide metrics that could be used to simplify this process.

It would be good to have these metrics available:

- batch size in bytes
- batch size in number of events
- batch timeout (how long did it take for batch to be ready for flush, if it reached timeout_secs or not)
- batch flush duration (how long does it take for backend to ack the write)

### Attempted Solutions

`component_sent_events_total` and `component_sent_event_bytes_total` are useful to know rate at which given sink is sending events and then guess some values for batch configuration.

It is also very difficult to understand relation between buffer and batch limits.

If user configures max batch size to be larger than buffer size, what will happen? If there's direct relation, then Vector should throw a warning if buffer size is lower than batch limit and should recommend buffer size being at least same as batch size or in multiples of batch size (eg. batch size * 2 to have some read-ahead from sources).

Also how does this work when ARC or concurrency > 1 is being used (then it should be batch size * expected max concurrency).

And last thing, if user has one source (eg. kafka) and multiple sinks (ES, S3) with different buffer size. Will sink with smaller buffer throttle the other one?

### Proposal

- add metrics to give batching insight
- describe buffer and batch relation, throw warning if it is not properly configured
- provide guidance on how to optimize pipeline

**Comment by jszwedko** [comment] 2024-04-11 13:54
Thanks for opening this @fpytloun ! I think it is a duplicate of https://github.com/vectordotdev/vector/issues/9719 so I'll close this one, but I like the additional detail you added here. Feel free to leave more comments on the other issue.

**Closed by jszwedko** 2024-04-11 13:54 UTC
Labels: type: feature
