### ISSUE TITLE
Can we enable SASL/SCRAM on Windows without GSSAPI?

### ISSUE THREAD

**Issue by Ilmarii** [vectordotdev/vector#14874] opened 2022-10-18 09:53 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

SASL is currently disabled due to build issues with krb5-src on WIndows (https://github.com/vectordotdev/vector/pull/3081#issuecomment-659298042)

### Attempted Solutions

But if we only need SCRAM mechanisms krb5-src is not needed, `sasl2-sys` now has a separate feature for this: https://github.com/MaterializeInc/rust-sasl/blob/master/sasl2-sys/Cargo.toml#L38
I tried to build with this feature and it work fine for me.

### Proposal

I suppose changes to rust-rdkafka will be required.
I added these features for my build: 
`rust-rdkafka`: `scram-vendored = ["rdkafka-sys/scram-vendored"]`
`rdkafka-sys`: `scram-vendored = ["ssl", "sasl2-sys/scram", "sasl2-sys/openssl-vendored"]`
And for `vector` added `"rdkafka?/scram-vendored"` to `default-msvc` feature.

### References

#4866

### Version

0.28.1

**Comment by Neustradamus** [comment] 2022-10-23 17:52
Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by sproberts92** [comment] 2022-12-20 13:44
I would be keen for this to be enabled. Is there more to it than just adding the features described above?

**Comment by sproberts92** [comment] 2022-12-22 08:42
I have opened a PR to rust-rdkafka to add those features that you suggested @Ilmarii.

**Comment by Neustradamus** [comment] 2022-12-22 13:31
Thanks a lot @sproberts92!

Your PR is here:
- https://github.com/fede1024/rust-rdkafka/pull/528

**Comment by sproberts92** [comment] 2022-12-24 12:55
Hmm following on from @benesch's  statement on the rust-rdkafka PR that we probably don't need a change to rust-rdkafka, I went back and did some testing with Vector on Windows.

Personally, I first noticed the lack of SCRAM support in Vector on Windows in 0.23.0, and this issue was opened on Oct 18, which would have been 0.24.2. I'd be willing to bet that none of us have really tested it again since, and assumed there was still no support... so it was much to my surprise when I tested 0.26.0 and I was able to use SASL/SCRAM successfully.

I can confirm that 0.25.2 still shows the familiar
```
2022-12-24T12:36:50.330949Z ERROR vector::topology: Configuration error. error=Sink "kafka": creating kafka producer failed: Client creation error: No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with openssl support. Current build options: PLAIN WindowsSSPI(GSSAPI)
```
whereas 0.26.0 is able to produce without any issue.

Tested using the config below with Vector installed in a fresh Windows 10 VM, and an appropriately configured Kafka cluster:
```
[sinks.kafka] 
type = "kafka" 
inputs = ["parse_logs"] 
encoding.codec = "json" 
bootstrap_servers = "foo.bar:9093" 
sasl.enabled = true 
sasl.mechanism = "SCRAM-SHA-256" 
sasl.username = "test" 
sasl.password = "test" 
topic = "test"
```

I've had a bit of a look at the [diff between 0.25.2 and 0.26.0](https://github.com/vectordotdev/vector/compare/v0.25.2...v0.26.0#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) but as I'm less intimately familiar with the `Cargo.toml` of this project it's not obvious to me what the key difference is.

@Ilmarii are you able to confirm the same, that 0.26.0 now works with SASL/SCRAM on Windows? I've only confirmed at home for now and should also be able to test at the office later next week.

**Comment by jszwedko** [comment] 2022-12-27 16:42
Interesting, thanks for digging into that @sproberts92 . I'm also not seeing anything jump out in the Cargo.toml diff. The upgrade of rdkafka/librdkafka seems like the most suspicious but looking through the changelogs there I'm not seeing anything either. We've already been vendoring openssl. I'll give @Ilmarii a chance to confirm, but otherwise it looks like we can close this out.

**Comment by jszwedko** [comment] 2023-02-01 22:30
Closing this out since it seems to be complete.

**Closed by jszwedko** 2023-02-01 22:30 UTC
Labels: sink: kafka, source: kafka, meta: blocked, type: feature
