### ISSUE TITLE
Datadog Agent not supporting Rate metric type

### ISSUE THREAD

**Issue by datsabk** [vectordotdev/vector#14857] opened 2022-10-17 07:07 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have a `Rate` type metric being submitted to [Datadog Agent source](https://vector.dev/docs/reference/configuration/sources/datadog_agent/). The metric is being treated as `Counter` which is causing trouble in how the metric gets visualized. 

Below is the JSON body thats submitted to the source: 
```
{"host":"i-0e7b18d0911f00d68","interval":10,"metric":"metload.general.count","points":[[xx,xx]],"tags":["environment:stage","env:stage","region:us-west-2","app:metricsloadgenerator"],"type":"rate"}
```

The outcome of it is:
```
{"name":"general.count","namespace":"metload","tags":{"app":"metricsloadgenerator","env":"stage","environment":"stage","host":"i-0e7b18d0911f00d68","region":"us-west-2"},"timestamp":"2022-10-17T07:04:11Z","kind":"incremental","counter":{"value":xxx}}
```

There is no field in the Data model for type `Rate` which is potentially causing this problem. 

### Configuration

```text
sources:
                datadog_agent:
                  address: 0.0.0.0:8282
                  type: datadog_agent
                  disable_logs: true
                  disable_traces: true
                  multiple_outputs: false
           sinks:
                my_sink_id:
                  type: console
                  inputs:
                    - datadog_agent
                  target: stdout
                  encoding:
                    codec: json
```
```


### Version

0.23.3

### Debug Output

_No response_

### Example Data

Provided in the issue description.

### Additional Context

_No response_

### References

_No response_

**Comment by datsabk** [comment] 2022-10-17 07:08
@jszwedko - Requesting attention. Its a limitation and major blocker. Happy to help with all the inputs needed.

**Comment by jszwedko** [comment] 2022-10-17 14:06
Hi @datsabk!

We believe this was fixed in 0.24.2. Could you try that version?

**Comment by jszwedko** [comment] 2022-10-17 14:07
Closing as duplicate of https://github.com/vectordotdev/vector/issues/14740 but let us know if it still isn't working for you once you upgrade.

**Closed by jszwedko** 2022-10-17 14:07 UTC
Labels: type: bug, sink: datadog_metrics, source: datadog_agent

**Comment by datsabk** [comment] 2022-10-17 16:42
@jszwedko - The problem of metric type gets solved but the [calculation](https://github.com/vectordotdev/vector/blob/e72f126af85cc8f577d8c893a641da6476089f39/src/sources/datadog_agent/metrics.rs#L463) is incorrect. 

For instance, my rate metric is published as 40 for interval 10 seconds means - The count increased by 40 in 10seconds. However, vector is multiplying 40 by 10 to get the count value which ends up reaching "400". The problem further is that it submits this 400 as rate instead of 40! 

Request to reopen and check if my understanding is correct here.

**Comment by jszwedko** [comment] 2022-10-17 16:51
@datsabk did you try 0.24.2? I see in the issue report you appear to be running 0.23.3. We've had another user confirm the fixes work for them so it'd be good to verify that version. If you still see issues we can dig in 🙂

**Comment by datsabk** [comment] 2022-10-17 17:18
@jszwedko - Yes I was on 0.24.2 and had this happening. However, I changed the metric name and issue seems to have gone away. Could be something at Datadog side. I'll dig in and let you know if there's still something fishy. Thanks for prompt responses.
