### ISSUE TITLE
Support node-exporter metrics in host_metrics

### ISSUE THREAD

**Issue by AndrewChubatiuk** [vectordotdev/vector#17247] opened 2023-04-28 20:16 UTC
### A note for the community

`host_metrics` has some of node-exporter metrics, but this is not enough. It lacks most of collectors listed in https://github.com/prometheus/node_exporter/blob/master/README.md. Also `memory` collector metrics do not respect node-exporter convention

### Use Cases

This is useful to use less daemonsets in K8s cluster. Fluentbit in V2 added node-exporter metrics

**Comment by bruceg** [comment] 2023-04-28 20:28
Are there some of the metrics in particular you are interested in? We are unlikely to add support for everything there, so that would help us prioritize any enhancements. We would also accept enhancement pull requests.

How do the memory collector metrics differ from the Prometheus node exporter's metrics? The linked document doesn't go into many details of what is emitted.

**Comment by jszwedko** [comment] 2023-04-28 21:22
I see FluentBit also has a separate input specifically intended to mirror the node exporter rather than modifying its existing host metrics collection: https://docs.fluentbit.io/manual/pipeline/inputs/node-exporter-metrics (it also mentions that it is incomplete).

I agree with @bruceg's comment that we'd be more likely to add specific metrics that are requested, to Vector, rather than aim for general Prometheus node exporter compatibility as doing so seems like a decent amount of work and continuing maintenance (to maintain parity) that doesn't provide a ton of value over just running the node exporter and having Vector scrape it with the `prometheus_scrape` source.

**Comment by jszwedko** [comment] 2023-05-02 21:46
> @jszwedko solution with `promtheus_scrape` doesn't help to improve already existing setup, cause we'd like to decrease amount of daemonsets in a cluster

This is fair, but also it is a fair bit work to add to Vector and to keep it up-to-date with any node_exporter changes (as evidence of this, fluentbit seems to lack [full compatibility](https://github.com/fluent/fluent-bit/issues?q=is%3Aissue+is%3Aopen+node_exporter)) for what doesn't _seem_ like a lot of value added over users running the node_exporter if they want the metrics it provides. If you didn't want to run it as another daemonset you could even run it in the same container as Vector.

**Comment by jszwedko** [comment] 2023-09-28 01:52
Closing this since we won't be taking it up.

We appreciate the discussion, but maintaining compatibility with `node_exporter` metrics in Vector just doesn't seem like it provides enough value to overcome the significant maintenance burden it would incur to introduce and maintain compatibility. Our recommendation, if you want `node_exporter` metrics is to just run the `node_exporter`.

**Closed by jszwedko** 2023-09-28 01:52 UTC
Labels: type: enhancement, source: host_metrics

**Comment by james-stevens** [comment] 2023-11-03 09:58
> > @jszwedko solution with `promtheus_scrape` doesn't help to improve already existing setup, cause we'd like to decrease amount of daemonsets in a cluster
> 
> This is fair, but also it is a fair bit work to add to Vector and to keep it up-to-date with any node_exporter changes (as evidence of this, fluentbit seems to lack [full compatibility](https://github.com/fluent/fluent-bit/issues?q=is%3Aissue+is%3Aopen+node_exporter)) for what doesn't _seem_ like a lot of value added over users running the node_exporter if they want the metrics it provides. If you didn't want to run it as another daemonset you could even run it in the same container as Vector.

I totally agree ... and IMHO, given the above, it seems relatively pointless keeping the `host_metrics` feature. Either it should reproduce all metrics, or just deprecate it.

**Comment by jszwedko** [comment] 2023-11-03 13:24
@james-stevens The `host_metrics` source was never meant to replicate the functionality Prometheus `node_exporter`. I think there is space for both to exist 🤔 . If `node_exporter` was more of the "standard" I might agree, but it seems like each system collector ends up implementing its own (e.g. Telegraf, OpenTelemetry collector, Metricbeat, Vector, Prometheus). I think users can choose the one that works best for their use-cases.
