### ISSUE TITLE
Vector aggregator's transform bottleneck

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#10622] opened 2021-12-29 15:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

### Vector Configuration File

Vector agent
```yaml
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    kubernetes_logs_agent:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 900000
      glob_minimum_cooldown_ms: 2000
      extra_field_selector: metadata.namespace=default
    internal_metrics_agent:
      type: internal_metrics
  sinks:
    vector_agent:
      type: vector
      inputs:
        - kubernetes_logs_agent
      address: vector-aggregator-haproxy.vector.svc:9080
      healthcheck:
        enabled: true
    prometheus_exporter_agent:
      type: prometheus_exporter
      inputs:
        - internal_metrics_agent
      address: 0.0.0.0:9090
```

Vector aggregator
```yaml
replicas: 1

haproxy:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: 200m
      memory: 64Mi

customConfig:
  data_dir: "/vector-data-dir"
  timezone: Etc/UTC
  log_schema:
    message_key: vector_message
  sources:
    kubernetes:
      type: vector
      address: 0.0.0.0:9080
  # transform: {}
  sinks:
    blackhole_aggregator:
      type: blackhole
      inputs:
        - kubernetes
        # - <transform>
      print_interval_secs: 30
      rate: 100000
```
<details>
<summary>Logs generator manifest:</summary>

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-logs-json
  labels:
    component: test
spec:
  parallelism: 5
  backoffLimit: 4
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        name: dummy-logs-json
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
      - name: flog
        image: mingrammer/flog
        imagePullPolicy: IfNotPresent
        command:
        - flog
        - -f
        - json
        - -b
        - "524288000"
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-logs-rfc3164
  labels:
    component: test
spec:
  parallelism: 5
  backoffLimit: 4
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        name: dummy-logs-rfc3164
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
      - name: flog
        image: mingrammer/flog
        imagePullPolicy: IfNotPresent
        command:
        - flog
        - -f
        - rfc3164
        - -b
        - "524288000"
      restartPolicy: Never

```
</details>

### Expected Behavior

Vector would use as much computing resources as possible

### Actual Behavior

Vector aggregator is limited at ~ 7 CPUs at 10k events/sec

### Example Data

Without any transfoms (vector source -> blackhole sink), vector processed very fast:
<img width="640" alt="Screen Shot 2021-12-29 at 16 43 46" src="https://user-images.githubusercontent.com/46129063/147679281-b0d35608-15fa-4a19-bee7-9a13c2306ce2.png">
<img width="640" alt="Screen Shot 2021-12-29 at 16 39 17" src="https://user-images.githubusercontent.com/46129063/147678944-87e40300-5364-45eb-a5b3-8ffb1799ad81.png">
<img width="640" alt="Screen Shot 2021-12-29 at 16 41 12" src="https://user-images.githubusercontent.com/46129063/147679026-34c74c69-3314-419d-b810-205a8aca5d37.png">

When some transforms VRL configs added, the processing power of aggregator pod is maxed at 7 CPUs at 10k events/sec
<img width="1305" alt="Screen Shot 2021-12-29 at 16 49 16" src="https://user-images.githubusercontent.com/46129063/147679784-8100db41-3ec9-4b39-ba9d-924a247f00eb.png">
<img width="1301" alt="Screen Shot 2021-12-29 at 16 49 52" src="https://user-images.githubusercontent.com/46129063/147679881-eb9e371d-d8f1-4fcf-a2e2-2484e9ae462a.png">

### Additional Context

I ran tests on an empty cluster with n1-standard-16 instances, so CPU & MEMORY resources are plenty. The topology is simple:
```
[ vector-agent ] ---> [ haproxy ] ---> [ vector aggregator ]
```

After tested with vector sending k8s source to blackhole sink directly, I added a 1000 lines of transforms block. But vector wouldn't use higher than 7 CPUs and events rate is stable at 10k events/sec that's sending to blackhole sink. Given plenty of resources doesn't seem matter. It looks like is there a bottleneck somewhere that limited vertical scaling?

**Comment by jszwedko** [comment] 2021-12-29 16:37
Hi @namm2 !

Would you want to try the version 2 of the Vector source/sink protocol? This version should have better scaling behavior as it is HTTP-based. The default in 0.18.1 was version 1 which is a simple protocol over TCP that is fairly limited.

You can enable it by setting `version: 2` on both the `vector` source and sink configuration.

**Comment by jszwedko** [comment] 2021-12-29 16:38
`0.19.0` removed the default protocol version as part of migrating users to version `2` which will be the default in a future release (probably `0.20.0`).

**Comment by jszwedko** [comment] 2021-12-29 16:53
Apologies, I also missed that the lower graphs were with the transforms defined.

In that case, in addition to the above suggestion of using the different protocol version for the vector sources/sink:

* Would you want to try `0.19.0`? This release includes some changes to allow a some transform types (like `remap`) to be parallelized
* Could you share the transform config to see if anything jumps out to us as possibly impacting performance?

**Comment by namm2** [comment] 2021-12-30 09:15
@jszwedko Thanks for replying, yes I've tried to put `version: "2"` on vector source & sink with v0.18.1 but it doesn't affect much, so I didn't mentioned it.

<details>
<summary>This is my vector aggregator configs with only generic contents:</summary>

```yaml
customConfig:
  data_dir: "/vector-data-dir"
  timezone: Etc/UTC
  log_schema:
    message_key: vector_message
  sources:
    kubernetes:
      type: vector
      address: 0.0.0.0:9080
  transforms:
    agents:
      type: remap
      inputs:
        - kubernetes
      source: |-
        if is_null(.vector_message) { .vector_message = del(.message) }

        # Needed early on for routing
        if is_null(.cloud_provider.service) {
          .cloud_provider.service = "k8s"
        }
        .cloud_provider.name = "${CLOUD_PROVIDER_NAME:-default}"
        .cloud_provider.region = "${CLOUD_PROVIDER_REGION:-default}"
        .cloud_provider.account = "${CLOUD_PROVIDER_ACCOUNT:-default}"
        .environment = "${ENVIRONMENT:-default}"

    route_agents:
      type: route
      inputs:
        - agents
      route:
        k8s: .cloud_provider.service == "k8s"

    legacy_fields:
      type: remap
      inputs:
        - route_agents.k8s
      source: |-
        if exists(.kubernetes.pod_labels."app.kubernetes.io/name") {
          .kubernetes.pod_labels."app_kubernetes_io/name" = del(.kubernetes.pod_labels."app.kubernetes.io/name")
        }
        if exists(.kubernetes.pod_labels."app.kubernetes.io/instance") {
          .kubernetes.pod_labels."app_kubernetes_io/instance" = del(.kubernetes.pod_labels."app.kubernetes.io/instance")
        }
        if exists(.kubernetes.pod_labels."app.kubernetes.io/component") {
          .kubernetes.pod_labels."app_kubernetes_io/component" = del(.kubernetes.pod_labels."app.kubernetes.io/component")
        }
        if exists(.kubernetes.pod_labels."app.kubernetes.io/managed-by") {
          .kubernetes.pod_labels."app_kubernetes_io/managed-by" = del(.kubernetes.pod_labels."app.kubernetes.io/managed-by")
        }
        if exists(.kubernetes.pod_labels."app.kubernetes.io/version") {
          .kubernetes.pod_labels."app_kubernetes_io/version" = del(.kubernetes.pod_labels."app.kubernetes.io/version")
        }
        if exists(.kubernetes.pod_labels."app.kubernetes.io/created-by") {
          .kubernetes.pod_labels."app_kubernetes_io/created-by" = del(.kubernetes.pod_labels."app.kubernetes.io/created-by")
        }
        if exists(.kubernetes.pod_labels."app.kubernetes.io/part-of") {
          .kubernetes.pod_labels."app_kubernetes_io/part-of" = del(.kubernetes.pod_labels."app.kubernetes.io/part-of")
        }
        if exists(.kubernetes.pod_labels."helm.sh/chart") {
          .kubernetes.pod_labels."helm_sh/chart" = del(.kubernetes.pod_labels."helm.sh/chart")
        }

        if .cloud_provider.name == "aws" {
          .kubernetes.namespace_name = .kubernetes.pod_namespace
          .log = .vector_message
          .kubernetes.host = .kubernetes.pod_node_name
          .kubernetes.labels = .kubernetes.pod_labels
          .docker.container_id = .kubernetes.container_id
          .kubernetes.pod_id = .kubernetes.pod_uid
        }
        if .cloud_provider.name == "gcp" {
          .resource.labels.cluster_name = "${K8S_CLUSTER_NAME:-default}"
          .resource.labels.container_name = .kubernetes.container_name
          .resource.labels.location = "${K8S_CLUSTER_LOCATION:-default}"
          .resource.labels.namespace_name = .kubernetes.pod_namespace
          .resource.labels.pod_name = .kubernetes.pod_name
          .resource.labels.project_id = .cloud_provider.account
          .resource.type = "k8s_container"

          parsed, err = parse_json(.vector_message)
          if err == null {
            if exists(parsed.kv) {
              .jsonPayload.kv = parsed.kv
            } else if !includes(["<some container names>", "<container name>", ... ], .kubernetes.container_name) {
              .jsonPayload = parsed
            }
          } else {
            .textPayload = .vector_message
          }
        }

    pre_processing:
      type: remap
      inputs:
        - legacy_fields
      source: |-
        # drop unneeded autoinjected fields
        del(.file)

        # parse and unpack JSON events in order
        # to use their fields for routing.
        parsed, err = parse_json(.vector_message)
        if err == null {
          del(.vector_message) # not needed anymore
          if exists(parsed.resource) {
            parsed.resource_str = encode_json(del(parsed.resource))
          }
          . = merge!(., parsed)
          .log_format = "json"
        } else {
          .log_format = "raw"
        }

    remap_containers:
      type: remap
      inputs:
        - pre_processing
      source: |-
        # unset .route just in case it was parsed from a JSON log event
        .route = null
        if .kubernetes.container_name == "<container_name>" || .kubernetes.container_name == "<container_name>" || .kubernetes.container_name == "<container_name>" || .type == "<name>" {
          .route = "<route1>"
        }
        if is_null(.route) && (.type == "<name>" || .type == "<name>" || .type == "<name>") {
          .route = "<name>"
        }
        if is_null(.route) && .type == "<name>" {
          .route = "<name>"
        }
        # the following must always come last:
        if is_null(.route) && .log_format == "json" {
          .route = "json"
        }
        if is_null(.route) {
          .route = "other"
        }

        # routing temporary fields are not needed anymore
        del(.log_format)
  sinks:
    blackhole_aggregator:
      type: blackhole
      inputs:
        - remap_containers
      print_interval_secs: 30
      rate: 100000
```
<details>

With vector 0.18.1, it can only sent ~ 20k events/sec to the blackhole sink:
<img width="1311" alt="Screen Shot 2021-12-30 at 10 10 07" src="https://user-images.githubusercontent.com/46129063/147737779-472a2b66-7cbf-4538-bf14-cc137f2ae27c.png">

And vector's CPU usage was just slightly under 3 CPUs:
<img width="1306" alt="Screen Shot 2021-12-30 at 10 11 25" src="https://user-images.githubusercontent.com/46129063/147737876-b027ee49-0393-44ca-93c4-70b07ae4ed6d.png">


WIth the same configs, vector 0.19.0's improvement is impressive up to 53k events/sec:
<img width="1309" alt="Screen Shot 2021-12-30 at 10 12 53" src="https://user-images.githubusercontent.com/46129063/147737998-7608354d-1162-466b-9e15-a02a24fe504a.png">
And vector's CPU usage jumped up to 8.5 CPUs:
<img width="1314" alt="Screen Shot 2021-12-30 at 10 14 17" src="https://user-images.githubusercontent.com/46129063/147738088-88a29ed8-ac32-4531-93cb-d240f4daee36.png">

This results made vector 0.19.0 looks really promising, but I can't understand what's holding back vector when given plenty of computing resources?

**Comment by jszwedko** [comment] 2022-12-23 22:05
Duplicate of https://github.com/vectordotdev/vector/issues/15298. The issue here is that the aggregate transform can't be run concurrently. We hope to improve that in the future though through data partitioning.

**Closed by jszwedko** 2022-12-23 22:05 UTC
Labels: type: bug, sink: vector, source: vector, domain: performance
