### ISSUE TITLE
`gcp_cloud_storage` `encoding` incorrectly marked as optional

### ISSUE THREAD

**Issue by khionu** [vectordotdev/vector#10887] opened 2022-01-17 23:44 UTC
Vector: `vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)`

Without adding an encoding field, this output is created
```
Failed to load ["vector.toml"]
------------------------------
x missing field `encoding` for key `sinks.gcs` at line 12 column 1
```

**Comment by spencergilbert** [comment] 2022-01-18 17:52
This is actually a general problem with the website not generating properly off our cue files, duplicate of https://github.com/vectordotdev/vector/issues/10051

**Closed by spencergilbert** 2022-01-18 17:52 UTC
Labels: type: bug
