### ISSUE TITLE
Common strategy for sources (and other components?) when the upstream system fails 

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#6245] opened 2021-01-26 15:59 UTC
We have encountered this problem with the `docker_logs` source: when Docker crashes while we're connected to it, and closes the connection abruptly, the error is handled in a way that it's propagated through the component to the topology, and the topology handles it by shutting down.

It might be suboptimal since there might be other sources that can continue even when the `docker_logs` struggles, while the Docker itself is highly likely to be restarted and get back online in (tens of) seconds (or minutes, if more than that - people are likely having some critical issues).

So, a more optimal strategy would, obviously, be to go into a special mode, where we attempt to connect to docker for a while. If docker comes back online - we can continue, if not - crashing is ok I guess.

Do we have a consensus on how sources should behave in this and similar situations?
If we generally agree we should try to keep up, we should ensure that the sources actually implement this logic - maybe create a list of them, and validate that each works as expected.

cc @lukesteensen @binarylogic

**Comment by binarylogic** [comment] 2021-01-26 16:16
Vector should not crash when the `docker_logs` source encounters an error like this. It should log errors appropriately and indefinitely retry (with backoff) until things are back to normal. I thought we had that mechanism already? (see #3732).

Being resilient in the face of errors like this is important. If external systems can recover, then Vector should recover with them. That's not to say we should make this the default for all sources. There might be times where we do want to crash, so my vote would be for each source to handle this as it sees fit, but I'll defer to @lukesteensen on that.

**Comment by lukesteensen** [comment] 2021-01-26 16:26
> Vector should not crash when the `docker_logs` source encounters an error like this. It should log errors appropriately and indefinitely retry (with backoff) until things are back to normal.

Agreed. If it's clear that the problem is with the external system and not Vector itself, we should retry in a loop with backoff. Crashing should be reserved for cases where some invariant is broken or we have reason to believe Vector is doing the wrong thing.

**Comment by MOZGIII** [comment] 2021-01-27 03:21
Excellent!

Currently, it is indeed handled by each source, and there's no guidance on how to handle it. I think we should document it at `CONTRIBUING.md` - alongside [sink healthchecks](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#guidelines).

**Comment by syedriko** [comment] 2022-09-26 18:52
@MOZGIII Should we s/downstream/upstream in the title?

**Comment by jszwedko** [comment] 2022-09-26 20:28
> @MOZGIII Should we s/downstream/upstream in the title?

👍 agreed, updated.

**Comment by Rulasmur** [comment] 2022-09-27 06:01
I've had this same problem with the redis source. This basically makes vector unusable for us.

**Comment by jszwedko** [comment] 2022-12-29 17:50
Closing this in-lieu of creating issues for individual sources. Vector should retry failures.

**Closed by jszwedko** 2022-12-29 17:50 UTC
Labels: meta: idea
