### ISSUE TITLE
[UX] Config settings around `endpoint`/`url`/`address`/`uri` should be more consistent

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#17074] opened 2023-04-06 20:00 UTC
For both sources and sinks, we use these names in configuration settings without great consistency.

We should center on which one(s) to use for what data direction/application, update the component configuration settings, and document the reasoning at a central location to be referenced.

**Comment by jszwedko** [comment] 2023-07-17 19:37
Duplicate of https://github.com/vectordotdev/vector/issues/17074

**Closed by jszwedko** 2023-07-17 19:37 UTC
Labels: type: enhancement, type: tech debt, meta: idea

**Comment by neuronull** [comment] 2023-07-17 20:54
> Duplicate of #17074

👀  was this comment meant for a different issue? Or is the issue # link meant to point to a different one?

**Comment by neuronull** [comment] 2023-07-17 20:55
I bet https://github.com/vectordotdev/vector/issues/8877

**Comment by jszwedko** [comment] 2023-07-17 20:58
Doh, yep :) Meant to link to https://github.com/vectordotdev/vector/issues/8877
