### ISSUE TITLE
Vector GCS Source

### ISSUE THREAD

**Issue by atibdialpad** [vectordotdev/vector#11015] opened 2022-01-25 03:39 UTC
I noted that Vector has a GCS Sink but not a GCS source. 
Corresponding Logstash Plugin : https://www.elastic.co/guide/en/logstash/current/plugins-inputs-google_cloud_storage.html

**Comment by jszwedko** [comment] 2022-01-25 15:41
Thanks @atibdialpad ! I realized this is actually a duplicate of https://github.com/vectordotdev/vector/issues/7501

**Closed by jszwedko** 2022-01-25 15:41 UTC
Labels: type: enhancement, domain: sources, provider: gcp
