### ISSUE TITLE
Similar to the parsing function of the Dissect filter plugin in Logstash.

### ISSUE THREAD

**Issue by 41405465** [vectordotdev/vector#18303] opened 2023-08-18 01:04 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Our applications log in the following format:
[20230813_060934_933][W][TcpClient.cpp::Reconnect:861]Reconnect(id:687 ip:172.26.165.6 port:20882) failed(-17)[TID:118242]

The logstash dissect parsing is implemented as follows：
dissect {
		mapping => {
			"message" => "[%{time}][%{level}][%{file}::%{function}:%{line}]%{content}[TID:%{tid}]"
		}
	}

Does Vector have a parsing function similar to the Logstash Dissect filter plugin's parsing capability?
Dissect differs from Grok in that it does not use regular expressions and is faster. Dissect works well when data is reliably repeated.

**Comment by jszwedko** [comment] 2023-08-18 14:08
Duplicate of https://github.com/vectordotdev/vrl/issues/395

**Closed by jszwedko** 2023-08-18 14:08 UTC
Labels: type: feature
