### ISSUE TITLE
Missing docs for remapping metric events

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#8779] opened 2021-08-18 16:20 UTC
https://github.com/timberio/vector/blob/master/website/cue/reference/remap.cue#L259-L267

This section of "how it works" doesn't appear to be rendered on the site

**Comment by jszwedko** [comment] 2022-12-29 17:34
Duplicate of https://github.com/vectordotdev/vector/issues/8339

**Closed** 2023-01-04 14:37 UTC
Labels: type: bug, website: template
