### ISSUE TITLE
Socket source with bytes framing and TCP mode only sends data after connection is closed

### ISSUE THREAD

**Issue by dekelpilli** [vectordotdev/vector#17136] opened 2023-04-13 03:13 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

As the title says, the `socket` source with `bytes` framing doesn't seem to be behaving correctly when the mode is `tcp`.

In addition to the tests detailed in the Discord link below, I also set up tests using vector on both sides. The data would only appear on the receiving Vector instance after the sending Vector instance was stopped, and even then all of the data would be concatenated into one event. I believe the netcat tests in the Discord also show that this is an issue with the `socket` source, rather than with the sink.

### Configuration

Receiving:
```json
{
  "healthchecks": {
    "enabled": false
  },
  "log_schema": {
    "source_type_key": ""
  },
  "sources": {
    "a": {
      "address": "0.0.0.0:30000",
      "port_key": "",
      "mode": "tcp",
      "type": "socket",
      "host_key": "",
      "framing": {
        "method": "bytes"
      }
    },
    "b": {
      "address": "0.0.0.0:30001",
      "port_key": "",
      "mode": "tcp",
      "type": "socket",
      "host_key": "",
      "framing": {
        "method": "newline_delimited"
      },
      "decoding": {"codec": "bytes"}
    },
    "c": {
      "address": "0.0.0.0:30002",
      "framing": {
        "method": "bytes"
      },
      "port_key": "",
      "mode": "udp",
      "type": "socket",
      "host_key": ""
    }
  },
  "transforms": {
  },
  "sinks": {
    "ljpdseuegrsvnbvaagwkj": {
      "encoding": {
        "codec": "json"
      },
      "inputs": [
        "*"
      ],
      "target": "stderr",
      "type": "console"
    }
  }
}
```

Sending:
```json
{
  "log_schema": {
    "source_type_key": ""
  },
  "sources": {
    "h": 
    {
      "type": "http",
      "acknowledgements": false,
      "address": "0.0.0.0:${PORT:-1234}",
      "framing": {"method":"newline_delimited"},
      "path_key": ""
    }
  },
  "transforms": {
  },
  "sinks": {
    "tcp": {
      "type": "socket",
      "inputs": ["h"],
      "address": "0.0.0.0:30001",
      "mode": "tcp",
      "encoding": {
        "codec": "raw_message"
      },
      "framing": {
        "method": "bytes"
      },
      "buffer": {
        "max_events": 1
      }
    }
  }
}
```

### Version

vector 0.28.2 (x86_64-apple-darwin 986dd37 2023-04-10)

### Example Data

I sent three separate http messages to the sending Vector:
`abc`
`123`
and `ab`. Once I shut down that Vector instance, the following data appeared in the receiving Vector:

{"message":"abc123ab","timestamp":"2023-04-13T03:06:18.673551Z"}

### References

- Also discussed on discord: https://discord.com/channels/742820443487993987/1095691688506298528/1095691688506298528

**Comment by neuronull** [comment] 2023-05-30 18:17
Hi @dekelpilli , have you had a chance to review my previous comment?
Essentially, I believe the source is working as intended.

**Comment by dekelpilli** [comment] 2023-05-31 02:30
Hi @neuronull - I still believe this is not how the source should behave. My understanding is that the "underlying I/O's boundary" should just be a single TCP packet, rather than a full connection. Where the structure of a TCP packet is `<segment header><data>`, I would expect source `a` above to send the bytes content of <data> after every packet, and that the presence/absence of newlines within that data to make no impact on the framing of events emitted by the source.

This is my understanding of "split between messages or stream segments", rather than splitting messages when the connection is closed. I also believe this is far more useful, and if for TCP we take the I/O boundary to mean the start of a connection until the end of that connection, then bytes framing on the TCP is not a very useful feature (as it would require breaking and recreating the connection to get messages to progress).

**Comment by dekelpilli** [comment] 2023-06-03 08:41
> what is sending the data? 

Our own (thin) service that is receiving UDP messages and streaming them to Vector. At the moment, it's also adding newlines to the end of the messages as we're using `newline_delimited` (similar to source `b` above). This is, in large part, a workaround for the current issues with the UDP mode for the socket source (https://github.com/vectordotdev/vector/issues/15583, https://github.com/vectordotdev/vector/issues/8518). At the moment, this issue isn't impacting us very much because we have already implemented a workaround. That said, I do believe that if the current behaviour of the `bytes` framing won't change, it's worth clarifying the documentation to specify that the I/O boundary is the connection, rather than one packet.

> What is the data? What processing are you hoping to do in Vector?

Various application and device logs, which go through some transforms in vector before ending up in storage/loki sinks.

**Comment by jszwedko** [comment] 2023-06-23 20:26
Thanks for the additional details @dekelpilli ! Using the newline delimited framing for that case makes sense in light of the known issues for UDP (which would be nice to fix).

I agree that the connection based framing is not likely to be used much, but it is at least something senders using TCP have more control over than TCP packet splitting. That is, they can open a connection, send an "event", and close it but they can't guarantee that a single TCP packet will have a single event since TCP packets can be split in-transit.

Given the above discussion, I'll close this issue, but I appreciate you raising it!

**Closed by jszwedko** 2023-06-23 20:26 UTC

**Comment by jszwedko** [comment] 2023-06-23 20:31
Opened https://github.com/vectordotdev/vector/pull/17745 to clarify the docs.
