### ISSUE TITLE
Implement unit benchmarking framework

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3968] opened 2020-09-16 21:16 UTC
This epic represents implementing a continuous benchmarking suite in our CI. Vector offers a variety of ways to benchmark Vector:

<p></p>

1. Local, Rust-native benchmarks via the `/benches` folder.

2. The end-to-end blackbox [test harness](https://github.com/timberio/vector-test-harness/).

3. And other various handrolled setups.

<p></p>

These suites have been run on-demand and before each release. We would like to integrate one or more of these suites into CI so that they are run continously. This will help us identify performance regressions earlier and reduce the possible variables.

# Goals

1. Identify the layers of benchmarking so we can formalize work going forward.

2. Integrate these benchmarks into CI, both on a pull-request basis and nightly basis.

3. Collect performance data so we can compare performance across different versions of Vector.

**Comment by vector-vic** [comment] 2020-09-16 21:16
Link to feature: https://timber.productboard.com/feature-board/planning/features/5303082

**Comment by jszwedko** [comment] 2022-12-01 23:26
Closing since this was superseded by the end-to-end regression framework currently in place.

**Closed by jszwedko** 2022-12-01 23:26 UTC
Labels: type: tech debt, domain: ci, domain: performance, Epic
