### ISSUE TITLE
Show http request/reponse body in debug mode (up to some character limit)

### ISSUE THREAD

**Issue by nmiculinic** [vectordotdev/vector#21441] opened 2024-10-07 16:35 UTC
### Use Cases

I'm sending logs to 3rd party HTTPS endpoint. It's failing with http 400. I want to see http response body to debug the issue further. Despite running vector with `VECTOR_LOG=debug` this is the best I'm getting:

```
2024-10-07T16:24:24.846491Z DEBUG sink{<>}:request{request_id=60}:http: vector::internal_events::http_client: HTTP response. status=400 Bad Request version=HTTP/1.1 headers={"content-type": "application/json; charset=utf-8", "content-length": "73", "connection": "keep-alive", "content-security-policy": "default-src 'none'; frame-ancestors 'none'", "strict-transport-security": "max-age=63072000", "x-content-type-options": "nosniff", "date": "Mon, 07 Oct 2024 16:24:24 GMT"} body=[73 bytes]
```

### Attempted Solutions

https://github.com/vectordotdev/vector/blob/51dcf8dfd4b9be926fd45b584908e820df4c2b7a/src/internal_events/http_client.rs#L99

Unfortunately all info I have in the code seems to be how long is the body, but not what is the body. In my case it's 73bytes long....but I have no idea what those 73 bytes are.

### Proposal

Anything reasonable that I can see response body. e.g. having envvar `VECTOR_DEBUG_HTTP_BODY_MAX_LEN` which will include debug log up to first MAX_LEN characters before truncation. 

### Version

0.41.1

**Comment by jszwedko** [comment] 2024-10-07 17:10
Thanks for opening this @nmiculinic ! I think it is a duplicate of https://github.com/vectordotdev/vector/issues/15911 so I'll close this one, but feel free to add additional thoughts on the other issue!

**Closed by jszwedko** 2024-10-07 17:10 UTC
Labels: type: feature
