### ISSUE TITLE
journald source doesn't get input events after 0.22.0 upgrade

### ISSUE THREAD

**Issue by mhaggerty042** [vectordotdev/vector#13073] opened 2022-06-09 21:01 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

After upgrading from vector 0.21.2 to 0.22.0, our [journald source](https://vector.dev/docs/reference/configuration/sources/journald/) stopped receiving input events.

Notice how the input events for the journald source is 1, but the other metric sources are in the thousands.

![vector-top](https://user-images.githubusercontent.com/10854753/172937586-951363bf-570a-4402-857e-e7c904bd5375.png)

I restarted vector 0.22.0 a few times as I enabled debug and turned on the api, but I did not see any errors. Here are the logs for one of those cycles - [vector-0.22.0-logs.txt](https://github.com/vectordotdev/vector/files/8873904/vector-0.22.0-logs.txt)

I then stopped vector, and restarted it with 0.21.2 and noticed the input events started going up.

<img width="1423" alt="vector-0 21 2-top" src="https://user-images.githubusercontent.com/10854753/172941771-284626fb-f444-4724-87b6-1e920707d67b.png">

### Configuration

```text
{
  "data_dir": "/var/lib/vector",
  "api": {
    "enabled": true
  },
  "sources": {
    "host_metrics_source": {
      "type": "host_metrics",
    },
    "service_logs_source": {
      "type": "journald",
      "include_units": [
        "cloud-host-manager.service",
        "scada-proxy.service",
        "user@1001.service"
      ]
    }
  },
  "transforms": {
    "add_metrics_tags_remap": {
      "type": "remap",
      "inputs": [
        "host_metrics_source",
      ],
      "source": "REDACTED"
    },
    "add_log_tags_remap": {
      "type": "remap",
      "inputs": [
        "service_logs_source"
      ],
      "source": "REDACTED"
    },
  },
  "sinks": {
    "datadog_logs_sink": {
      "type": "datadog_logs",
      "inputs": [
        "add_log_tags_remap"
      ],
      "default_api_key": "REDACTED",
      "compression": "gzip"
    },
    "datadog_metrics_sink": {
      "type": "datadog_metrics",
      "inputs": [
        "add_metrics_tags_remap"
      ],
      "api_key": "REDACTED",
    }
  }
}
```

### Version

version="0.22.0" arch="x86_64" build_id="5e937e3 2022-06-01"

**Comment by jszwedko** [comment] 2022-06-09 21:15
Hi @mhaggerty042 !

I think this is a duplicate of #12966 . We are cutting a release with a bugfix for this shortly.

**Closed by jszwedko** 2022-06-09 21:15 UTC
Labels: type: bug
