### ISSUE TITLE
hang on redis::parser::aio_support::ValueCodec::decode_stream::h0fdb334ac776be3d

### ISSUE THREAD

**Issue by noodle-fish** [vectordotdev/vector#17431] opened 2023-05-18 06:20 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I use vector as a forwarder between redis and clickhouse. Unfortunately, after a few minutes of normal operation, vector no longer forwards data. And occupy 100% of the computing resources of the cpu thread. I checked the stack information of two of this thread at intervals. found that they are all executing this function:
```
redis::parser::aio_support::ValueCodec::decode_stream::h0fdb334ac776be3d
```

### Version

0.29.1

### Debug Output

```text
Thread 16 (Thread 0x7fd0abfff700 (LWP 259381)):
#0  0x00007fd0ef7f1c3b in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x00005575271ff30e in alloc::raw_vec::finish_grow::h009fe8d1fc043057 ()
#2  0x0000557526dd8db7 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::reserve::do_reserve_and_handle::h0280d4a568ca303d ()
#3  0x0000557527ef3028 in _$LT$alloc..string..String$u20$as$u20$core..fmt..Write$GT$::write_str::h69901c03d49f2f40 ()
#4  0x00005575273c8e8d in core::fmt::num::imp::_$LT$impl$u20$core..fmt..Display$u20$for$u20$u64$GT$::fmt::h6cfa4c009e125745 ()
#5  0x00005575273cae0e in core::fmt::write::h062c617411b691df ()
#6  0x0000557527ad5a8b in _$LT$combine..parser..sequence..ThenPartial$LT$P$C$F$GT$$u20$as$u20$combine..parser..Parser$LT$Input$GT$$GT$::parse_mode_impl::h6368eb40c918aa48 ()
#7  0x0000557527ad1b52 in _$LT$combine..parser..combinator..AnySendSyncPartialStateParser$LT$P$GT$$u20$as$u20$combine..parser..Parser$LT$Input$GT$$GT$::parse_partial::h011639861ac63380 ()
#8  0x0000557527ad05dd in redis::parser::aio_support::ValueCodec::decode_stream::h0fdb334ac776be3d ()
#9  0x0000557528f9ba5c in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::he0af6518060092f2 ()
#10 0x000055752a3c2cdc in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hbbc1dd3563382845 ()
#11 0x0000557529ce40ec in _$LT$tracing..instrument..Instrumented$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hb4180aabac693641 ()
#12 0x0000557529ce2a33 in tokio::runtime::task::raw::poll::h31b82eb24c4b2d85 ()
#13 0x0000557527de07a2 in tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hafb02d832abc1c0d ()
#14 0x0000557527dea605 in tokio::runtime::task::raw::poll::h51829b7d15320e86 ()
#15 0x0000557527dca2e9 in std::sys_common::backtrace::__rust_begin_short_backtrace::h28244d90814d35ae ()
#16 0x0000557527dc9f6d in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hd1f98ff135f87c72 ()
#17 0x0000557527d9c1c3 in std::sys::unix::thread::Thread::new::thread_start::h0a2f4c32ba2f2278 ()
#18 0x00007fd0eff76ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007fd0ef799b0d in clone () from /lib64/libc.so.6



Thread 16 (Thread 0x7fd0abfff700 (LWP 259381)):
#0  0x00005575273cac59 in core::fmt::write::h062c617411b691df ()
#1  0x0000557527ad1923 in _$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$::fmt::h37723d0530c84fb8 ()
#2  0x00005575273cae0e in core::fmt::write::h062c617411b691df ()
#3  0x0000557527ad0fda in redis::parser::aio_support::ValueCodec::decode_stream::h0fdb334ac776be3d ()
#4  0x0000557528f9ba5c in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::he0af6518060092f2 ()
#5  0x000055752a3c2cdc in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hbbc1dd3563382845 ()
#6  0x0000557529ce40ec in _$LT$tracing..instrument..Instrumented$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hb4180aabac693641 ()
#7  0x0000557529ce2a33 in tokio::runtime::task::raw::poll::h31b82eb24c4b2d85 ()
#8  0x0000557527de07a2 in tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hafb02d832abc1c0d ()
#9  0x0000557527dea605 in tokio::runtime::task::raw::poll::h51829b7d15320e86 ()
#10 0x0000557527dca2e9 in std::sys_common::backtrace::__rust_begin_short_backtrace::h28244d90814d35ae ()
#11 0x0000557527dc9f6d in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hd1f98ff135f87c72 ()
#12 0x0000557527d9c1c3 in std::sys::unix::thread::Thread::new::thread_start::h0a2f4c32ba2f2278 ()
#13 0x00007fd0eff76ea5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007fd0ef799b0d in clone () from /lib64/libc.so.6


flow_parser" time_remaining="14 seconds left"
2023-05-18T05:57:32.050583Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="eveflow, clickhouse, eveflow_parser" time_remaining="9 seconds left"
2023-05-18T05:57:37.050888Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="eveflow, clickhouse, eveflow_parser" time_remaining="4 seconds left"
2023-05-18T05:57:42.051261Z ERROR vector_common::shutdown: Source 'eveflow' failed to shutdown before deadline. Forcing shutdown.
2023-05-18T05:57:42.051305Z ERROR vector::topology::running: Failed to gracefully shut down in time. Killing components. components="eveflow, clickhouse, eveflow_parser"
```

### Example Data

Occurs after the amount of data per second exceeds 10,000 for a period of time (several minutes)

**Comment by noodle-fish** [comment] 2023-05-22 02:25
System: CentOS Linux release 7.9.2009 (Core)
Kernel: Linux x 5.4.170-1.el7.elrepo.x86_64 #1 SMP Tue Jan 4 17:11:53 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Here is docker-compose file
```
version: '2'
services:
  redis:
    container_name: redis
    image: bitnami/redis:7.0
    #restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        #- REDIS_PASSWORD=00000000
      - REDIS_PORT_NUMBER=6379
      - REDIS_AOF_ENABLED=no
      - REDIS_IO_THREADS=1
      - REDIS_IO_THREADS_DO_READS=yes
  vector:
    container_name: vector
    image: timberio/vector:0.29.X-debian
    #restart: always
    volumes:
      - './vector/etc:/etc/vector'
    ports:
      - '8686:8686'
    depends_on:
      - redis
    command: -C /etc/vector
```

Here is vector.toml
```
[sources.src]
type = "redis"
data_type = "channel"
key = "vector_in"
url = "redis://redis:6379"

# Parse evelog flow
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.trans]
type = "remap"
inputs = ["src"]
source = '''

. = parse_json!(.message)

#.timestamp = to_unix_timestamp(parse_timestamp!(.timestamp, "%Y-%m-%dT%H:%M:%S%.6f%z"), "nanoseconds")

#del(.message)
#del(.source_type)

'''

[sinks.redis]
type = "redis"
inputs = [ "trans" ]
endpoint = "redis://redis:6379"
key = "vector_out"
encoding.codec = "json"

[api]
enabled = true
address = "0.0.0.0:8686"
```


> Is there any chance you could provide an MRE for this @noodle-fish ?

**Comment by neuronull** [comment] 2023-05-31 19:25
Thanks for those configs @noodle-fish ! 

Do you by chance have a script or a file to import into redis for the reproduction of this issue?

**Comment by noodle-fish** [comment] 2023-06-01 03:04
> Thanks for those configs @noodle-fish !
> 
> Do you by chance have a script or a file to import into redis for the reproduction of this issue?

I've tried to do this but didn't reproduce the issue, probably related to the dataset I'm using. Unfortunately I am not yet able to share a dataset that reproduces this issue.

**Comment by neuronull** [comment] 2023-06-01 15:36
👍 we will stay tuned in case you (or another user who later encounters it) can provide it.

**Comment by jszwedko** [comment] 2023-09-28 01:47
Closing due to a lack of reproduction case here. If anyone has one, please leave it!

**Closed by jszwedko** 2023-09-28 01:47 UTC
Labels: type: bug, source: redis
