### ISSUE TITLE
Adding support for a mutable global external store for enrichment of data

### ISSUE THREAD

**Issue by lsampras** [vectordotdev/vector#20383] opened 2024-04-26 13:36 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

- Doing accumulations over a much longer period of time where I can keep on accumulating the data in an external store
- Enriching my logs with non static data which keeps on increasing / changing
- if else clauses based on external conditions

a simple use case for this would look like
```vrl
no_of_objects_encountered = get_global_table_record!("store_id", { "id":  .type })
.object_serial_no = no_of_objects_encountered + 1
set_global_table_record!("store_id", { "id":  .type }, no_of_objects_encountered + 1)
```

### Proposal

In terms of usage it could be similar to the enrichment tables accessed via VRL,

however these stores would also support inserting/modifying data.

Either we can build a new set of abstraction apart from the existing enrichment tables or extend the enrichment table traits to optionally support modifying/inserting values.

These functions for get/set would be fallible and could cause the stream to be blocked or drop events on failure based on configuration...

For now I'm thinking of some key-value stores like redis or cassandra without any local cache.

### Version

0.37.1

**Comment by jszwedko** [comment] 2024-04-26 13:52
Thanks for this @lsampras ! I think it is a duplicate of https://github.com/vectordotdev/vector/issues/17195 so I'll close this one, but let me know if you disagree.

**Closed by jszwedko** 2024-04-26 13:52 UTC
Labels: type: feature
