### ISSUE TITLE
Redact creditcard numbers

### ISSUE THREAD

**Issue by Sg-23** [vectordotdev/vector#11488] opened 2022-02-21 10:10 UTC
I am working on an implementation to redact card numbers, but with regex, I am getting false positives. I need to implement luhn checker for the same. Do we have any inbuilt functionality in vector or can the same be achieved with VRL? Will it require lua for the same?

**Comment by spencergilbert** [comment] 2022-02-24 14:20
Closing as duplicate of https://github.com/vectordotdev/vector/discussions/11496

**Closed by spencergilbert** 2022-02-24 14:20 UTC
