### ISSUE TITLE
[CLI] VRL compiler is always emitting ANSI color codes during errors

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#11446] opened 2022-02-17 15:49 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

There are two ways in Vector to decide if using color-output, i.e. emit ANSI color codes, in the terminal: (1) using the `--color <color>` CLI argument and (2) if `auto` is used for `--color` (the default) then check if the terminal is a TTY.

However, the VRL compiler doesn't seem to be using any of those methods and instead _always_ emit ANSI color codes.

In the following examples, a Vector configuration file with a VRL error in purpose is used (so the VRL compiler has output).

1. Using `auto` coloring: Vector logging is clean (correct), VRL compiler is still using ANSI codes (wrong):
```
$ vector -c vector.yaml --color auto 2>&1 | less -F
2022-02-17T15:42:10.153085Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-02-17T15:42:10.153243Z  INFO vector::app: Loading configs. paths=["vector.yaml"]
2022-02-17T15:42:10.155806Z ERROR vector::topology: Configuration error. error=Transform "remap":
ESC[0mESC[1mESC[38;5;9merror[E203]ESC[0mESC[1m: syntax errorESC[0m
  ESC[0mESC[34m┌─ESC[0m :1:11
  ESC[0mESC[34m│ESC[0m
ESC[0mESC[34m1ESC[0m ESC[0mESC[34m│ESC[0m if broken ESC[0mESC[31minESC[0m purpose { ... }
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31m^^ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31m│ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31munexpected syntax token: "Identifier"ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[34mexpected one of: "\n", "!=", "%", "&&", ")", "*", "+", ",", "-", "/", ";", "<", "<=", "==", ">", ">=", "??", "]", "{", "|", "|", "||", "}"ESC[0m
  ESC[0mESC[34m│ESC[0m
  ESC[0mESC[34m=ESC[0m see language documentation at https://vrl.dev
```
2. Using `never` coloring: Vector logging is clean (correct), VRL compiler is still using ANSI codes (wrong):
```
$ vector -c vector.yaml --color never 2>&1 | less -F
2022-02-17T15:45:07.609388Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-02-17T15:45:07.609476Z  INFO vector::app: Loading configs. paths=["vector.yaml"]
2022-02-17T15:45:07.610447Z ERROR vector::topology: Configuration error. error=Transform "remap":
ESC[0mESC[1mESC[38;5;9merror[E203]ESC[0mESC[1m: syntax errorESC[0m
  ESC[0mESC[34m┌─ESC[0m :1:11
  ESC[0mESC[34m│ESC[0m
ESC[0mESC[34m1ESC[0m ESC[0mESC[34m│ESC[0m if broken ESC[0mESC[31minESC[0m purpose { ... }
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31m^^ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31m│ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31munexpected syntax token: "Identifier"ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[34mexpected one of: "\n", "!=", "%", "&&", ")", "*", "+", ",", "-", "/", ";", "<", "<=", "==", ">", ">=", "??", "]", "{", "|", "|", "||", "}"ESC[0m
  ESC[0mESC[34m│ESC[0m
  ESC[0mESC[34m=ESC[0m see language documentation at https://vrl.dev
```
3. Using `always` coloring: Vector logging is using ANSI codes (correct), VRL compiler is using ANSI codes (correct):
```
$ vector -c vector.yaml --color always 2>&1 | less -F
ESC[2m2022-02-17T15:45:46.935425ZESC[0m ESC[32m INFOESC[0m ESC[2mvector::appESC[0mESC[2m:ESC[0m Log level is enabled. ESC[3mlevelESC[0mESC[2m=ESC[0m"vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
ESC[2m2022-02-17T15:45:46.935777ZESC[0m ESC[32m INFOESC[0m ESC[2mvector::appESC[0mESC[2m:ESC[0m Loading configs. ESC[3mpathsESC[0mESC[2m=ESC[0m["vector.yaml"]
ESC[2m2022-02-17T15:45:46.938316ZESC[0m ESC[31mERRORESC[0m ESC[2mvector::topologyESC[0mESC[2m:ESC[0m Configuration error. ESC[3merrorESC[0mESC[2m=ESC[0mTransform "remap":
ESC[0mESC[1mESC[38;5;9merror[E203]ESC[0mESC[1m: syntax errorESC[0m
  ESC[0mESC[34m┌─ESC[0m :1:11
  ESC[0mESC[34m│ESC[0m
ESC[0mESC[34m1ESC[0m ESC[0mESC[34m│ESC[0m if broken ESC[0mESC[31minESC[0m purpose { ... }
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31m^^ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31m│ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[31munexpected syntax token: "Identifier"ESC[0m
  ESC[0mESC[34m│ESC[0m           ESC[0mESC[34mexpected one of: "\n", "!=", "%", "&&", ")", "*", "+", ",", "-", "/", ";", "<", "<=", "==", ">", ">=", "??", "]", "{", "|", "|", "||", "}"ESC[0m
  ESC[0mESC[34m│ESC[0m
  ESC[0mESC[34m=ESC[0m see language documentation at https://vrl.dev
```

When running the first example without piping to `less`, you get colored Vector logging as expected. Therefore, the coloring in Vector logging is correctly detecting if the terminal is a TTY, but not the VRL compiler.

The problem with all this is that sometimes users in our team run Vector inside subpar terminals, for example the standard Windows Console (not Powershell nor Windows Terminal) and when they try to copy/paste VRL errors for me to help them, I get all the ANSI color codes embedded and thus unreadable content.

Therefore having a working `--color never` CLI argument would be very helpful for us.
While not our particular use-case, I can see this behaviour being problematic in CI jobs too that do not process ANSI color codes.

### Configuration

```text
sources:
  logs:
    type: demo_logs
    format: syslog

transforms:
  remap:
    type: remap
    inputs:
      - logs
    source: |-
      if broken in purpose { ... }

sinks:
  blackhole:
    type: blackhole
    inputs:
      - remap
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)

**Comment by spencergilbert** [comment] 2022-02-17 15:52
Hi @hhromic thanks for the issue, it is unfortunately a duplicate of https://github.com/vectordotdev/vector/issues/7551 that we haven't gotten to prioritize yet. Please drop a 👍 over there to help get it prioritized!

**Closed by spencergilbert** 2022-02-17 15:52 UTC

**Comment by spencergilbert** [comment] 2022-02-17 15:56
Nah, I can almost never find what I'm looking for when I search - I just remembered seeing it from a recent issue that referred to it 😄
