### ISSUE TITLE
AWS S3 sink, reload ~/.aws/credentials

### ISSUE THREAD

**Issue by nevenr** [vectordotdev/vector#19298] opened 2023-12-04 15:39 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

AWS credentials are regularly (~1h) provided to ~/.aws/credentials by third party solution.
Before tokens in credentials file expire third party solution renew them and update file.

We use those credentials to ship logs to AWS bucket.

On vector start it works as expected but after token rotation vector does not get new token and just report error with AWS S3 sink.

### Attempted Solutions

No solution.

### Proposal

Introduce some mechanism to reload credentials from file:

- use existing while working and when "ExpiredToken" error occurs reload credentials  file
- monitor credentials file for changes and when change is detected then reload
- configuration parameter to define timeout for recurrent credentials file reload
- or something else

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

**Comment by jszwedko** [comment] 2023-12-04 16:06
Thanks @nevenr !

I think this is a duplicate of https://github.com/vectordotdev/vector/issues/18591 . I'll close this out, but let me know if you disagree.

I'd recommend using https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html which does handle extrenal credential reload when the credentials expire.

**Closed by jszwedko** 2023-12-04 16:06 UTC
Labels: type: feature
