### ISSUE TITLE
certificate verify failed, unable to get local issuer certificate [Windows]

### ISSUE THREAD

**Issue by JohannesM24** [vectordotdev/vector#13238] opened 2022-06-20 15:26 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector does not connect to datadog sinks, having tried datadog_logs and datadog_metrics. On the same machine a datadog agent runs and sends data successfully.

I have seen some recent commits on TLS for those sinks, and also some related issues, e.g.  the last comment on https://github.com/vectordotdev/vector/issues/2256 seems to have a similar problem., but for me even setting `tls.verify_certificate = false` does not seem to make a difference.

We also have a setup with intermediary proxies and we were not sure if there could be a problem with SSL inspection.

Could you have a look into the issue and assist in debugging this?
I tested this on various Windows machines.

Additionally, also a curl to `https://api.datadoghq.eu/api/v1/validate` runs successfully.

I am happy to help with additional information, just let me know.

### Configuration

```text
data_dir = "G:\\Vector"

[proxy]
http = "http://***:***"
https = "http://***:***"

[sources.file_logger]
type = "file"
ignore_older_secs = 600
include= [ "G:\\Datadog_test_logs\\*" ]
read_from = "beginning"

[sinks.datadog_logs]
type = "datadog_logs"
inputs = [ "file_logger" ]
default_api_key = "***"
compression = "gzip"
site = "datadoghq.eu"
```

### Version

vector 0.22.2 (x86_64-pc-windows-msvc 0024c92 2022-06-15)

### Debug Output

```text
C:\Program Files\Vector>vector -vvv --require-healthy true
2022-06-20T15:10:09.486457Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,kube=trace"
2022-06-20T15:10:09.487568Z  INFO vector::app: Loading configs. paths=["C:\\Program Files\\Vector\\config\\vector.toml"]
2022-06-20T15:10:09.500662Z DEBUG vector::topology::builder: Building new source. component=file_logger
2022-06-20T15:10:09.501554Z DEBUG vector::topology::builder: Building new sink component=datadog_logs
2022-06-20T15:10:09.512769Z DEBUG vector::tls::settings: Fetching system root certs.
2022-06-20T15:10:09.527015Z  INFO vector::topology::running: Running healthchecks.
2022-06-20T15:10:09.527926Z DEBUG http: vector::internal_events::http_client: Sending HTTP request. uri=https://api.datadoghq.eu/api/v1/validate method=GET version=HTTP/1.1 headers={"dd-api-key": "***", "user-agent": "Vector/0.22.2 (x86_64-pc-windows-msvc 0024c92 2022-06-15)", "accept-encoding": "identity"} body=[empty]
2022-06-20T15:10:09.637147Z ERROR http: vector::internal_events::http_client: HTTP error. error=error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1916: error_type="request_failed" stage="processing"
2022-06-20T15:10:09.637703Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1916: component_kind="sink" component_type="datadog_logs" component_id=datadog_logs component_name=datadog_logs
2022-06-20T15:10:09.639969Z ERROR vector::topology::running: Sinks unhealthy.
```

### References

https://github.com/vectordotdev/vector/issues/2256

**Comment by jszwedko** [comment] 2022-06-20 16:07
Hi @JohannesM24 !

I think you might be running into the same issue as https://github.com/vectordotdev/vector/issues/10107 . A workaround (mentioned on that issue) is to force TLS 1.2:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

It still isn't clear to us why this happens, though, or if this is something we could make a change in Vector to avoid which is why the issue is still open.

**Comment by JohannesM24** [comment] 2022-06-20 17:41
Hi @jszwedko 

thanks for the quick answer. Actually i saw this suggestion aswell, but it does not seem to work. I guess I am supposed to set the command in powershell and call vector from there?

![image](https://user-images.githubusercontent.com/18679023/174652123-548bd9e2-4cf5-431a-8456-cb5a0583ceb5.png)

I also tried only allowing TLS 1.2 in `Internet Options -> Advanced` , but it did not help.

I have also read some articles that recommend changing registry keys in `HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols`
to force TLS 1.2 in SChannel , but before doing this I would need to consult with the server admin and I am still not sure if this would even help.

Regarding  https://github.com/vectordotdev/vector/issues/10107 there is a slighty different error message, hinting at a self signed certificate in the chain.

`
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1916:: self signed certificate in certificate chain`

while in my case it says 
`error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1916: error_type="request_failed" stage="processing"`

I am sadly not too strong in https or ssl, else I could maybe try to read something out from that.

Do you maybe have another try for a work around or help for debugging?

**Comment by neuronull** [comment] 2023-02-15 23:40
I tried reproducing this, but so far have been unable to.

```
$ cat ./config/vector.toml

data_dir = "C:\\Program Files\\Vector-v0.22.2\\logs"

[sources.file_logger]
type = "file"
ignore_older_secs = 600
include= [ "C:\\Datadog_test_logs\\*" ]
read_from = "beginning"

[sinks.datadog_logs]
type = "datadog_logs"
inputs = [ "file_logger" ]
default_api_key = "<REDACTED>"
compression = "gzip"
```

```
$ ./bin/vector.exe -vvv -c ./config/vector.toml --require-healthy true
2023-02-15T23:35:27.844196Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,kube=trace"
2023-02-15T23:35:27.844623Z  INFO vector::app: Loading configs. paths=["config\\vector.toml"]
2023-02-15T23:35:27.846527Z DEBUG vector::topology::builder: Building new source. component=file_logger
2023-02-15T23:35:27.847154Z DEBUG vector::topology::builder: Building new sink component=datadog_logs
2023-02-15T23:35:27.849949Z DEBUG vector::tls::settings: Fetching system root certs.
2023-02-15T23:35:27.856659Z  INFO vector::topology::running: Running healthchecks.
2023-02-15T23:35:27.856806Z DEBUG http: vector::internal_events::http_client: Sending HTTP request. uri=https://api.datadoghq.com/api/v1/validate method=GET version=HTTP/1.1 headers={"dd-api-key": "<REDACTED>", "user-agent": "Vector/0.22.2 (x86_64-pc-windows-msvc 0024c92 2022-06-15)", "accept-encoding": "identity"} body=[empty]
2023-02-15T23:35:28.161853Z DEBUG http: vector::internal_events::http_client: HTTP response. status=200 OK version=HTTP/1.1 headers={"date": "Wed, 15 Feb 2023 23:35:28 GMT", "content-type": "application/json", "content-length": "15", "connection": "keep-alive", "x-content-type-options": "nosniff", "strict-transport-security": "max-age=15724800;", "content-security-policy": "frame-ancestors 'self'; report-uri https://logs.browser-intake-datadoghq.com/api/v2/logs?dd-api-key=<REDACTED>-evp-origin=content-security-policy&ddsource=csp-report&ddtags=site%3Adatadoghq.com", "x-frame-options": "SAMEORIGIN"} body=[15 bytes]
2023-02-15T23:35:28.161987Z  INFO vector::topology::builder: Healthcheck: Passed.
2023-02-15T23:35:28.162009Z  INFO vector::topology::running: All healthchecks passed.
```

Maybe something is going on with your proxy?

Have you tried this running this configuration recently, or with the latest version of Vector?

**Comment by jszwedko** [comment] 2023-09-28 02:01
Closing due to our lack of ability to reproduce. If anyone has a reproduction case, please drop a note here!

**Closed by jszwedko** 2023-09-28 02:01 UTC
Labels: type: bug, platform: windows, sink: datadog_logs
