### ISSUE TITLE
Debugging kubernetes_logs reader_failed error

### ISSUE THREAD

**Issue by mjperrone** [vectordotdev/vector#14354] opened 2022-09-09 17:37 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Using the `kubernetes_logs` sink we see a large number of `error_type:reader_failed` errors emitted at `component_errors_total`. We also see log lines like this:

```
2022-09-08T21:49:33.092072Z ERROR source{component_kind="source" component_id=kubernetes_logs component_type=kubernetes_logs component_name=kubernetes_logs}: vector::internal_events::kubernetes_logs: Failed to annotate event with pod metadata. event=Log(LogEvent { inner: Inner { fields: Object({"file": Bytes(b"<fpath>"), "message": Bytes(b"<valid json>"), "source_type": Bytes(b"kubernetes_logs"), "timestamp": Timestamp(2022-09-08T21:49:33.092035942Z)}), size_cache: AtomicCell { value: Some(1492) } }, metadata: EventMetadata { datadog_api_key: None, splunk_hec_token: None, finalizers: EventFinalizers([]), schema_definition: Definition { collection: Collection { known: {}, unknown: None }, meaning: {}, optional: {} } } }) error_code="annotation_failed" error_type="reader_failed" stage="processing"
```

I see the error tag produced [here](https://github.com/vectordotdev/vector/blob/f3603d40e5fffe270958d50bb7d0085972f8e22d/src/internal_events/kubernetes_logs.rs#L62). I searched the vector.dev website for `"reader_failed"` and didn't find anything. It [used](https://github.com/vectordotdev/vector/blob/d802cf2ee3bcab24ddd737910bb0e72c4dacd86a/src/internal_events/kubernetes_logs.rs#L55) to be `event_annotation` so I searched for that too. That at least pointed me to the [kuberenetes_logs](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/) source documentation, but it doesn't add any info around my questions past the error log message text.

I was able to find two related issues linked at the bottom section. Without more information about the error, I am not 100% sure this is a duplicate of either of them, though it is suspicious.

I have a few questions:

* What happens to the log event when this error is hit? 
* How do I found out _why_ the error happened? Is there a problem receiving the data from k8s? Problem adding the data?
* Am I missing any existing documentation around this?

### Configuration

```text
[sources.kubernetes_logs]
  type = "kubernetes_logs"
```

### Version

0.22.3

### Debug Output

```text
It is tricky to turn on debug logs for just one pod since this is deployed as a daemonset. I am afraid to turn on debug logs for all the pods due to the performance implication and the risk of a circular collection dependency.

I have been looking for workarounds like turning on debug logging from the gql api, or using `--watch-config` and then live editing the config to turn on debug logging. Unfortunately neither of these things are possible. The best idea I can think of is to taint a pod, have the daemonset exclude the tainted nodes, then manually start a pod on the tainted node with a verbose vector agent.

I suppose I'm asking another question: do folks know a good way to enable debug logging for single pod in an infra like this?
```

### References

https://github.com/vectordotdev/vector/issues/12014
https://github.com/vectordotdev/vector/issues/13467

**Comment by jszwedko** [comment] 2022-09-13 21:39
Hi @mjperrone !

This seems likely to be the same as https://github.com/vectordotdev/vector/issues/13467 . I'm curious if you think so too.

> * What happens to the log event when this error is hit?

The log event is passed through without being enriched with Kubernetes metadata (like the pod namespace).

> * How do I found out _why_ the error happened? Is there a problem receiving the data from k8s? Problem adding the data?

I _think_ this is likely to be due to https://github.com/vectordotdev/vector/issues/13467 but in general it means that Vector doesn't have the Kubernetes metadata cached to collate with the pod ID.

> * Am I missing any existing documentation around this?

https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#enrichment has some information about the enrichment process, but it doesn't discuss this particular error or why it might occur.

**Comment by mjperrone** [comment] 2022-10-13 16:44
More conversation in [this discord thread](https://discord.com/channels/742820443487993987/746070591097798688/1017851672027992104)

**Comment by jszwedko** [comment] 2022-10-26 17:56
Closing as a likely duplicate of https://github.com/vectordotdev/vector/issues/13467

**Closed by jszwedko** 2022-10-26 17:56 UTC
Labels: type: bug, source: kubernetes_logs
