### ISSUE TITLE
Add name of the input to the Event metadata

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#11935] opened 2022-03-22 15:45 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Say you have a remap transform that can take input from two different sources.

### Attempted Solutions

Currently you would have to create a separate remap transform for each source that adds a field to the event to identify the source.

### Proposal

It would be useful for that transform to be able to identify the source that the event has come from. Would it be possible to add this to the `Event` metadata?

### Version

v0.20

**Comment by hhromic** [comment] 2022-03-22 16:49
Duplicate of https://github.com/vectordotdev/vector/issues/11544 ? :)

**Comment by jszwedko** [comment] 2022-03-22 18:22
Yeah, good catch, I was thinking this was more general than #11544, but, as written, it is a duplicate of that issue. I'll close it in-lieu of that one.

**Closed by jszwedko** 2022-03-22 18:22 UTC
Labels: domain: topology, type: feature
