### ISSUE TITLE
Allow overriding the vector version with the vector installation script (`https://sh.vector.dev`)

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#18321] opened 2023-08-21 14:13 UTC
### A note for the community

The Vector version is currently hard-coded to the latest version. It would be nice if an argument could override that and set an older version.

Hard-coded version: https://github.com/vectordotdev/vector/blob/d3a623540ec08e63dd3b075614159db663ac0dc2/distribution/install.sh#L15

Discord question: https://discord.com/channels/742820443487993987/1142799019345707048/1142799019345707048

**Comment by jszwedko** [comment] 2023-08-21 15:01
This looks to be a duplicate of https://github.com/vectordotdev/vector/issues/5033

**Closed by jszwedko** 2023-08-21 15:01 UTC
Labels: type: feature, domain: setup
