### ISSUE TITLE
Compression on gcp_cloud_storage sink mangles data

### ISSUE THREAD

**Issue by jdoupe** [vectordotdev/vector#12826] opened 2022-05-23 23:24 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

`gcp_cloud_storage` sink with compression set to `gzip` causes data to be malformed in some circumstances.  I can reliably reproduce (unfortunately with a dataset that I can't publish - and on a couple attempts to mask the data, the issue doesn't present itself).

With the same dataset and configuration on version `0.21.2`, the corruption does not occur.

### Configuration

```text
[sinks.gcs]
type = "gcp_cloud_storage"
inputs = ["parse_logs"]
encoding = "text"
bucket = "my-logs"
credentials_path = "/path/to/creds/creds.json"
key_prefix = "mypath/"
compression = "gzip"
batch.max_bytes = 104857600
batch.timeout_secs = 60
buffer.type = "memory"
buffer.max_events = 6000000
buffer.when_full = "block"
storage_class = "STANDARD"
```

### Version

vector 0.22.0 (x86_64-unknown-linux-gnu b002bfb 2022-05-22)

**Comment by jdoupe** [comment] 2022-05-24 19:34
The corruption is post decompression.  It appears that one record is chopped, and the next record continues on the same line.  I've tried to generate random data (with same fields, about the same size) with no luck.  I believe I HAVE managed to mask my data sufficiently to pass on.

**Comment by jszwedko** [comment] 2022-05-24 22:21
Hi @jdoupe !

If you are able to provide the masked data, that would be very helpful since we haven't been able to reproduce yet. If you don't want to post here, you can also email it to jesse.szwedko@datadoghq.com.

**Comment by bruceg** [comment] 2022-05-25 14:22
While I'm trying to reproduce this locally with the data you provided (thank you), could I get you to verify a couple of things for me to help narrow down my bug search:
1. Does this corruption also happen with the identical config but with compression disabled?
2. Does this corruption also happen with a different sink, like `file`?
3. What is the source the events are coming from?

**Comment by jdoupe** [comment] 2022-05-25 14:57
Apologies for excluding that info...

1. No.  Disabling compression produces correct results.
2. No.  I was unable to reproduce using `file` sink.
3. Source for reproducing is just `file`.

**Comment by bruceg** [comment] 2022-05-25 18:25
I have reproduced this and bisected it down to 1daba0d61088bd8f4df7426285152fcd445f5165 #12488 which is where the new Encoder framework was integrated into the `gcp_cloud_storage` sink. This may, then, affect more sinks than just GCS.

I will take a look at building a minimal reproducer that doesn't involve GCP. @pablosichert I will be interested to hear your thoughts on this.

**Closed** 2022-05-26 16:57 UTC
Labels: type: bug, meta: regression, sink: gcp_cloud_storage, domain: codecs

**Comment by jdoupe** [comment] 2022-05-26 23:01
Confirmed fixed as well.  Many thanks!
