### ISSUE TITLE
filter nested json objects (escaping)

### ISSUE THREAD

**Issue by dzirg44** [vectordotdev/vector#5709] opened 2020-12-24 12:43 UTC
Hi!
### Current Vector Version

docker image
```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)
```

### Use-cases

i have logs 
```json
{
   "file":"/log/file.json",
   "kubernetes":{
      "pod_labels":{
         "application.env":"dev"
      }
   }
}
```
and want to filter it by `pod_labels`

I tried to do this through

```json
  "transforms": {
    "vector_filter": {
       "condition": {
         "kubernetes.pod_labels.application.env.exists" : true
       },
      "inputs" : [
        "vector"
      ],
      "type" : "filter"
    }
  },
```
but it seems it doesn't work

### Attempted Solutions

i tried to escape it via `\` but I received the error
```
 ERROR vector::cli: Configuration error. error=invalid escape at line 34 column 45
```
in case if i don't have dots - everything works as expected.

**Comment by dzirg44** [comment] 2020-12-24 13:02
it seems it worked before
#3057

**Comment by dzirg44** [comment] 2020-12-24 13:09
solved by
```
         "kubernetes.pod_labels.application\\.env.exists" : true
```
btw, looks a little bit strange, but it works)

**Comment by juchiast** [comment] 2021-01-04 01:49
Hi @dzirg44, It is documented here https://vector.dev/docs/reference/field-path-notation/ , but I'm not sure how to reach this page from the homepage (found it through a search). 

@binarylogic I think it should be included in https://vector.dev/docs/reference/configuration/ ?

**Comment by juchiast** [comment] 2021-01-04 01:52
Ok it's here https://vector.dev/docs/reference , but I don't think there is a link to this page in the left column.

**Comment by dzirg44** [comment] 2021-01-05 08:22
@juchiast I agree with you, but it is not so obvious, for example
according to the documentation I expect something like
```
"kubernetes.pod_labels.application\.env.exists" : true
```
has to work, but not
```
"kubernetes.pod_labels.application\\.env.exists" : true
```

**Comment by juchiast** [comment] 2021-01-05 08:57
Yeah, you need to use single-quoted string for that to work. 

I'll add an example to the page instead of only mentioning it
> The \ character, if used literally, must be escaped with a \ as well.

**Comment by dzirg44** [comment] 2021-04-14 10:13
due to latest changes when we work with nested json objects in VRL we should use 
```json
    "vector_filter": {
       "inputs": ["vector_json"],
       "condition": ".kubernetes.pod_labels.\"application.scrape_logs\" == \"true\"",
       "type": "filter"
    }
```
maybe it would be nice to have it in the documentation.

**Comment by arbourd** [comment] 2021-10-09 19:08
Found it:https://vector.dev/docs/reference/vrl/expressions/#path-example-quoted-path

**Comment by jszwedko** [comment] 2022-08-05 22:06
Closing since this appears to have been resolved by escaping the fields with `.`s in them.

**Closed by jszwedko** 2022-08-05 22:06 UTC
Labels: type: enhancement

**Comment by sojjan1337** [comment] 2024-09-24 14:22
Hi! 

Using helm to install vector.

This works:

`labels: "{{\"{{ kubernetes.pod_labels }}\"}}"`


This does not work:

`app: "{{\"{{ kubernetes.pod_labels.app_kubernetes_io/name }}\"}}"`


`Configuration error. error=Invalid field path in template "kubernetes.pod_labels.app_kubernetes_io/name"`

**Comment by jszwedko** [comment] 2024-09-24 14:53
I believe you want: `app: "{{\"{{ kubernetes.pod_labels.\"app_kubernetes_io/name\" }}\"}}"`

Paths with special characters must be quoted.

**Comment by sojjan1337** [comment] 2024-09-25 06:18
Hi! Tried it, i get this error:

`Error: template: vector/templates/daemonset.yaml:30:28: executing "vector/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: vector/templates/configmap.yaml:11:3: executing "vector/templates/configmap.yaml" at <tpl (toYaml .Values.customConfig) .>: error calling tpl: error during tpl function execution type: remap": parse error at (vector/templates/daemonset.yaml:29): bad character U+002F '/'`

**Comment by jszwedko** [comment] 2024-09-25 13:17
How about:

```
app: {{ "{{" }} kubernetes.pod_labels."app_kubernetes_io/name" {{ "}}" }}
```

I think the issue is that `{{` is also the Helm template character as well as being the Vector string template character.

**Comment by jszwedko** [comment] 2024-09-25 13:26
Can you share your full Helm config? It sounds like like there might be a field missing.

**Comment by sojjan1337** [comment] 2024-09-25 13:34
```
image:
  repository: "harbor.se/dssc/docker_registry.hub.docker.com-r/timberio/vector"

service:
  enabled: false

role: "Agent"

customConfig:
  data_dir: "/vector_data"
  api:
    enabled: true
    address: 127.0.0.1:8686

  sources:
    vector_metrics:
      type: internal_metrics
      namespace: vector
      scrape_interval_secs: 1
    k8s_source:
      type: kubernetes_logs
    local_source:
      type: file
      include:
        - /var/log/messages
        - /var/log/secure
        - /var/log/audit/audit.log
        - /var/log/sssd/*.log
    journald_source:
      type: journald
      journal_directory: /var/log/journal/

  transforms:
    local_remap:
      type: remap
      inputs:
        - local_source
      source: |
        .host.name = "$VECTOR_SELF_NODE_NAME"
        #. = {"log": .message, "file": .file }

    k8s_remap:
      type: remap
      inputs:
        - k8s_source
      source: |
        .host.name = .kubernetes.pod_node_name
        #. = {"log": .message, "kubernetes": .kubernetes }

    journal_remap:
      type: remap
      inputs:
        - journald_labels
      source: |
        .root."@timestamp" = .timestamp
        .root.message = .message
        .root.tags = .tags

        .root.labels = {
          "log_type": .source_type,
        }

        .root.event = {
          "dataset": .source_type
        }

        . = compact(.root, string: false, array: true, null: true)

    journald_labels:
      type: remap
      inputs:
        - journald_source
      source: |
        .root.journald = {
          "fields": {}
        }
        .root.host = {
            "name": del(.host),
            "architecture": del(.metadata.architecture),
            "type": del(.metadata.type)
        }
        .root.log = {
          "syslog": {
            "hostname": .host.name,
            "level": .PRIORITY,
            "priority": .PRIORITY,
            "msgid": .MESSAGE_ID,
            "procid": ._PID,
            "facility": {
              "code": .SYSLOG_FACILITY
            },
            "appname": .SYSLOG_IDENTIFIER
          }
        }

        # List of Journald fields
        # NOTE! All these fields will NOT be added to each event,
        #       it is only used as a filter to prevent excessive amount of JournalD fields per set
        journald_fields = [
          "MESSAGE_ID",
          "PRIORITY",
          "CODE_FILE",
          "CODE_LINE",
          "CODE_FUNC",
          "ERRNO",
          "INVOCATION_ID",
          "USER_INVOCATION_ID",
          "SYSLOG_FACILITY",
          "SYSLOG_IDENTIFIER",
          "SYSLOG_PID",
          "SYSLOG_TIMESTAMP",
          # "SYSLOG_RAW",
          # "DOCUMENTATION",
          "TID",
          "UNIT",
          "USER_UNIT",
          "_PID",
          "_UID",
          "_GID",
          "_COMM",
          "_EXE",
          "_CMDLINE",
          "_CAP_EFFECTIVE",
                "_AUDIT_SESSION",
                "_AUDIT_LOGINUID",
                "_SYSTEMD_CGROUP",
                "_SYSTEMD_SLICE",
                "_SYSTEMD_UNIT",
                "_SYSTEMD_USER_UNIT",
                "_SYSTEMD_USER_SLICE",
                "_SYSTEMD_SESSION",
                "_SYSTEMD_OWNER_UID",
                "_SELINUX_CONTEXT",
                "_SOURCE_REALTIME_TIMESTAMP",
                "_BOOT_ID",
                "_MACHINE_ID",
                "_SYSTEMD_INVOCATION_ID",
                "_HOSTNAME",
                "_TRANSPORT",
                "_STREAM_ID",
                "_LINE_BREAK",
                "_NAMESPACE",
                "_RUNTIME_SCOPE",
                "_KERNEL_DEVICE",
                "_KERNEL_SUBSYSTEM",
                "_UDEV_SYSNAME",
                "_UDEV_DEVNODE",
                "_UDEV_DEVLINK"
              ]

              # Populate the .labels map with all labels found in "journald_fields"
              for_each(journald_fields) -> |_, field| {
                value = get!(., [field])
                if value != null {
                  .root.journald.fields = set!(.root.journald.fields, [downcase(field)], value)
                }
              }

  sinks:
    prom_remwri:
      type: prometheus_remote_write
      inputs:
        - vector_metrics
      tenant_id: PLACEHOLDER_CLUSTER_ID
      endpoint: https://mimir.se/api/v1/push
      tls:
        ca_file: /etc/pki/tls/certs/cacerts.crt

    # stdout:
    #   type: console
    #   inputs:
    #     - k8s_remap
    #   encoding:
    #     codec: json

    loki_k8s:
      type: loki
      inputs:
        - k8s_remap
      endpoint: https://loki.se
      path: /loki/api/v1/push
      labels:
        # labels_*: "{{\"{{ kubernetes.pod_labels }}\"}}"
        app: {{ "{{" }} kubernetes.pod_labels."app_kubernetes_io/name" {{ "}}" }}
        # cluster: PLACEHOLDER_CLUSTER_ID
        # component: "{{\"{{kubernetes.pod_labels.\\\"app_kubernetes_io/component\\\"}}\"}}"
        # container: "{{\"{{kubernetes.container_name}}\"}}"
        # instance: "{{\"{{kubernetes.pod_labels.\\\"app_kubernetes_io/instance\\\"}}\"}}"
        # job: {{ "{{" batch."kubernetes.io/job-name" {{ "}}" }}"
        # namespace: "{{\"{{ kubernetes.pod_namespace }}\"}}"
        # node_name: "{{\"{{kubernetes.pod_node_name}}\"}}"
        # pod: "{{\"{{kubernetes.pod_name}}\"}}"
        # pod_ip: "{{\"{{kubernetes.pod_ip}}\"}}"
      tenant_id: PLACEHOLDER_CLUSTER_ID
      encoding:
        codec: json
        except_fields:
          - kubernetes
      tls:
        ca_file: /etc/pki/tls/certs/cacerts.crt

    loki_local:
      type: loki
      inputs:
        - local_remap
      endpoint: https://loki.se
      path: /loki/api/v1/push
      labels:
        filename: "{{\"{{file}}\"}}"
      tenant_id: PLACEHOLDER_CLUSTER_ID
      encoding:
        codec: json
        except_fields:
          - file
      tls:
        ca_file: /etc/pki/tls/certs/cacerts.crt

    # kafka:
    #   type: kafka
    #   inputs:
    #     - k8s_remap
    #     - journal_remap
    #     - local_remap
    #   bootstrap_servers: "xxxxxx:9093,xxxxxxxx:9093,xxxxxxxxx:9093"
    #   topic: xxx
    #   compression: gzip
    #   encoding:
    #     codec: json
    #   tls:
    #     enabled: true
    #     ca_file: /etc/pki/tls/certs/cacerts.crt

extraVolumes:
  - name: journalctl-binary
    hostPath:
      path: /usr/bin/journalctl
  - name: journalctl-libs1
    hostPath:
      path: /usr/lib64/systemd/
  - name: journalctl-libs2
    hostPath:
      path: /lib64/
  - name: ca-trust
    configMap:
      name: ca-trust
      defaultMode: 420

extraVolumeMounts:
  - name: journalctl-binary
    mountPath: /usr/bin/journalctl
    readOnly: true
  - name: journalctl-libs1
    mountPath: /usr/lib64/systemd/
    readOnly: true
  - name: journalctl-libs2
    mountPath: /lib64/
    readOnly: true
  - name: ca-trust
    mountPath: /etc/pki/tls/certs
    readOnly: true


```

**Comment by sojjan1337** [comment] 2024-09-26 12:26
@jszwedko did your magic eyes find anything? ;) ^_^

**Comment by jszwedko** [comment] 2024-09-26 15:48
YAML templating is hard 😅 

This seems to work:

```yaml
      labels:
        app: >
          {{ `{{ kubernetes.pod_labels."app_kubernetes_io/name" `}}` }}
```

**Comment by sojjan1337** [comment] 2024-09-27 05:25
Thanks for all the help. Tried it. Gave me:

```
2024-09-27T05:23:47.780549Z ERROR vector::cli: Configuration error. error=Invalid field path in template "kubernetes.pod_labels.\"app_kubernetes_io/name\" `" (see https://vector.dev/docs/reference/configuration/template-syntax/)




in `sinks.loki_k8s`
```

**Comment by jszwedko** [comment] 2024-09-27 21:07
Doh, sorry, I had an extra backtick in there. It should be:

```yaml
      labels:
        app: >
          {{ `{{ kubernetes.pod_labels."app_kubernetes_io/name" }}` }}
```

**Comment by jszwedko** [comment] 2024-09-30 13:57
One step closer! That would indicate, as the error says, that the incoming events don't have that field present. You could use `vector tap` to examine the events as the flow into the sink.

**Comment by sojjan1337** [comment] 2024-10-04 07:51
The only label that is activated is:

```
      labels:
        app: >
          {{ `{{ kubernetes.pod_labels."app_kubernetes_io/name" }}` }}
```

vector pod seems to have no bash.

You can do this:

`k exec -it vector-7dfbx -- vector tap | grep app.kubernetes.io | jq`

When i'm doing this i can see:

`"app.kubernetes.io/instance": "driver-test",`

and when i'm doing this:
`k exec -it vector-7dfbx -- vector tap | grep app.kubernetes.io`

`Helm","app.kubernetes.io/name":`

And this:
`k exec -it vector-7dfbx -- vector tap | grep pod_labels`

`"pod_labels":{"app":"driver-test","app.kubernetes.io/instance":"driver-test","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"driver-test",`


What happens if the label is empty under pod_labels? I still can't see the app label in grafana.
The only label i can see in grafana is "agent"

```
WARN sink{component_kind="sink" component_id=loki_k8s component_type=loki}: vector::internal_events::template: Internal log
[Failed to render template for "label_value "{{ kubernetes.pod_labels."app_kubernetes_io/name" }}
" with label_key "app"".] is being suppressed to avoid flooding.
2024-10-04T07:40:32.290120Z ERROR sink{component_kind="sink" component_id=loki_k8s component_type=loki}: vector::internal_events::loki: Internal log [Event had no labels. Adding default agent label.] is being suppressed to avoid flooding.
```

**Comment by jszwedko** [comment] 2024-10-04 22:34
If the label is empty, I think you will see error you are currently seeing. You could use a `remap` transform to set a default value like:

```
if .labels.app == null {
  .labels.app = "some default"
}
```

**Comment by jszwedko** [comment] 2024-10-08 17:50
It looks like you aren't assigning the label in the sink. Maybe something like:

```yaml
k8s_remap:
  type: remap
  inputs:
    - k8s_source
    source: |    
        if .kubernetes.pod_labels."app_kubernetes.io/name" != null {
          .labels.app = .kubernetes.pod_labels."app.kubernetes.io/name"
        } else {
          .labels.app = "unknown"
        }
```

and in the sink:

```
loki_k8s:
  type: loki
  inputs:
    - k8s_remap
   endpoint: sdfsdfsdf
   path: rrsdfsdfsd
   labels:
     app: >
       {{ `{{ .labels.app }}` }}
#      app: >
#          {{ `{{ kubernetes.pod_labels."app_kubernetes_io/name" }}` }}
     cluster: CLUSTER_ID
```

?

**Comment by sojjan1337** [comment] 2024-10-10 12:03
Now it works!

Thanks!

```
k8s_remap:
  type: remap
  inputs:
    - k8s_source
    source: |    
        if .kubernetes.pod_labels."app.kubernetes.io/name" != null {
          .labels.app = .kubernetes.pod_labels."app.kubernetes.io/name"
        } else {
          .labels.app = "unknown"
        }

```


```
loki_k8s:
  type: loki
  inputs:
    - k8s_remap
   endpoint: sdfsdfsdf
   path: rrsdfsdfsd
   labels:
     app: "{{\"{{ .labels.app }}\"}}"
     cluster: CLUSTER_ID
```
