### ISSUE TITLE
Regex Parser Documentation examples not working

### ISSUE THREAD

**Issue by SyluxDX** [vectordotdev/vector#4788] opened 2020-10-28 11:50 UTC
The Documentation on the transformation Regex Parser is incorrect and both the configuration and example for the field *patterns* gives an error and crashes vector on startup

### Vector Version
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Vector Configuration File
```toml
[transforms.regex]
    type = "regex_parser"
    inputs = ["input"]
    field = "msg"
    overwrite_target = true
    patterns = "['^(?P<timestamp>[\\w\\-:\\+]+) (?P<level>\\w+) (?P<message>.*)$']"
```

### Debug Output
```
Oct 28 11:39:10.500  INFO vector: Log level "info" is enabled.
Oct 28 11:39:10.506  INFO vector::topology::config::watcher: Creating configuration file watcher.
Oct 28 11:39:10.513  INFO vector::topology::config::watcher: Watching configuration files.
Oct 28 11:39:10.514  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Oct 28 11:39:10.517 ERROR vector: Configuration error: "/etc/vector/vector.toml": invalid type: string "[\'^(?P<timestamp>[\\w\\-:\\+]+) (?P<level>\\w+) (?P<message>.*)$\']", expected a sequence for key `transforms.version_regex`
```

**Comment by jszwedko** [comment] 2020-10-28 13:36
Just noting for when this is picked up that I believe the issue is that the value for patterns is wrapped in `"`s.

**Comment by jszwedko** [comment] 2022-08-04 21:36
Closing since the `regex_parser` transform no longer exists.

**Closed by jszwedko** 2022-08-04 21:36 UTC
Labels: type: bug, domain: transforms
