### ISSUE TITLE
--config-yaml fails if config doesn't have yaml extension

### ISSUE THREAD

**Issue by amravyan** [vectordotdev/vector#10186] opened 2021-11-29 08:17 UTC
Found and interesting issue with vector validate command: it fails if i specify `--config-yaml` but config actually doesn't have yml extension
Could you please investigate this bug?

v0.18.0
```
 [root@test2 ~]# vector validate --config-yaml /root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source
 Failed to load ["/root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source"]
 -------------------------------------------------------------------------------------------
 x expected an equals, found a colon at line 12 column 9
  
 [root@test2 ~]# vector validate --config-yaml /root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source.yml
 √ Loaded ["/root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source.yml"]
 √ Component configuration
 √ Health check "output-kafka"
 -----------------------------------------------------------------------------------------
                                                                                  Validated
 [root@test2 ~]# diff -s /root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source /root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source.yml
 Files /root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source and /root/.ansible/tmp/ansible-tmp-1637918351.5709512-273358672672511/source.yml are identical
```

**Comment by darren-fhf** [comment] 2022-01-05 17:21
This appears to have been fixed by  e14acc7f30.

I am unable to reproduce the problem with 0f1aa9a6bd.

**Comment by spencergilbert** [comment] 2022-01-05 17:32
Thanks @darren-fhf - this does appear to be resolved on the latest release. @amravyan please let us know if you're still running into this issue.

**Closed by spencergilbert** 2022-01-05 17:32 UTC
Labels: type: bug, domain: config
