### ISSUE TITLE
azure blob storage sink not working 

### ISSUE THREAD

**Issue by doriwal** [vectordotdev/vector#17782] opened 2023-06-28 14:53 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I used connection string according to documentation and get error msg: 
"Healthcheck failed." error=failed to execute `reqwest` request component_kind="sink" component_type="azure_blob" component_id=mysink component_name=mysink

source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1921 }]))) }, X509VerifyResult { code: 19, error: "self signed certificate in certificate chain" })) } }, "failed to execute `reqwest` request") }) request_id=1 error_type="request_failed" stage="sending" internal_log_rate_limit=true

### Version

    image: timberio/vector:0.28.1-debian

**Comment by jszwedko** [comment] 2023-06-28 15:20
Hi @doriwal !

Could you please provide the configuration you used? That will be important for reproducing this. At first blush it looks like the endpoint you are using is using a certificate that Vector doesn't trust.

**Comment by doriwal** [comment] 2023-06-28 17:51
Please ignore it was a network issue at the office that failed the connection 
small question - does the connection_string that vector.dev expect to get is limited to accessKey or it can also include SAS like in https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-using-a-shared-access-signature ?

**Comment by jszwedko** [comment] 2023-06-28 18:17
Thanks for following up @doriwal ! I'll close this issue.

SAS should be supported; we just haven't fully documented it yet. A user was able to get it working with the steps you see on https://github.com/vectordotdev/vector/issues/15394

**Closed by jszwedko** 2023-06-28 18:17 UTC
Labels: type: bug

**Comment by doriwal** [comment] 2023-06-28 19:30
Thanks for the answer :-)

Question about blob storage support for managed identity 
https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview-for-developers?tabs=portal%2Cdotnet

does it mean i can create several sink's each with different managed identity 
how exactly managed identity is supported ? i need to provide in storage_account the client_id ?
is there an example of the payload, its not clear from documentation
is there some assumption like it only works if vector.dev is running in azure env but not from aws env ?

**Comment by jszwedko** [comment] 2023-06-28 19:36
Hi @doriwal ,

I've never used Azure managed identities, but I believe it would mean running Vector on Azure infrastructure to make use of them. The page you linked reinforces this belief.

I think it also means that you couldn't have one Vector with multiple sinks using different managed identities since the credentials are pulled from Azure resources. Again I've never actually used managed identities so I could be wrong.
