### ISSUE TITLE
[http][source] ability to use protocol://domain:port/endpoint?params address

### ISSUE THREAD

**Issue by Diliz** [vectordotdev/vector#2696] opened 2020-05-27 14:27 UTC
Hello Timberio PPLs!

I actually opened a previous issue related to this one, here: https://github.com/timberio/vector/issues/2680 (seems identical, but it's more a proposal than a bug report here :) )

I opened a new one to ask it would be possible to just use any string as an http adress actually, instead of expecting a specific format?

My vector version:
```sh
vector --version
vector 0.9.1 (v0.9.1 x86_64-unknown-linux-musl 2020-04-30)
```

Here what I want to be able to do in my config:
```toml
[sources.test]
  type = "http"
  address = "api.region.something.something:port/my/endpoint/there?params_here...&..."
  encoding = "json"
```

The error it gives today:
```sh
vector --config druid/*.toml --dry-run -v
May 25 16:20:10.202  INFO vector: Log level "debug" is enabled.
May 25 16:20:10.202  INFO vector: Loading configs. path=["druid/pure_backend.toml"]
May 25 16:20:10.206 ERROR vector: Configuration error: "druid/pure_backend.toml": invalid IP 
address syntax for key `address` for key `sources.test`
```

Thanks for reading, and thanks for your work 👍

**Comment by lukesteensen** [comment] 2020-05-27 22:25
We require an IP address/port because the http source starts a server and needs to know where to listen.

It sounds like you would like a source that acts as an http client and makes requests to various endpoints. We don't currently have a generic version of that but please feel free to open an issue to request one!

**Comment by Diliz** [comment] 2020-05-28 07:13
Ok, I understand the point, I assumed it was simple http requests since it's making a post request with a provided body/headers etc...

I think having an other http source will just be confusing, actually it's already confusing that the http part can't use an alias but only ips, no endpoints and no params, there's lot of examples where you would fetch metrics simply by hitting a specific endpoint like this. I expect from an http source or sink to be able to make any kind of http requests actually :/

Thanks for your answers :)

**Comment by lukesteensen** [comment] 2020-05-28 14:53
> I assumed it was simple http requests since it's making a post request with a provided body/headers etc...

It is an HTTP server, so it does not make any requests at all. It receives requests.

> there's lot of examples where you would fetch metrics simply by hitting a specific endpoint like this

We have other sources that work this way. Prometheus is one example where we make HTTP requests to fetch metrics.

We could definitely have a generic http client sources, but as you state it would be somewhat confusing with the existing http server source. We would need to make sure to name and document them such that there is not this kind of confusion.

**Comment by Diliz** [comment] 2020-06-02 08:57
> It is an HTTP server, so it does not make any requests at all. It receives requests.

That makes sense yep, and it's a cool thing :)

Maybe just calling the actual http source httpReceiver or else

And if there's a new http client source, it can be httpSender or something like this ( just giving ideas ), so the two http sources describe what they do 👍

**Comment by hhromic** [comment] 2022-04-01 15:34
I think this issue evolved into becoming a duplicate of #3532 :)

**Comment by jszwedko** [comment] 2022-04-01 15:39
Yes indeed, I'll close this in-lieu of https://github.com/vectordotdev/vector/issues/3532. Thanks!

**Closed by jszwedko** 2022-04-01 15:39 UTC
Labels: needs: approval, type: help, meta: feedback, source: http
