### ISSUE TITLE
Failed to run on CentOS 8 due to page size differences

### ISSUE THREAD

**Issue by DocLM** [vectordotdev/vector#4392] opened 2020-10-05 16:27 UTC
### Vector Version
```
0.10.0
```

### Expected Behavior
Vector run on AWS t4g instance

### Actual Behavior
Vector fail to run with error
```
<jemalloc>: Unsupported system page size
memory allocation of 32 bytes failed
Aborted
```

### Additional Context
Installed Vector from archive or RPM package on AWS t4g instance (Graviton 2 ARM64) processor.
AMI: [Centos 8](https://centos.org/download/aws-images/)

**Comment by jamtur01** [comment] 2020-10-07 03:48
Hi @DocLM - thanks for reporting! Are you using the 0.10 release or the nightly builds or...?

**Comment by jszwedko** [comment] 2020-10-07 13:20
I am able to reproduce this with vector 0.10.0 on Centos 8 (ami-0c7ec43a152e9c107) using ARM64. Interestingly, I do not get this error using Amazon Linux 2 with ARM64 so I'm wondering if it is something specific to Centos8.

**Comment by jszwedko** [comment] 2020-10-07 13:29
It looks like Amazon Linux has page sizes of 4 kB while Centos 8 has 64 kB pages:

Amazon Linux:
```
cd /proc/1 && sudo grep -i pagesize smaps | sort | uniq
KernelPageSize:        4 kB
MMUPageSize:           4 kB
```

Centos:
```
 cd /proc/1 && sudo grep -i pagesize smaps | sort | uniq
KernelPageSize:       64 kB
MMUPageSize:          64 kB
```

It _looks_ like we may need to compile vector with larger page sizes? It looks like, by default, jemallac uses the page sizes of the build system:

> JEMALLOC_SYS_WITH_LG_PAGE=<lg-page>: Specify the base 2 log of the allocator page size, which must in turn be at least as large as the system page size. By default the configure script determines the host's page size and sets the allocator page size equal to the system page size, so this option need not be specified unless the system page size may change between configuration and execution, e.g. when cross compiling.

https://github.com/gnzlbg/jemallocator/blob/01b2dc89238a35b38f8d7b62c2ef876ed7641b2f/jemalloc-sys/README.md#environment-variables

It's unclear to me if we should do that generally or specifically for CentOS builds.

**Comment by DocLM** [comment] 2020-10-07 17:51
> Hi @DocLM - thanks for reporting! Are you using the 0.10 release or the nightly builds or...?

@jamtur01 I tried v0.10.0 and also nightly but the outcome is the same.

> It's unclear to me if we should do that generally or specifically for CentOS builds.

@jszwedko Honestly I don't know. Yesterday I built it from source as a workaround but if bigger pages also work on systems with a lower default it can be a more inclusive approach.

**Comment by jamtur01** [comment] 2020-10-07 21:19
@jszwedko Not sure either. Maybe @Hoverbear knows?

**Comment by Hoverbear** [comment] 2020-10-07 23:40
#3813 just closed a few hours ago. Do you think you could try with one of the next nightlies or from an updated main branch again? Otherwise I can take a look at this tomorrow. :) Thank you for reporting it.

**Comment by DocLM** [comment] 2020-10-08 05:32
> #3813 just closed a few hours ago. Do you think you could try with one of the next nightlies or from an updated main branch again? Otherwise I can take a look at this tomorrow. :) Thank you for reporting it.

I tried a moment ago (7.30 AM CET) with the latest nightly I found on the site (2020-10-08) without luck.

**Comment by jamtur01** [comment] 2020-10-08 05:37
@DocLM Sorry - we've got a hiccup with our nightlies post #3813. I'll ping you when we have new builds. Hopefully soon'ish.

**Comment by jamtur01** [comment] 2020-10-08 14:14
@DocLM New nightly images here: https://github.com/timberio/vector/actions/runs/294876413

**Comment by DocLM** [comment] 2020-10-08 18:55
> @DocLM New nightly images here: https://github.com/timberio/vector/actions/runs/294876413

@jamtur01 I tried a moment ago. It's not working with the same errors.

**Comment by DocLM** [comment] 2021-06-22 19:16
I tried the official rpm for Vector 0.14.0 on Centos 8 with Graviton 2 and now works out of the box.

**Comment by jszwedko** [comment] 2021-06-22 19:38
Thanks for following up @DocLM ! This must have changed with 0.14.0 when we dropped jemalloc as the default allocator.

**Comment by markmartirosian** [comment] 2022-01-19 23:01
@DocLM this is still happening on Centos 8 Stream with vector-0.19.0.

```sh
# uname -a
Linux ip-172-16-30-81.eu-central-1.compute.internal 4.18.0-358.el8.aarch64 #1 SMP Mon Jan 10 13:06:14 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
# /bin/vector
<jemalloc>: Unsupported system page size
memory allocation of 32 bytes failed
Aborted (core dumped)
```

**Comment by jszwedko** [comment] 2022-01-19 23:02
Ah, doh, I completely forgot about this Centos 8 issue when we re-enabled jemalloc in 0.19.0. I'll re-open this for tracking.

**Comment by jszwedko** [comment] 2022-01-20 00:02
I confirmed that building Vector with 64 KiB pages seems to run on systems with both 4 KiB pages and 64 KiB pages. I'm not sure what trade-offs are, though, or if they warrant a separate build specifically with large pages.

**Comment by markmartirosian** [comment] 2022-01-20 02:11
@jszwedko another thing to consider: EL9, Centos Stream 9, RHEL 9 Beta &c. have moved back to 4 kB.

**Comment by jszwedko** [comment] 2022-01-20 22:23
That is good to know, thank you @markmartirosian !

Just for reference, in case users want to compile Vector themselves for systems with 64 K page sizes, you can use:

```
JEMALLOC_SYS_WITH_LG_PAGE=16 make build-aarch64-unknown-linux-gnu
```

once https://github.com/vectordotdev/vector/pull/10940 is merged.

**Comment by markmartirosian** [comment] 2022-01-20 22:58
@jszwedko thank you, that will help with building my own rpm.

**Comment by shumphrey** [comment] 2023-09-11 08:06
I would love to see a precompiled version that works for EL8 (centos8/rockylinux8)

**Closed** 2023-09-14 22:13 UTC
Labels: type: bug, domain: platforms, domain: releasing
