### ISSUE TITLE
Is there a plan to add Vector sinks for Doris in the future?

### ISSUE THREAD

**Issue by jiaozi07** [vectordotdev/vector#21011] opened 2024-08-06 06:07 UTC
### Use Cases

https://doris.apache.org/

**Comment by jszwedko** [comment] 2024-08-06 14:18
Thanks for this request @jiaozi07 . I think it is a duplicate of https://github.com/vectordotdev/vector/issues/20843 so I'll close this one, but feel free to leave a 👍 emoji reaction on the other one to indicate that the feature would be useful to you.

**Closed by jszwedko** 2024-08-06 14:18 UTC
Labels: type: feature
