### ISSUE TITLE
random_in_range function

### ISSUE THREAD

**Issue by jlazic** [vectordotdev/vector#15324] opened 2022-11-22 20:54 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We'd like to have function to generate random integer numbers, where use cases are

1. Send events to multiple buckets where buckets are numbered in range min, max
2. Simple event sampling via randomly generated numbers
3. Ensuring uniqueness for files generated via file sink

### Attempted Solutions

We have used lua remap and `math.random` function, but that's cumbersome and having simple VRL function would make things much easier.

### Proposal

Function can be named random_integer (to be in line with one existing random function random_bytes), and can function exactly like rust helper function random_in_range 
    https://github.com/vectordotdev/vector/blob/master/lib/fakedata/src/logs.rs#L219
    
    random_integer(min: 1, max:50)
    
    random_bytes(min: <integer>, max: <integer>)
    :: <integer> , <error>

### Version

0.25.1

**Comment by jszwedko** [comment] 2022-11-28 22:53
Thanks for this request! I think it is a duplicate of https://github.com/vectordotdev/vector/issues/7049 so I'll close this one, but feel free to follow that one or add any additional details there.

**Closed by jszwedko** 2022-11-28 22:53 UTC
Labels: type: feature
