### ISSUE TITLE
--config option ignored

### ISSUE THREAD

**Issue by ilikejam** [vectordotdev/vector#15356] opened 2022-11-25 18:13 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The '--config' option appears to be completely ignored.

[root@vm-10-160-207-120 vector]# pwd
/etc/vector

[root@vm-10-160-207-120 vector]# ls -l
total 16
-rw-r-----. 1 root vector  262 Nov 25 17:38 container_ansible_runner.toml
-rw-r-----. 1 root vector  524 Nov 25 17:38 container_awssink_eu-west-1_ansible_runner.toml
drwxr-x--x. 3 root vector 4096 Nov 23 17:26 examples
-rw-r-----. 1 root vector 1500 Nov 25 17:38 vector.toml

[root@vm-10-160-207-120 vector]# strace -e open /usr/bin/vector --config '/etc/vector/*.toml' validate
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/proc/sys/vm/overcommit_memory", O_RDONLY|O_CLOEXEC) = 3
open("/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY) = 3
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
open("/proc/self/cgroup", O_RDONLY|O_CLOEXEC) = 3
open("/proc/self/mountinfo", O_RDONLY|O_CLOEXEC) = 3
open("/sys/fs/cgroup/cpu,cpuacct/user.slice/cpu.cfs_quota_us", O_RDONLY|O_CLOEXEC) = 3
open("/etc/vector/vector.toml", O_RDONLY|O_CLOEXEC) = 9
open("/etc/vector/vector.toml", O_RDONLY|O_CLOEXEC) = 9
Loaded with warnings ["/etc/vector/vector.toml"]

~ Transform "journal_nodocker._unmatched" has no consumers

open("/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-da5b0c64898c9c97/out/openssl-build/install/ssl/openssl.cnf", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 9
open("/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", O_RDONLY) = 9
open("/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", O_RDONLY) = 9
√ Component configuration
√ Health check "aws"

                                                 Validated
+++ exited with 0 +++

### Version

vector 0.22.3 (x86_64-unknown-linux-gnu)

**Comment by bruceg** [comment] 2022-11-25 21:57
I am not able to reproduce this with either version 0.22.3 or current master. Could you share a little more about your installation? I see this is running from `/usr/bin/vector`. Which distribution are you running and where did you download the installed package?

**Comment by ilikejam** [comment] 2022-11-25 22:23
Hi!

This is from the vector-0.22.3-1.x86_64.rpm on vector.io, running on RHEL7.9

[root@vm-10-160-207-120 ~]$ rpm -qi vector-0.22.3-1.x86_64
Name        : vector
Version     : 0.22.3
Release     : 1
Architecture: x86_64
Install Date: Wed 23 Nov 2022 17:26:29 UTC
Group       : Applications/System
Size        : 200196760
License     : MPL-2.0
Signature   : (none)
Source RPM  : vector-0.22.3-1.src.rpm
Build Date  : Wed 29 Jun 2022 04:41:16 UTC
Build Host  : 2e9e38d718a4
Relocations : (not relocatable)
URL         : https://vector.dev
Summary     : A lightweight and ultra-fast tool for building observability pipelines
Description :
A lightweight and ultra-fast tool for building observability pipelines

[root@vm-10-160-207-120 ~]# sha256sum vector-0.22.3-1.x86_64.rpm
78ee3d0bb4593ad7ff63112612828e45d8dbadfaf5e0686b537a965a9fe1d21b  vector-0.22.3-1.x86_64.rpm

**Comment by ilikejam** [comment] 2022-11-25 22:24
(We're stuck on 0.22.3 atm because of https://github.com/vectordotdev/vector/issues/13183 )

**Comment by jszwedko** [comment] 2022-12-01 21:36
Hey @ilikejam . I think you are hitting a rough edge of the CLI flags. The global `--config` flag is only read when no subcommands are used (i.e. when running Vector). `vector validate` takes the configs as arguments like `vector validate /etc/vector/*.toml`. Let me know if that works for you.

We have an issue to do a pass over the CLI flags and normalize them: https://github.com/vectordotdev/vector/issues/12242

I'll close this since I'm pretty sure that is it but feel free to re-open if you are still having issues.

**Closed by jszwedko** 2022-12-01 21:36 UTC
Labels: type: bug, domain: cli, domain: config
