### ISSUE TITLE
Incorrect fallibility assessment for `test` but not `validate`

### ISSUE THREAD

**Issue by mjperrone** [vectordotdev/vector#14468] opened 2022-09-19 18:54 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The [documentation](https://vector.dev/docs/reference/vrl/functions/#merge) for merge says that the function is infallible.

When I run `validate`, it doesn't complain:

```
 vector validate --no-environment  testparse.toml
√ Loaded ["testparse.toml"]
---------------------------
                  Validated
```

But then when I run a test, it does complain that `merge` is fallible.

```
vector test testparse.toml
Running tests
2022-09-19T18:52:43.731054Z ERROR vector::unit_test: Failed to execute tests:
Failed to build test 'test message':
  Transform "parse": 
  error[E103]: unhandled fallible assignment
    ┌─ :2:19
    │
  2 │     new_message = merge(structured, .)
    │     ------------- ^^^^^^^^^^^^^^^^^^^^
    │     │             │
    │     │             this expression is fallible
    │     │             update the expression to be infallible
    │     or change this to an infallible assignment:
    │     new_message, err = merge(structured, .)
    │
    = see documentation about error handling at https://errors.vrl.dev/#handling
    = learn more about error code 103 at https://errors.vrl.dev/103
    = see language documentation at https://vrl.dev
    = try your code in the VRL REPL, learn more at https://vrl.dev/examples
  .
```

### Configuration

```text
[sources.kubernetes_logs]
  type = "kubernetes_logs"

## This transform attempts to parse the .message as json
[transforms.parse]
  # General
  type = "remap"
  inputs = ["kubernetes_logs"]
  source = '''
    structured = parse_json!(.message)
    new_message = merge(structured, .)
  '''

[sinks.blackhole]
  type = "blackhole"
  inputs = ["parse"]

[[tests]]
  name = "test message"
  [[tests.inputs]]
    insert_at = "parse"
    type = "log"
    [tests.inputs.log_fields]
       message = "{\"level\":\"info\",\"time\":1629228610946,\"pid\":34,\"hostname\":\"blah\",\"name\":\"start\",\"context\":{},\"dd\":{\"service\":\"blah-service\",\"version\":\"0.1.0\",\"env\":\"production\"},\"msg\":\"Done running shutdown hooks.\"}"
  [[tests.outputs]]
    extract_from = "parse"
    [[tests.outputs.conditions]]
      type = "vrl"
      source = '''assert!(.message == "Done running shutdown hooks." && .level == "info" && .name == "start")'''
```

### Version

0.24.0 and 0.24.1

### Debug Output

```text
No additional info running debug like this.
```

**Comment by spencergilbert** [comment] 2022-09-19 18:56
👋 
Thanks for reporting @mjperrone - this is actually a duplicate of, https://github.com/vectordotdev/vector/issues/7198. Currently `validate --no-environment` doesn't check VRL snippets due to how things are loaded internally.

**Closed by spencergilbert** 2022-09-19 18:56 UTC
Labels: type: bug

**Comment by mjperrone** [comment] 2022-09-19 19:24
More conversation on the merged function and its docs here: https://discord.com/channels/742820443487993987/764187584452493323/1021494662948732928
