### ISSUE TITLE
Enable raw event endpoint in the Splunk HEC Sink 

### ISSUE THREAD

**Issue by calvincs** [vectordotdev/vector#12183] opened 2022-04-12 15:28 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently the Splunk HEC sink only allows the use of the "/services/collector/event" endpoint.  
This endpoint is hardcoded here: https://github.com/vectordotdev/vector/blob/master/src/sinks/splunk_hec/common/util.rs#L58
The Splunk HEC endpoint also allows sending events to "/services/collector/raw"

Additionally, we are unable to define the meta data transmitted to Splunk.
Per the Splunk HEC documentation:
https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/FormateventsforHTTPEventCollector#Event_metadata

- With raw events, you can configure metadata at the global level, at the token level, and at the request level using the **query string**.

Allowing the use use of the /services/collector/raw event with the ability to modify query string parameters sent in events allows Splunk operators the ability to fully utilize their existing Props and Transforms as they migrate away from Splunk tooling such as Heavy Forwarders to Vector systems.

### Attempted Solutions

N/A

### References

https://github.com/vectordotdev/vector/issues/1088  New splunk_hec source
https://github.com/vectordotdev/vector/issues/6185  Vector Sinks Splunk HEC (Time / Timestamp)
https://github.com/vectordotdev/vector/issues/6452  Allow user to manually set or define the HEC event metadata field.

### Version

v0.20.1

**Comment by jszwedko** [comment] 2022-04-12 15:52
Thanks for reporting! I think this is a duplicate of https://github.com/vectordotdev/vector/issues/8601 but this issue has more details, so I'll close the other one.

**Closed** 2022-06-17 23:22 UTC
Labels: sink: splunk_hec, type: feature
