### ISSUE TITLE
Inconsistencies in `vector_component_*` Vector metrics

### ISSUE THREAD

**Issue by skygrammas** [vectordotdev/vector#17328] opened 2023-05-05 22:30 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm trying to monitor the amount of dropped log events for a `humio` sink. Upon observing the `vector_component_sent_event_bytes_total` and `vector_component_received_event_bytes_total` metrics, I am seeing that the amount of bytes that `vector_component_sent_event_bytes_total` reports is significantly higher than the amount of bytes reported for `vector_component_received_event_bytes_total`. I've scoped both metrics down to the `humio` sink component, so I don't expect that there's any difference in the amount of bytes that the component receives versus what it sends as there is no transformation of log data within the component. Additionally, I could understand the amount of bytes received being higher than the amount sent and interpreting that as the sink is dropping events, however the amount sent being higher than the amount received without any transformation within the component is puzzling (and concerning).

I would expect these two metric values would be tightly bound for a sink component that is not dropping logs. I would not expect the amount of bytes sent to be significantly higher than the amount of bytes received for a component that is not transforming the data it receives.

<img width="1376" alt="Screenshot 2023-05-05 at 3 26 56 PM" src="https://user-images.githubusercontent.com/23141825/236578631-47a8d606-37c8-43f6-839f-766613b4be70.png">

### Configuration

```text
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 0.0.0.0:8686
  log_schema:
    host_key: host
    message_key: message
    source_type_key: source_type
    timestamp_key: timestamp
  sources:
    kubernetes_logs:
      type: kubernetes_logs
      self_node_name: ${NODE_NAME}
      glob_minimum_cooldown_ms: 2000
      max_line_bytes: 262144
      max_read_bytes: 10485760
    internal_logs:
      type: internal_logs
    vector_metrics:
      type: internal_metrics
  sinks:
    humio:
      type: humio_logs
      inputs:
        - kubernetes_logs
      token: "${HUMIO_INGEST_TOKEN}"
      endpoint: "${HUMIO_INGEST_ENDPOINT}"
      request:
        concurrency: adaptive
      compression: gzip
      encoding:
        codec: json
    prometheus_exporter:
      type: prometheus_exporter
      address: 0.0.0.0:9598
      default_namespace: vector
      inputs:
        - vector_metrics
```
```


### Version

Vector version 0.26.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by spencergilbert** [comment] 2023-05-08 14:23
Closing as duplicate of #17329

**Closed by spencergilbert** 2023-05-08 14:23 UTC
Labels: type: bug
