### ISSUE TITLE
Splunk hec logs sink not picking up tls.verify_certificate, tls.verify_hostname update to false when config file changes

### ISSUE THREAD

**Issue by mans2singh** [vectordotdev/vector#16164] opened 2023-01-27 15:35 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi:

I am using splunk hec logs sink to post data a splunk instance and using vectors watch functionality to pick up config file changes.  The jobs are running in kubernetes.

I am including fragments of sink config below and the complete config is also included below.

If I start the pipeline with tls.verify_hostname and tls.verify_certificate with `false` settings (https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#tls.verify_certificate, https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#tls.verify_hostname), the pipeline works as expected.
```
tls.verify_certificate = false
tls.verify_hostname = false
```

If I change the config file to have tls.verify_hostname and tls.verify_certificate to `true`, the logs show that the config file has changed and a new sink is being created. I then get SSL error indicating that the certificates are self signed.
```
tls.verify_certificate = true
tls.verify_hostname = true
```

If I now change the config file back to tls.verify_hostname and tls.verify_certificate `false`, the logs indicate that the config file has changed and a new sink is being created.  However, the ssl errors persist even though the config file now has the values set to false as shown below.
```
tls.verify_certificate = false
tls.verify_hostname = false
```

The complete config file (with tokens/dns names changed) is included below.

Please let me know what could the issue that the tls values changing back to false is not being picked up.

If there is any other advice, please let me know.

Thanks

### Configuration

```text
[api]
enabled = true

[sources.messages_source]
type = "kafka"
bootstrap_servers = "bkafka-broker.com:9094,bkafak-broker2.com:9094"
group_id = "tests-exporter-splunk-hec-logs-1111"
topics = [ "tests_messages" ]
tls.enabled = true

[transforms.messages_transformed_for_splunk]
type = "remap"
inputs = [ "messages_source" ]
source = """
. = parse_json!(string!(.message))
del(.meta)
"""

[sinks.messages_sink]
type = "splunk_hec_logs"
inputs = [ "messages_transformed_for_splunk" ]
endpoint = "https://splunk-instance.com:8088"
endpoint_target = "event"
index = "messages"
default_token = "999999-00000-99999-9999"
tls.verify_certificate = false # This is the property that was flipped from true to false
tls.verify_hostname = false # Same as above

[sinks.messages_sink.encoding]
codec = "json"
```

### Version

timberio/vector:0.25.1-debian

### Debug Output

```text
2023-01-27T15:06:04.651232Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain internal_log_rate_limit=true
2023-01-27T15:06:04.651239Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying request. delay_ms=8000
2023-01-27T15:06:07.780343Z DEBUG transform{component_kind="transform" component_id=messages_transformed_for_splunk component_type=remap component_name=messages_transformed_for_splunk}: vector::utilization: utilization=0.00011985139550184171
2023-01-27T15:06:12.653133Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://splunk-instance.com:8088/services/collector/event method=POST version=HTTP/1.1 headers={"content-type": "application/json", "authorization": Sensitive, "x-splunk-request-channel": "3452333-8aaa-4555-a222-f23443221333", "user-agent": "Vector/0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)", "accept-encoding": "identity"} body=[1448 bytes]
2023-01-27T15:06:12.664284Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: Internal log [HTTP error.] is being rate limited.
2023-01-27T15:06:12.664353Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Internal log [Retrying after error.] is being rate limited.
2023-01-27T15:06:12.664364Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying request. delay_ms=13000
2023-01-27T15:06:13.056109Z DEBUG transform{component_kind="transform" component_id=messages_transformed_for_splunk component_type=remap component_name=messages_transformed_for_splunk}: vector::utilization: utilization=0.0001719675554822315
2023-01-27T15:06:25.665616Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://splunk-instance.com:8088/services/collector/event method=POST version=HTTP/1.1 headers={"content-type": "application/json", "authorization": Sensitive, "x-splunk-request-channel": "3452333-8aaa-4555-a222-f23443221333", "user-agent": "Vector/0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)", "accept-encoding": "identity"} body=[1448 bytes]
2023-01-27T15:06:25.676218Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: Internal log [HTTP error.] has been rate limited 1 times.
2023-01-27T15:06:25.676244Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain error_type="request_failed" stage="processing" internal_log_rate_limit=true
2023-01-27T15:06:25.676293Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Internal log [Retrying after error.] has been rate limited 1 times.
2023-01-27T15:06:25.676297Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain internal_log_rate_limit=true
2023-01-27T15:06:25.676306Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying request. delay_ms=21000
2023-01-27T15:06:46.596922Z DEBUG transform{component_kind="transform" component_id=messages_transformed_for_splunk component_type=remap component_name=messages_transformed_for_splunk}: vector::utilization: utilization=0.000029179265093017663
2023-01-27T15:06:46.678163Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://splunk-instance.com:8088/services/collector/event method=POST version=HTTP/1.1 headers={"content-type": "application/json", "authorization": Sensitive, "x-splunk-request-channel": "3452333-8aaa-4555-a222-f23443221333", "user-agent": "Vector/0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)", "accept-encoding": "identity"} body=[1448 bytes]
2023-01-27T15:06:46.689503Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain error_type="request_failed" stage="processing" internal_log_rate_limit=true
2023-01-27T15:06:46.689860Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain internal_log_rate_limit=true
2023-01-27T15:06:46.689880Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying request. delay_ms=34000
2023-01-27T15:06:51.822998Z DEBUG transform{component_kind="transform" component_id=messages_transformed_for_splunk component_type=remap component_name=messages_transformed_for_splunk}: vector::utilization: utilization=0.00019052936571849164
2023-01-27T15:07:03.021840Z DEBUG transform{component_kind="transform" component_id=messages_transformed_for_splunk component_type=remap component_name=messages_transformed_for_splunk}: vector::utilization: utilization=0.00004390547112885636


### This is where the config file was updated to tls verify values to false

2023-01-27T15:07:07.099489Z DEBUG vector::config::watcher: Configuration file change detected. event=Event { kind: Create(Folder), paths: ["/etc/vector/..2023_01_27_15_07_07.255977363"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
2023-01-27T15:07:08.099609Z DEBUG vector::config::watcher: Consumed file change events for delay. delay=1s
2023-01-27T15:07:08.099682Z DEBUG vector::config::watcher: Reloaded paths.
2023-01-27T15:07:08.099687Z  INFO vector::config::watcher: Configuration file changed.
2023-01-27T15:07:08.100550Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-01-27T15:07:08.101592Z  INFO vector::topology::running: Reloading running topology with new configuration.
2023-01-27T15:07:08.101658Z DEBUG vector::topology::running: Changing sink. component=messages_sink
2023-01-27T15:07:08.101685Z DEBUG vector::topology::running: Pausing component input in fanout. component=messages_sink fanout_id=messages_transformed_for_splunk
2023-01-27T15:07:08.101694Z DEBUG vector::topology::running: Waiting for sink to shutdown. key=messages_sink
2023-01-27T15:07:08.490977Z DEBUG transform{component_kind="transform" component_id=messages_transformed_for_splunk component_type=remap component_name=messages_transformed_for_splunk}: vector::utilization: utilization=0.0003007881012433421
2023-01-27T15:07:20.691179Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://splunk-instance.com:8088/services/collector/event method=POST version=HTTP/1.1 headers={"content-type": "application/json", "authorization": Sensitive, "x-splunk-request-channel": "3452333-8aaa-4555-a222-f23443221333", "user-agent": "Vector/0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)", "accept-encoding": "identity"} body=[1448 bytes]
2023-01-27T15:07:20.701758Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain error_type="request_failed" stage="processing" internal_log_rate_limit=true
2023-01-27T15:07:20.701827Z  WARN sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain internal_log_rate_limit=true
2023-01-27T15:07:20.701841Z DEBUG sink{component_kind="sink" component_id=messages_sink component_type=splunk_hec_logs component_name=messages_sink}:request{request_id=1}: vector::sinks::util::retries: Retrying request. delay_ms=55000
```

### Additional Context

The vector pipeline is running as a job in kubernetes.

**Comment by davidhuie-dd** [comment] 2023-01-27 22:58
I confirmed that this behavior happens. 

Vector team: here's an example (internal): https://github.com/vectordotdev/issue-examples/blob/main/16164/vector.toml#L22

**Comment by mans2singh** [comment] 2023-02-01 21:46
Thanks @davidhuie-dd

**Comment by jszwedko** [comment] 2023-08-21 15:24
Thanks for opening this @mans2singh ! I think this is a duplicate of https://github.com/vectordotdev/vector/issues/10877 so I'll close it out but feel free to leave a comment if you disagree.

**Closed by jszwedko** 2023-08-21 15:24 UTC
Labels: type: bug, sink: splunk_hec, domain: reload
