### ISSUE TITLE
Add windows eventlog support

### ISSUE THREAD

**Issue by Ayowel** [vectordotdev/vector#10043] opened 2021-11-16 12:26 UTC
Hi,

I'm interested in using vector on windows and would like to be able to read from/write to the windows eventlog (similar to the syslog source for GNU/Linux systems). In my use-case, this is to ease compliance management as I could then write all logs of interest to the host's eventlog, as those logs are then centrally managed.

Is this a good idea/planned at the moment ?

I could not find any policy on new sources/sinks ? More specifically, do they have to be compatible with both windows and linux hosts ? The specific implementation I have been working toward could only ever run on windows even though it would allow to read/write remote windows workstations' eventlogs.

I suppose that a placeholder that systematically errors out with a proper message should still be available on linux. What is your recommendation ?

**Comment by jszwedko** [comment] 2021-11-16 14:46
Hi @Ayowel !

That would be a great addition to Vector. To answer your question about source/sink policy, we are happy to add new components that target specific platforms. For example, the `dnstap` component does not run on Windows. If you wanted to take a shot at it, we'd be happy to review PRs.

This was actually suggested by https://github.com/vectordotdev/vector/issues/1206 though so I'll close this as a duplicate of that one to keep the tracking in one place.

**Closed by jszwedko** 2021-11-16 14:46 UTC
