### ISSUE TITLE
Cannot test arrays using VRL unit test, for example, for `kubernetes_logs`

### ISSUE THREAD

**Issue by fzyzcjy** [vectordotdev/vector#18022] opened 2023-07-19 03:11 UTC
### Problem

I want to test a VRL remap for kubernetes_logs. The idea is super simple: Copy the example data from https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#examples, and make some assertions about my transformation on that data. However, it says, `data did not match any variant of untagged enum TestInputValue`.

From the source code https://github.com/vectordotdev/vector/blob/b00727ee13cc4eef6dde63bb8eaa8e0a570294ce/src/config/mod.rs#L485, I guess it does not understand lists yet?

### Configuration

```text
tests:
  - name: primary_remap should work for normal logs
    inputs:
      - insert_at: primary_remap
        type: log
        log_fields:
          "file": "/var/log/pods/kube-system_storage-provisioner_93bde4d0-9731-4785-a80e-cd27ba8ad7c2/storage-provisioner/1.log"
          "kubernetes.container_image": "gcr.io/k8s-minikube/storage-provisioner:v3"
          "kubernetes.container_name": "storage-provisioner"
          '"kubernetes.namespace_labels"."kubernetes.io/metadata.name"': "kube-system"
          '"kubernetes.pod_annotations"."prometheus.io/scrape"': "false"
          "kubernetes.pod_ip": "192.168.1.1"
          '"kubernetes.pod_ips"': ["192.168.1.1", "::1"]
          '"kubernetes.pod_labels"."addonmanager.kubernetes.io/mode"': "Reconcile"
          '"kubernetes.pod_labels"."gcp-auth-skip-secret"': "true"
          '"kubernetes.pod_labels"."integration-test"': "storage-provisioner"
          "kubernetes.pod_name": "storage-provisioner"
          "kubernetes.pod_namespace": "kube-system"
          "kubernetes.pod_node_name": "minikube"
          "kubernetes.pod_uid": "93bde4d0-9731-4785-a80e-cd27ba8ad7c2"
          "message": "F1015 11:01:46.499073       1 main.go:39] error getting server version: Get \"https://10.96.0.1:443/version?timeout=32s\": dial tcp 10.96.0.1:443: connect: network is unreachable"
          "source_type": "kubernetes_logs"
          "stream": "stderr"
          "timestamp": "2020-10-15T11:01:46.499555308Z"
```

### Version

latest

### Debug Output

```text
Running tests
2023-07-19T03:10:48.292632Z ERROR vector::unit_test: Failed to execute tests:
data did not match any variant of untagged enum TestInputValue
in `tests.inputs.log_fields."kubernetes.pod_ips"`
.
```

**Comment by jszwedko** [comment] 2023-07-19 15:08
Hi @fzyzcjy !

I think this is the same as this issue: https://github.com/vectordotdev/vector/issues/9386 . You can see a workaround there. In your case it'd be "flattening" the array like: `"kubernetes.pod_ips[0]"': "192.168.1.1", "::1"`

**Comment by jszwedko** [comment] 2023-07-19 15:08
Duplicate of #9386

**Closed by jszwedko** 2023-07-19 15:08 UTC
Labels: type: bug
