### ISSUE TITLE
Capture memory / CPU utilization

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#10456] opened 2021-12-14 21:46 UTC
Right now throughput is our primary optimization concern in vector. That is, all other things being equal we'll always go for a solution that gives more throughput. The soaks reflect this. It would, however, be useful to know other things about vector while it's being soaked. For instance, how much memory did the vector process allocate during the soak? What was the CPU utilization like? 

To that end we want to collect data on allocation/deallocation during a soak run _and_ CPU utilization data. The later becomes especially important as we scale out to more CPUs. Can vector make use of them?

**Comment by blt** [comment] 2022-05-17 22:33
REF https://github.com/blt/lading/pull/200

**Comment by jszwedko** [comment] 2023-09-01 13:28
Closing this since the regression rig does capture this data now.

**Closed by jszwedko** 2023-09-01 13:28 UTC
Labels: domain: ci, domain: performance
