### ISSUE TITLE
Allow payload_prefix and payload_suffix on text encoding for http sink

### ISSUE THREAD

**Issue by cjp421** [vectordotdev/vector#17370] opened 2023-05-11 18:20 UTC
Currently, `payload_prefix` and `payload_suffix` are applicable when the encoding codec is set to "json".  I would like to be able to add either a prefix or a suffix to my request's payload when the codec is "text".

**Comment by jszwedko** [comment] 2023-05-11 18:28
Thanks for this @cjp421 .

We actually want to take a more generalized approach to this with "batch encoding" which is tracked by https://github.com/vectordotdev/vector/issues/16637 . This would let wrappers be added for any codec (like `text`) and also for every sink. Would you want to take a look and see if that would satisfy your use case? If so, I think we can close this one as a duplicate.

**Comment by cjp421** [comment] 2023-05-11 19:18
would that batch encoding be a configuration on the specific sink or all "text" encodings?

**Comment by neuronull** [comment] 2023-05-30 17:40
Hi @cjp421  , have you had a chance to review that linked issue? Do you think it will satisfy your use case?
https://github.com/vectordotdev/vector/issues/16637

**Comment by jszwedko** [comment] 2023-09-28 01:48
This appears to be a duplicate of https://github.com/vectordotdev/vector/issues/16637

**Closed by jszwedko** 2023-09-28 01:48 UTC
