### ISSUE TITLE
File sink using templated path cause infinite internal_metrics growth

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#11821] opened 2022-03-14 10:42 UTC
Using file sink with templated path will cause infinite growth of internal metrics. Therefore growth of memory and CPU usage as default scrape interval is 2s.

![image](https://user-images.githubusercontent.com/948799/158156194-2bca55a6-d6d0-4101-9362-8e91c8cdde08.png)

Found tons of metrics like this:
```
vector_component_sent_bytes_total{component_id="out_kafka_access_file",component_kind="sink",component_name="out_kafka_access_file",component_type="file",file="/var/lib/vector/out_kafka_access_file/topics/fluentd.svcfw.apiaccess_dea91c9a-beed-4561-67af-ab4112426b1f/year=2022/month=03/day=14/hour=10/minute=31/vector-0.json.gz",protocol="file"} 70445 1647253977789
```

Related configuration:
```
    [sinks.out_kafka_access_file]
      type = "file"
      inputs = ["remap_kafka_access"]
      compression = "gzip"
      encoding.codec = "ndjson"
      encoding.except_fields = ["_index", "_topic", "_topic_template", "_partition", "_offset", "_throttle_key", "_hash", "_alert", "_sd", "_source", "_syslog_severity", "kubernetes.labels.pod-template-hash"]
      path = "/var/lib/vector/out_kafka_access_file/topics/{{ _topic }}/year=%Y/month=%m/day=%d/hour=%H/minute=%M/${HOSTNAME}.json.gz"
      idle_timeout_secs = 10
      buffer.type = "memory"
      buffer.max_events = 3000    # default 500 with memory buffer
```

**Comment by jszwedko** [comment] 2022-03-14 21:59
Hi @fpytloun !

Thanks for reporting this. We have a similar issue with the `file` and `kubernetes_logs` sources which also tag metrics by file.

I'm curious what you think of the proposed solution in https://github.com/vectordotdev/vector/issues/11225 to expire metrics from the internal metrics registry.

**Comment by jszwedko** [comment] 2022-03-14 21:59
As a work around, you can pass the metrics through a `remap` transform and `del(.tags.file)` to remove that tag.

**Comment by xiaonanshen-ponyai** [comment] 2022-03-15 08:26
> As a work around, you can pass the metrics through a `remap` transform and `del(.tags.file)` to remove that tag.

I don't think this will aggregate the metrics properly. If we use a prometheus exporter, doesn't it just give the metrics of a random file but without the tag?

**Comment by fpytloun** [comment] 2022-03-15 09:47
Workaround works, it seems to create single useless metric (with constant value):
```
vector_component_sent_bytes_total{component_id="out_kafka_access_file",component_kind="sink",component_name="out_kafka_access_file",component_type="file",protocol="file"} 6507 1647337396118
```
Maybe this workaround could be extended to drop matching events completely 🤔

**Comment by jszwedko** [comment] 2022-03-15 14:18
Interesting, I would have expected it to aggregate correctly since `vector_component_sent_bytes_total` is an incremental counter. I'll have to check that.

You can also drop the metric completely via a `filter` transform that looks for that tag. Something like:

```toml
[transform.drop_file_metrics]
type = "filter"
condition = "!exists(.tags.file)"
```

**Comment by fpytloun** [comment] 2022-03-22 10:47
So I found out that workaround doesn't solve the issue. It will drop unwanted metrics on output so will not DoS Prometheus but metrics are still coming in and overloading `internal_metrics` source.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/948799/159464869-90148abb-e97c-418e-822a-5e3be1cffb8c.png">
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/948799/159464957-2c1d3f57-f582-43d0-a14d-d29946975d0f.png">

**Comment by aavileli** [comment] 2022-06-22 03:04
we are also facing this issue @jszwedko is there a way to drop it from the internal metrics .
Its crerating 120000 s3 events like this for us
```bash
vector_processed_bytes_total{component_id="out_s3_default",component_kind="sink",component_name="out_s3_default",component_type="aws_s3",endpoint="/vector-aggregator-xxxxxx/index%3Dsystem/host%3Dip-xxxxx.ap-southeast-1.compute.internal/year%3D2022/month%3D06/day%3D21/1655779850-e046da8a-ddb8-4c1b-bc16-2a833802a8cb.log.gz?x-id=PutObject",protocol="https",region="xxxxx"} 868 1655780332329
```

**Comment by jszwedko** [comment] 2022-06-22 16:06
Hi @aavileli ,

I'm able to reproduce this. I opened https://github.com/vectordotdev/vector/issues/13284 to track it separately.

Thanks for the report!

**Comment by aavileli** [comment] 2022-06-23 00:27
Thanks @jszwedko 
similar issue on kubernetes_logs source 
```bash
vector_files_added_total{component_id="kubernetes_logs",component_kind="source",component_name="kubernetes_logs",component_type="kubernetes_logs",file="/var/log/pods/kube-system_kube-janitor-27592740--1-vbn5j_9fd5e94b-aabc-4516-8d43-9488d3d85610/kube-janitor/0.log"} 1 1655780332331
```

**Comment by hhromic** [comment] 2022-07-15 09:22
We just discovered today this same problem :(
In our case, the files being scrapped by the `file` source are named with this pattern very frequently:
```
app01_07-02-2022_03-29.log.gz
app02_06-24-2022_17-05.log.gz
app02_07-08-2022_16-57.log.gz
...
```
So naturally the `file` label/tag in the metrics grows to infinity (and beyond).

As mentioned, the workaround from @jszwedko only helps on the output side of metrics, but not during collection. Therefore, Vector will still use CPU/RAM to keep the high-cardinality metrics.

For the case of the `file` source, I think what would be very useful is to be able to specify a (regex?) pattern to match against the watched file names to extract the value to be used in the `file` label. Something like:
```yaml
sources:
  file:
    type: file
    include:
      - /path/to/[0-9]*/*.log.gz.processed
    file_tag_pattern: '^(/path/to/[0-9]/app[\w]+)_.*'
```
Which then would aggregate the above example into:
```
vector_checksum_errors_total{file="/path/to/app01"} 0
vector_checksum_errors_total{file="/path/to/app02"} 1
```

By default, this option could be set to `.*', preserving current behaviour.
Just an idea!

**Comment by zamazan4ik** [comment] 2022-10-08 22:38
@jszwedko what is the status of resolving this issue?

**Comment by jszwedko** [comment] 2022-10-26 17:32
In 0.24.2 the ability to expire these metrics was added so that they don't grow indefinitely. I'd still like to see us avoid publishing them to begin with though so this issue is still relevant.

**Comment by dsmith3197** [comment] 2023-12-18 18:32
The `file` metric tag is now opt-in thanks to https://github.com/vectordotdev/vector/pull/19084, addressing the root problem discussed in this issue.

**Closed by dsmith3197** 2023-12-18 18:32 UTC
Labels: type: bug, domain: observability, sink: file
