### ISSUE TITLE
New source - kubernetes_events

### ISSUE THREAD

**Issue by nabokihms** [vectordotdev/vector#17333] opened 2023-05-06 15:43 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Events in Kubernetes are logs of controllers. Controllers write the most critical information to event objects. Vector can be used to collect logs from pods, but, as of today, the other essential event of a Kubernetes cluster can only be collected with external tools.

### Attempted Solutions

Other solutions besides Vector can be applicable, e.g., [vmware-archive/eventrouter](https://github.com/vmware-archive/eventrouter).

Another option is to implement an events collector as an external application and send events to vector via, e.g., Vector protocol or let Vector collect events from a pod stdout.

### Proposal

Add a new source for Vector - kubernetes_events. Use a kube-rs watcher to collect events. Provide a way to collect only certain events by specifying a field or namespace selector.

Vector has an excellent capability to export events as both metrics and logs (and traces in the future), so the info can be exposed in a convenient format for everyone.

### Version

v0.29

**Comment by zamazan4ik** [comment] 2023-05-07 16:31
@nabokihms is there a still maintained alternative to "vmware-archive/eventrouter"?

**Comment by nabokihms** [comment] 2023-05-07 21:02
I think [this one](https://github.com/openshift/eventrouter) is alive, but I'm not sure.

**Comment by Leo1003** [comment] 2023-05-08 15:24
I think [resmoio/kubernetes-event-exporter](https://github.com/resmoio/kubernetes-event-exporter) is also a still maintained tool.

**Comment by patrickdung** [comment] 2023-07-30 08:40
As a side note:
[kubewatch](https://github.com/robusta-dev/kubewatch) can collect k8s events and send to other sinks.

But if Vector can collect it directly, it would be great.

**Comment by air3ijai** [comment] 2023-10-18 13:37
[Fluentbit - Kubernetes Events](https://docs.fluentbit.io/manual/pipeline/inputs/kubernetes-events)

Looks like Vector can't cover all our needs and we still need to run both tools in the cluster.

**Comment by ptr1120** [comment] 2023-12-09 19:54
Unfortunately, this is the last missing feature that prevents us from using vector in favour of fluent-bit.🤧

**Comment by air3ijai** [comment] 2024-01-02 17:57
Isn't this a duplicate of the #1293?

**Comment by jszwedko** [comment] 2024-01-04 19:26
Thanks for flagging that @air3ijai . Closing as a duplicate of https://github.com/vectordotdev/vector/issues/1293

**Closed by jszwedko** 2024-01-04 19:26 UTC
Labels: domain: sources
