### ISSUE TITLE
Acquire CII Badge(s)

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#1680] opened 2020-02-03 14:57 UTC
The CII from LF has a "Badge Program" that allows us to qualify for and display nice infrastructure standards qualifications. I think we can achieve passing quite easily. Silver/gold may require quite some work!

https://www.coreinfrastructure.org/programs/badge-program/

cc @binarylogic

**Comment by jszwedko** [comment] 2022-08-01 21:12
Duplicate of https://github.com/vectordotdev/vector/issues/322

**Closed by jszwedko** 2022-08-01 21:12 UTC
Labels: type: task, needs: approval, domain: ci
