### ISSUE TITLE
At-least-once, or improved delivery / checkpointing for `docker_logs` source

### ISSUE THREAD

**Issue by jonaslb** [vectordotdev/vector#20121] opened 2024-03-18 09:17 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

If structured logs are used downstream (for statistics or investigating which events took place), it would be nice to be able to rely a bit more on the correct delivery of those logs. Currently, vector only has "best effort" for `docker_logs`, and if I read the docs/source correctly, it always reads the logs from the "now" (at the start) timestamp, and not from the start of the container or indeed from any kind of checkpoint. That means the "best effort" is a quite poor effort, where logs _will_ be lost if vector is restarted. This has kept me from using Vector (other tools like promtail or filebeat do checkpointing - don't know if they integrate that with acknowledgements though).

### Proposal

- Introduce checkpointing to the `docker_logs` source, similar to the file source.
- Optionally integrate checkpointing with acknowledgements

I see that checkpointing hasn't been enough to upgrade the file source from best-effort to at-least-once delivery, which I assume is due to lack of acknowledgement integration. However, checkpoints is still a big upgrade to the reliability of the source, even without acknowledgement integration. But I do think both together would be enough to "upgrade" the classification.

### Version

0.36.1 (docker)

**Comment by jszwedko** [comment] 2024-03-18 13:20
Hi @jonaslb ! Thanks for filing this. I think it is a duplicate of https://github.com/vectordotdev/vector/issues/7358 so I'll close this one, but let me know if you disagree!

**Closed by jszwedko** 2024-03-18 13:20 UTC
Labels: type: feature
