### ISSUE TITLE
RPM installation issue

### ISSUE THREAD

**Issue by zzcpower** [vectordotdev/vector#13857] opened 2022-08-05 01:42 UTC
### Discussed in https://github.com/vectordotdev/vector/discussions/13856

<div type='discussions-op-text'>

<sup>Originally posted by **zzcpower** August  5, 2022</sup>
Hi, there

The error occurred when I tried to install the newest rpm vector-0.23.0-1.x86_64.rpm.
The linux operator system is CentOS-7-x86_64-Minimal-2009.iso

![image](https://user-images.githubusercontent.com/41858357/182983612-ddf16ebd-01c2-4273-9586-23c8cdee39c6.png)

Then I upgrade the libc version to 2.18, but still get the same error
![image](https://user-images.githubusercontent.com/41858357/182983428-b4904a0a-6fb6-4d61-a4c1-60ebb11169ae.png)

Anyone help plz.

</div>

**Comment by spencergilbert** [comment] 2022-08-05 12:53
Closing as duplicate of https://github.com/vectordotdev/vector/discussions/13856

**Closed by spencergilbert** 2022-08-05 12:53 UTC
