### ISSUE TITLE
VRL JSON example fails with error

### ISSUE THREAD

**Issue by jpds** [vectordotdev/vector#19563] opened 2024-01-09 10:15 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The VRL JSON example at: https://vector.dev/docs/reference/vrl/examples/#emitting-multiple-logs-from-json fails with just...

```
$ RUST_BACKTRACE=full vector -vvv vrl --input input.json --program program.vrl --print-object
2024-01-09T10:12:50.117192Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2024-01-09T10:12:50.117242Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
2024-01-09T10:12:50.117342Z DEBUG vector::app: messaged="Building runtime." worker_threads=4
input error: EOF while parsing an object at line 1 column 1
```

At first I thought this was a bug with my own VRL, but then found that the same issue happened with the example.

### Version

0.34.1

**Comment by jszwedko** [comment] 2024-01-09 15:32
Hi @jpds !

I'm not able to reproduce this. See https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiLiA9IHBhcnNlX2pzb24hKC5tZXNzYWdlKSIsImV2ZW50Ijp7Im1lc3NhZ2UiOiJbe1wibWVzc2FnZVwiOiBcImZpcnN0X2xvZ1wifSwge1wibWVzc2FnZVwiOiBcInNlY29uZF9sb2dcIn1dIn0sImlzX2pzb25sIjpmYWxzZSwiZXJyb3IiOm51bGx9 .

Note that when using `--input input.json ` the input is expected to be newline delimited JSON. The example from the webpage is multiline so you'll need to collapse it from:

```json
{
  "message": "[{\"message\": \"first_log\"}, {\"message\": \"second_log\"}]"
}
```

to

```json
{ "message": "[{\"message\": \"first_log\"}, {\"message\": \"second_log\"}]" }
```

Based on the error message, I'm guessing your input is not newline delimited JSON.

**Comment by jszwedko** [comment] 2024-01-12 22:38
Closing since I'm pretty confident that this was the issue, but feel free to reopen if it wasn't.

**Closed by jszwedko** 2024-01-12 22:38 UTC
