### ISSUE TITLE
Vector V0.35.0 does not seem to be recognizing the all_metrics field in the log_to_metric transform and gives an error upon its inclusion.

### ISSUE THREAD

**Issue by a-patos** [vectordotdev/vector#19633] opened 2024-01-16 23:01 UTC
### A note for the community

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector V0.35.0 does not seem to be recognizing the all_metrics field in the log_to_metric transform and gives an error upon its inclusion.

### Configuration

```text
transforms:
  log_2_met:
    inputs:
      - kafka
    type: log_to_metric
    metrics: ignored
    all_metrics: true
```

### Version

vector 0.35.0 (aarch64-unknown-linux-gnu e57c0c0 2024-01-08 14:42:10.103908779)

### Debug Output

```text
2024-01-16T23:00:31.023842Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2024-01-16T23:00:31.023886Z  INFO vector::app: Log level is enabled. level="trace"
2024-01-16T23:00:31.023942Z DEBUG vector::app: messaged="Building runtime." worker_threads=2
2024-01-16T23:00:31.024034Z TRACE mio::poll: registering event source with poller: token=Token(1), interests=READABLE
2024-01-16T23:00:31.024341Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.yaml"]
2024-01-16T23:00:31.025194Z ERROR vector::cli: Configuration error. error=invalid type: string "ignored", expected a sequence



in `transforms.log_2_met`
```

### Additional Context

Hello, I'm trying to implement a Kafka bus that centralizes all my metric collects from several Prometheus, and I need to route my metrics to different backends.
No problem to do the source.prometheus_remote_write to sinks.kafka,

but the reverse doesn't seem to be possible without this all_metrics, if I understood correctly.

### References

#19625

**Comment by jszwedko** [comment] 2024-01-17 00:19
@a-patos I think you want to leave out the `metrics: "ignored"` bit.

Also, if the goal is just to send metrics to Kafka, that can be achieved by configuring `encoding.codec` to either `native_json` or `native`. These will send the metrics as either JSON or protobuf (respectively) and can be decoded on the other side via `decoding.codec`. https://vector.dev/highlights/2022-03-31-native-event-codecs/ describes this in more detail.

**Comment by a-patos** [comment] 2024-01-17 19:24
My goal is to retrieve the metrics stored in Kafka topics and send them to different Prometheus instances. 


Sending metrics is working with this configuration:
# Change this to use a non-default directory for Vector data storage:
# data_dir: "/var/lib/vector"

# Random Syslog-formatted logs sources:
  system:
    type: "prometheus_remote_write"
    address: "0.0.0.0:8443"

  transforms:
    # Remove event if it does not contain "ST" field
    remove_no_st_system:
      inputs:
       - system
      type: filter
      when: '!((.ST.exists() && .Composant.exists()))'

# Print parsed logs to stdout sinks:
  metric:
    type: "kafka"
    inputs: ["remove_no_st_system"]
    topic: "metrics"
    bootstrap_servers: "kafka:9096"
    encoding:
      codec: "json"
    compression: "snappy"
    tls:
      enabled: true
    sasl:
      enabled: true
      mechanism: "SCRAM-SHA-512"
      username: "reader"


but the opposite don't work :(

**Comment by jszwedko** [comment] 2024-01-17 19:40
I'm a little confused since:

- The `prometheus_remote_write` should be emitting metric events and not log events which would be incompatible with the `kafka` sink as you have it configured
- `when: '!((.ST.exists() && .Composant.exists()))'` is not valid Vector configuration for the `filter` transform

Is this Vector configuration? Or configuration for another tool?

**Comment by a-patos** [comment] 2024-01-17 23:22
@jszwedko :
We need to forget about the filter for now. I corrected my previous post (I copied the wrong file). 
For me, the Prometheus remote write source is sending data to Kafka correctly, without any problem.
I attached a small schema for your reference
![Vector_metrics](https://github.com/vectordotdev/vector/assets/58400701/db7bb9c4-6969-476e-9343-88f3dde5d069)

In my schema, it is the "Vector Reader" part that is causing an error :("

**Comment by jszwedko** [comment] 2024-01-18 00:12
Thanks @a-patos . I'd recommend taking a look at https://vector.dev/highlights/2022-03-31-native-event-codecs/#sending-events-between-vector-instances . It discusses basically this exact use-case. The recommendation is to use the `native` codec for the sender and receiver.

**Comment by jszwedko** [comment] 2024-01-18 00:21
Which would mean removing the `log_to_metric` transform and any `metric_to_log` transform.

**Comment by a-patos** [comment] 2024-01-18 01:08
Oh great! It works perfectly, a big thank you for your help! 🥇 

Can I ask one more thing, Is it possible for me to implement a number of controls on the labels before sending the metrics?
 For example: 
 if the ST label is missing, we drop it, 
if the Job label is equal to "mycustomjob" , we drop it, 
if the name is not in the list ["up", "cpu", "ram"], we drop it, 
if the label "goto_siem" is equal to True, we send the metrics to the SIEM topic and Metrics topic .

**Comment by jszwedko** [comment] 2024-01-18 01:15
> if the ST label is missing, we drop it,
> if the Job label is equal to "mycustomjob" , we drop it,
> if the name is not in the list ["up", "cpu", "ram"], we drop it,

A `filter` transform should work for these

> if the label "goto_siem" is equal to True, we send the metrics to the SIEM topic and Metrics topic .

A `route` transform would work for this

I'll close this out since I think the issue is resolved, but feel free to open GitHub Discussions if you have additional usage questions!

**Closed by jszwedko** 2024-01-18 01:15 UTC
Labels: type: bug
