### ISSUE TITLE
gcp_cloud_storage sink: thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io'

### ISSUE THREAD

**Issue by Abhinav04** [vectordotdev/vector#19044] opened 2023-11-03 14:17 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector aggregator panicks and gets restarted for gcp_cloud_storage sink intermittently

Vector Version
`vector 0.26.0`

Log
```
2023-11-03T08:16:57.126512Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-03T08:16:57.144758Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-03T08:16:57.160504Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-03T13:47:06.246087Z ERROR sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}:sink{buffer_type="disk"}: vector_buffers::internal_events: Events dropped. count=18446744073709487194 intentional=false reason=corrupted_events stage=0
thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /project/lib/vector-buffers/src/topology/channel/receiver.rs:59:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-03T13:47:08.979414Z ERROR sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2023-11-03T13:47:08.979575Z  INFO vector: Vector has stopped.
```

Additional Context

Vector aggregator works fine throughout but fails intermittently after a few hours and gets restarted with the above error.
Good amount of CPU and Memory is available on nodes scheduling vector aggregator pods.

### Version

vector-0.26.0

**Comment by jszwedko** [comment] 2023-11-03 14:27
Appears to be a duplicate of https://github.com/vectordotdev/vector/issues/19045

**Closed by jszwedko** 2023-11-03 14:27 UTC
