### ISSUE TITLE
Kinesis PutRecords does not handle partial failure

### ISSUE THREAD

**Issue by kevinburkesegment** [vectordotdev/vector#16954] opened 2023-03-24 20:25 UTC
### Problem

One thing you can do with a kinesis PutRecords request is send multiple keys to multiple different partitions. AWS will respond with a list of records that succeeded and a list of records that failed. You can see this in the method signature in the aws-sdk-kinesis library, for PutRecordsOutput for example which has parameters both for successfully sent records and unsuccessful. https://docs.rs/aws-sdk-kinesis/latest/aws_sdk_kinesis/output/struct.PutRecordsOutput.html

Or the AWS docs: https://docs.aws.amazon.com/streams/latest/dev/developing-producers-with-sdk.html#kinesis-using-sdk-java-putrecords

As I am reading the Vector source code, we only look for errors on the _entire_ response, and retry if the entire response returns a ProvisionedThroughputExceededException. 

```rust
impl SendRecord for KinesisStreamClient {
    type T = KinesisRecord;
    type E = KinesisError;

    async fn send(&self, records: Vec<Self::T>, stream_name: String) -> Option<SdkError<Self::E>> {
        self.client
            .put_records()
            .set_records(Some(records))
            .stream_name(stream_name)
            .send()
            .instrument(info_span!("request").or_current())
            .await
            .err()
    }
}
```

And then the retry logic

```rust
impl RetryLogic for KinesisRetryLogic {
    type Error = SdkError<KinesisError>;
    type Response = KinesisResponse;

    fn is_retriable_error(&self, error: &Self::Error) -> bool {
        if let SdkError::ServiceError { err, raw: _ } = error {
            if let PutRecordsErrorKind::ProvisionedThroughputExceededException(_) = err.kind {
                return true;
            }
        }
        is_retriable_error(error)
    }
}
```

Perhaps if *every* record upload fails, then AWS will respond to the entire request with a ProvisionedThroughputExceededException, but it seems more likely that Vector is simply dropping records any time there is a partial failure.

### Version

Reading the code on tip.

**Comment by jszwedko** [comment] 2023-03-29 13:06
Thanks for filing this @kevinburkesegment ! I think it is a duplicate of https://github.com/vectordotdev/vector/issues/359 so I'll close this one, but let me know if I'm wrong!

**Closed by jszwedko** 2023-03-29 13:06 UTC
Labels: type: bug
