### ISSUE TITLE
希望sinks阶段数据写入clickhouse时支持性能更高的tcp连接

### ISSUE THREAD

**Issue by hjun881** [vectordotdev/vector#14917] opened 2022-10-22 00:49 UTC
### Use Cases

clickhouse官网默认支持tcp和http连接,可vector现在只支持http连接性能低并且不支持连接复用

### Proposal

clickhouse官网默认支持tcp和http连接,可vector现在只支持http连接,希望支持tcp连接并且可以设置连接复用来提高性能.

**Comment by hjun881** [comment] 2022-10-22 12:34
并且希望可以支持随机写,目前连接ck是一个http长连接导致只能和一台clickhouse建立连接，希望可以支持多连接与后端每一个clickhouse进行连接,特别是clickhouse 分片集群下能同时写多个片显著提高性能

**Comment by lroolle** [comment] 2022-10-23 02:16
WIP -> #14787

**Comment by jszwedko** [comment] 2022-10-24 13:38
Duplicate of https://github.com/vectordotdev/vector/issues/9000

**Closed by jszwedko** 2022-10-24 13:38 UTC
Labels: type: feature

**Comment by caibirdme** [comment] 2022-10-25 16:25
@hjun881 
You'd better add a (L4)VIP proxy before your clickhouse cluster, do not do load balancing on the client side by yourself.
And, native protocol is still working in progress, due to there's no production ready clickhouse rust sdk, So I have to develop the clickhouse sdk and vector clickhouse sink at the same time
