### ISSUE TITLE
Support an elasticsearch bulk source

### ISSUE THREAD

**Issue by nicolaipre** [vectordotdev/vector#15318] opened 2022-11-22 09:44 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

It would be nice to have Vector support a source type that simulates the elasticsearch bulk API. 

This will allow sending logs from i.e. Filebeat's ouptput type elasticsearch -> Vector.

### Attempted Solutions

I checked the possibility of using the splunk_hec source instead as the HTTP request for posting data was not too far off and thought I could hack around it by changing the URL. However, I did not think of the negotiation, which makes it fail.

Logstash can be used, but for secure transfers certificates are required there and it would be nice to be able to use HTTPS instead for simplicity.

Although I am using `vector 0.20.1` I have checked the most recent documentation for source types, and have not been able to find any elasticsearch source types.

### Proposal

I suppose the implementation would not differ too much from the splunk_hec source except for the initial negotiation with token or username authentication.

### Version

vector 0.20.1

**Comment by bruceg** [comment] 2022-11-25 23:40
I think this is a duplicate of #4600, so I'll close this in favor of that one. If you think this is in error, please reopen this issue.

**Closed by bruceg** 2022-11-25 23:40 UTC
Labels: domain: sources
