### ISSUE TITLE
Does the elasticsearch sink support multi endpoints?

### ISSUE THREAD

**Issue by OrdinaryFan** [vectordotdev/vector#6872] opened 2021-03-24 08:43 UTC
My elasticsearch has three nodes. What should i do to use all nodes?
Now the endpoint config only support one host.

**Comment by OrdinaryFan** [comment] 2021-03-24 08:47
`endpoint = ["http://host1:9201", "http://host2:9201", "http://host3:9201"]`

**Comment by OrdinaryFan** [comment] 2021-03-24 08:59
like the filebeat config:
```
output.elasticsearch:
  hosts: ["http://10.45.3.2:9220", "http://10.45.3.1:9230"] 
```

**Comment by gilgameshfreedom** [comment] 2021-07-01 16:09
+ 1

**Comment by sim0nx** [comment] 2021-09-27 19:52
Duplicate of https://github.com/vectordotdev/vector/issues/3649

**Comment by spencergilbert** [comment] 2021-09-29 13:50
As noted by @sim0nx - duplicate of an existing issue 🙂

**Closed by spencergilbert** 2021-09-29 13:50 UTC
Labels: type: enhancement
