### ISSUE TITLE
vector loses semantic meaning when using disk buffer and log_namespace

### ISSUE THREAD

**Issue by btmc** [vectordotdev/vector#18721] opened 2023-09-29 15:07 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm using `loki` sink and have noticed that no data goes to loki after I switched this sink to `disk` buffer type from the default (`memory`).

If I intentionally set `compression` to `none` and tcpdump HTTP traffic, going to loki, I see, that there is some traffic, but it only has labels and times, like so:

```
{"stream":{"image_repo":"xxx","image_tag":"yyy","machine":"ppp"},"values":[["1695996579716662799",""],["1695996579716680755",""],["1695996579716689345",""],["1695996579716697688",""],["1695996579716705774",""],["1695996579716714364",""],["1695996579716722063",""],["1695996579716730332",""],["1695996579716738233",""],["1695996579716747487",""],["1695996579716755751",""],["1695996579716762888",""],["1695996579716771260",""],["1695996579716780106",""],["1695996579716789274",""],["1695996579716796627",""],["1695996579716804167",""],["1695996579716811673",""],["1695996579716819854",""],["1695996579716829827",""],["1695996579716838275",""],["1695996579716845957",""],["1695996579716853697",""],["1695996579716861012",""],["1695996579716869723",""],["1695996579716877248",""],["1695996579716884456",""],["1695996579716893126",""],["1695996579716900689",""],["1695996579716911650",""],["1695996579716920265",""],["1695996579716927533",""]]},{"stream":{"pod_owner":...
```

The second field in the arrays should contain the message itself, but it is empty. I tried to switch back to `memory` type buffer (everything else in my config file stayed the same) and the messages reappeared in the dump and in loki.

If I open the file on disk, to which data going to the sink is buffered to, I can see, that the message is not empty and contains correct data, so it seems to be lost when read back from buffer and sent to loki.

I've already encountered a similar condition before, and it appeared to be that it was necessary to explicitly set the field in current context, which has "message" semantic meaning, with `set_semantic_meaning` function if you use `log_namespace` and one of encodings, dependent on semantic context (`text`, `raw_message`)
(they have "This encoding uses the message field of a log event." annotation in the documentation here: https://vector.dev/docs/reference/configuration/sinks/loki/#encoding.codec).

So I tried to switch from `text` encoding for the sink to `json` encoding, and the problem was also gone.

So I suppose the problem is the combination of using `text` or `raw_message` encoding and `disk` buffer, and `log_namespace` enabled.

### Configuration

Case 1: `text` encoding, `memory` buffer, data is correctly sent to loki:

Configure vector:

```
<<\Q cat > vector.toml
[schema]
log_namespace = true
Q

<<\Q cat > sources/socket.toml
type = "socket"
mode = "tcp"

address = "0.0.0.0:9090"
Q

<<\Q cat > transforms/remap.toml
type = "remap"

inputs = [ "socket" ]

source = '''
    .message = .

    set_semantic_meaning( .message,
                          "message" )
         '''
Q

<<\Q cat > sinks/loki.toml
type  = "loki"

inputs = [ "remap" ]

endpoint = "http://127.0.0.1:3100"

compression = "none"

[encoding]
    codec = "text"

[labels]
    label1 = "value1"
Q
```

Run the container:

```
docker run -it --rm \
               --net host \
                -v .:/etc/vector \
                 timberio/vector:0.33.0-alpine \
                  -C /etc/vector
```

Send the data:

```
echo 'test message' | nc 127.1 9090
```

Data is sent OK:

```
tcpdump -nnAiany port 3100

{"streams":[{"stream":{"label1":"value1"},"values":[["1695998808717666895","test message"]]}]}
```

Case 2: `text` encoding, `disk` buffer, data is NOT sent:

Reconfig only loki sink:

```
<<\Q cat > sinks/loki.toml
type  = "loki"

inputs = [ "remap" ]

endpoint = "http://127.0.0.1:3100"

compression = "none"

[buffer]
    type = "disk"
    max_size = 268435488

[encoding]
    codec = "text"

[labels]
    label1 = "value2"
Q
```

Run the container:

```
docker run -it --rm \
               --net host \
                -v .:/etc/vector \
                 timberio/vector:0.33.0-alpine \
                  -C /etc/vector
```

Send the data:

```
echo 'test message 2' | nc 127.1 9090
```

No data:

```
{"streams":[{"stream":{"label1":"value2"},"values":[["1695998941084384337",""]]}]}
```

Case 3: `json` encoding, `disk` buffer, data is also sent:

Reconfig only loki sink again:

```
<<\Q cat > sinks/loki.toml
type  = "loki"

inputs = [ "remap" ]

endpoint = "http://127.0.0.1:3100"

compression = "none"

[buffer]
    type = "disk"
    max_size = 268435488

[encoding]
    codec = "json"

[labels]
    label1 = "value3"
Q
```

Run the container:

```
docker run -it --rm \
               --net host \
                -v .:/etc/vector \
                 timberio/vector:0.33.0-alpine \
                  -C /etc/vector
```

Send the data:

```
echo 'test message 3' | nc 127.1 9090
```

It is sent, now in JSON format:

```
{"streams":[{"stream":{"label1":"value3"},"values":[["1695999017747189254","{\"message\":\"test message 3\"}"]]}]}
```
```


### Version

vector 0.33.0 (x86_64-unknown-linux-musl 89605fb 2023-09-27 14:18:24.180809939)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment] 2023-09-29 22:38
Thanks for filing this @btmc ! I think this is actually a duplicate of https://github.com/vectordotdev/vector/issues/11416. It is a bigger issue now that log namespacing has been released as a beta, though, so we'll try to get to it soon.

**Closed by jszwedko** 2023-09-29 22:38 UTC
Labels: type: bug
