### ISSUE TITLE
clickhouse sink table key is a string, not template-able

### ISSUE THREAD

**Issue by haithem-b-charrada** [vectordotdev/vector#8528] opened 2021-07-30 16:20 UTC
Hi there, the Docs say that the table key is a string, not template-able in clickhouse sink 
i'am trying to sink data in a table depending on attribute value

**Comment by Steuf** [comment] 2021-08-20 09:28
It's will be a good feature to add template on "table" and "database" param. In my (extreme) use case I have to setup sink on 3 databases and 5 table by database. 

Actually I have 15 sink setup for clickhouse (:/) and the real problem are in this case that the buffer max_size are difficult to setup ;)

**Comment by haithem-ben-charrada** [comment] 2021-08-23 09:34
@jszwedko

**Comment by haithem-ben-charrada** [comment] 2022-01-25 16:54
👍

**Comment by jszwedko** [comment] 2022-04-25 21:32
Duplicate of https://github.com/vectordotdev/vector/issues/7912

**Closed by jszwedko** 2022-04-25 21:32 UTC
Labels: sink: clickhouse, type: feature
